# SPDX-License-Identifier: Apache-2.0
# Copyright © 2025 Bijan Mousavi
"""Primary quantification Python API entrypoints."""

from __future__ import annotations

from bijux_proteomics.interfaces.python_api.quantify_runner import (
    run_quantify_command as _run_quantify_command,
)
from bijux_proteomics.interfaces.support.foundation import Path


def run_quantify_command(
    input_table: Path,
    measure: str,
    entity_level: str,
    aggregation: str,
    top_n: int,
    normalization: str,
    imputation: str,
    sample_column: str,
    feature_id_column: str,
    peptide_column: str,
    intensity_column: str,
    protein_refs_column: str | None,
    charge_column: str | None,
    mz_column: str | None,
    retention_time_column: str | None,
    missing_reason_column: str | None,
    protein_separator: str,
    design_path: Path | None,
    condition_a: str | None,
    condition_b: str | None,
    differential_tsv_out: Path | None,
    broken_pairs_tsv_out: Path | None,
    multi_contrast_consistency_tsv_out: Path | None,
    batch_effect_summary_tsv_out: Path | None,
    batch_effect_batches_tsv_out: Path | None,
    batch_effect_components_tsv_out: Path | None,
    time_course_tsv_out: Path | None,
    design_covariates: tuple[str, ...],
    design_batch_field: str,
    design_pairing_field: str | None,
    design_timepoint_field: str | None,
    design_timepoint_order_file: Path | None,
    design_matrix_tsv_out: Path | None,
    design_coefficients_tsv_out: Path | None,
    design_contrasts_tsv_out: Path | None,
    limma_assay_tsv_out: Path | None,
    limma_samples_tsv_out: Path | None,
    limma_design_tsv_out: Path | None,
    limma_contrasts_tsv_out: Path | None,
    msstats_input_tsv_out: Path | None,
    limma_results_path: Path | None,
    msstats_results_path: Path | None,
    report_out: Path | None,
    out_path: Path | None,
) -> None:
    return _run_quantify_command(
        input_table,
        measure,
        entity_level,
        aggregation,
        top_n,
        normalization,
        imputation,
        sample_column,
        feature_id_column,
        peptide_column,
        intensity_column,
        protein_refs_column,
        charge_column,
        mz_column,
        retention_time_column,
        missing_reason_column,
        protein_separator,
        design_path,
        condition_a,
        condition_b,
        differential_tsv_out,
        broken_pairs_tsv_out,
        multi_contrast_consistency_tsv_out,
        batch_effect_summary_tsv_out,
        batch_effect_batches_tsv_out,
        batch_effect_components_tsv_out,
        time_course_tsv_out,
        design_covariates,
        design_batch_field,
        design_pairing_field,
        design_timepoint_field,
        design_timepoint_order_file,
        design_matrix_tsv_out,
        design_coefficients_tsv_out,
        design_contrasts_tsv_out,
        limma_assay_tsv_out,
        limma_samples_tsv_out,
        limma_design_tsv_out,
        limma_contrasts_tsv_out,
        msstats_input_tsv_out,
        limma_results_path,
        msstats_results_path,
        report_out,
        out_path,
    )


__all__ = ["run_quantify_command"]
