# SPDX-License-Identifier: Apache-2.0
# Copyright © 2026 Bijan Mousavi

"""Governed adapter facade ledger for identification owner modules."""

from __future__ import annotations

from bijux_proteomics.identification.facade_ledger.models import (
    IdentificationFacadeBudget,
    IdentificationFacadeModule,
    build_facade_module,
)

ADAPTERS_FACADE_BUDGET = IdentificationFacadeBudget(
    max_public_symbols=180,
    max_init_lines=90,
)


def list_identification_adapter_api_modules() -> tuple[IdentificationFacadeModule, ...]:
    """Return the supported identification adapter-facade modules."""

    return (
        build_facade_module(
            "bijux_proteomics.identification.adapters.comet_import",
            "adapter_import_owner",
            "Comet import owner surface.",
            (
                "CometImportKind",
                "CometPsmReviewEntry",
                "CometCanonicalPsmEntry",
                "CometImportSummary",
                "CometImportReport",
                "build_comet_import_report",
                "render_comet_summary_tsv",
                "render_comet_canonical_psm_tsv",
                "render_comet_psm_tsv",
            ),
        ),
        build_facade_module(
            "bijux_proteomics.identification.adapters.diann_import",
            "adapter_import_owner",
            "DIA-NN import owner surface.",
            (
                "DiaNnPrecursorReviewEntry",
                "DiaNnProteinGroupReviewEntry",
                "DiaNnImportSummary",
                "DiaNnRejectedRowEntry",
                "DiaNnBundleImportReport",
                "build_diann_import_report",
                "render_diann_summary_tsv",
                "render_diann_precursor_tsv",
                "render_diann_protein_group_tsv",
                "render_diann_rejected_row_tsv",
            ),
        ),
        build_facade_module(
            "bijux_proteomics.identification.adapters.fragpipe_benchmarks",
            "adapter_benchmark_owner",
            "FragPipe import benchmark owner surface.",
            (
                "FragpipeCountComparisonEntry",
                "FragpipeImportBenchmarkReport",
                "FragpipeImportBenchmarkSummary",
                "FragpipeProteinGroupComparison",
                "FragpipeQValueBehaviorComparison",
                "FragpipeQValueComparisonEntry",
                "build_fragpipe_import_benchmark_report",
                "render_fragpipe_benchmark_summary_tsv",
                "render_fragpipe_count_comparisons_tsv",
                "render_fragpipe_protein_group_comparison_tsv",
                "render_fragpipe_q_value_comparison_tsv",
            ),
        ),
        build_facade_module(
            "bijux_proteomics.identification.adapters.fragpipe_import",
            "adapter_import_owner",
            "FragPipe import owner surface.",
            (
                "FragpipePsmReviewEntry",
                "FragpipeCanonicalPsmEntry",
                "FragpipePeptideReviewEntry",
                "FragpipeProteinReviewEntry",
                "FragpipeOpenSearchEvidenceEntry",
                "FragpipeProteinQuantityEntry",
                "FragpipeImportSummary",
                "FragpipeImportReport",
                "build_fragpipe_import_report",
                "render_fragpipe_summary_tsv",
                "render_fragpipe_canonical_psm_tsv",
                "render_fragpipe_psm_tsv",
                "render_fragpipe_peptide_tsv",
                "render_fragpipe_protein_tsv",
                "render_fragpipe_open_search_evidence_tsv",
                "render_fragpipe_protein_quantity_tsv",
            ),
        ),
        build_facade_module(
            "bijux_proteomics.identification.adapters.maxquant_import",
            "adapter_import_owner",
            "MaxQuant import owner surface.",
            (
                "MaxquantLfqIntensityEntry",
                "MaxquantEvidenceReviewEntry",
                "MaxquantPeptideReviewEntry",
                "MaxquantProteinGroupReviewEntry",
                "MaxquantLfqMatrixCandidateEntry",
                "MaxquantImportSummary",
                "MaxquantImportReport",
                "build_maxquant_import_report",
                "render_maxquant_summary_tsv",
                "render_maxquant_evidence_tsv",
                "render_maxquant_peptide_tsv",
                "render_maxquant_protein_group_tsv",
                "render_maxquant_lfq_candidate_tsv",
                "build_maxquant_lfq_matrix_candidates",
            ),
        ),
        build_facade_module(
            "bijux_proteomics.identification.adapters.openms_import",
            "adapter_import_owner",
            "OpenMS import owner surface.",
            (
                "OpenMsPsmReviewEntry",
                "OpenMsProteinReviewEntry",
                "OpenMsFeatureReviewEntry",
                "OpenMsFeatureValidationIssue",
                "OpenMsRejectedFeatureRow",
                "OpenMsImportSummary",
                "OpenMsFeatureParseSummary",
                "OpenMsImportReport",
                "build_openms_import_report",
                "render_openms_summary_tsv",
                "render_openms_psm_tsv",
                "render_openms_protein_tsv",
                "render_openms_feature_tsv",
                "render_openms_rejected_feature_tsv",
            ),
        ),
        build_facade_module(
            "bijux_proteomics.identification.adapters.sage_import",
            "adapter_import_owner",
            "Sage import owner surface.",
            (
                "SagePsmReviewEntry",
                "SageCanonicalPsmEntry",
                "SageImportSummary",
                "SageImportReport",
                "build_sage_import_report",
                "render_sage_summary_tsv",
                "render_sage_canonical_psm_tsv",
                "render_sage_psm_tsv",
            ),
        ),
        build_facade_module(
            "bijux_proteomics.identification.adapters.search_adapter_loss",
            "adapter_review_owner",
            "Search-adapter loss and parity owner surface.",
            (
                "SearchAdapterInformationLossReport",
                "ProteinInferenceDisagreementEntry",
                "ProteinInferenceEngineDisagreementDossier",
                "SearchAdapterParityCheck",
                "SearchAdapterParityReport",
                "build_search_adapter_information_loss_report",
                "build_protein_inference_engine_disagreement_dossier",
                "build_search_adapter_parity_report",
            ),
        ),
        build_facade_module(
            "bijux_proteomics.identification.adapters.spectronaut_import",
            "adapter_import_owner",
            "Spectronaut import owner surface.",
            (
                "SpectronautPrecursorReviewEntry",
                "SpectronautProteinGroupReviewEntry",
                "SpectronautPrecursorQuantityEntry",
                "SpectronautProteinGroupQuantityEntry",
                "SpectronautImportSummary",
                "SpectronautImportReport",
                "build_spectronaut_import_report",
                "render_spectronaut_summary_tsv",
                "render_spectronaut_precursor_tsv",
                "render_spectronaut_protein_group_tsv",
                "render_spectronaut_precursor_quantity_tsv",
                "render_spectronaut_protein_group_quantity_tsv",
            ),
        ),
        build_facade_module(
            "bijux_proteomics.identification.search_adapters",
            "search_adapter_owner",
            "Typed search-adapter family facade for normalized search-result workflows.",
            (
                "CalibrationPlotData",
                "FdrAuditTrail",
                "PsmParseReport",
                "PsmRecord",
                "ScoreOrientation",
                "SearchAdapterCapability",
                "SearchAdapterConformanceCheck",
                "SearchAdapterConformanceReport",
                "SearchAdapterCorpusConformanceEntry",
                "SearchAdapterCorpusConformanceMatrix",
                "SearchAdapterDialectManifest",
                "SearchAdapterFieldAccounting",
                "SearchAdapterKind",
                "SearchAdapterManifest",
                "SearchAdapterNormalizationReport",
                "SearchAdapterProvenanceManifest",
                "SearchConfigValidationIssue",
                "SearchConfigValidationReport",
                "SearchCorpusInputSpecification",
                "SearchCorpusNormalizationEntry",
                "SearchEngineCorpusReport",
                "SearchEngineObservation",
                "SearchInputAssessmentReport",
                "SearchInputRefusal",
                "SearchInputRefusalKind",
                "SearchMergeAgreementStatus",
                "SearchMergeCompatibilityIssue",
                "SearchMergeCompatibilityReport",
                "SearchModificationDefinition",
                "SearchNormalizedEvidenceEntry",
                "SearchParameterComparisonReport",
                "SearchParameterDifferenceEntry",
                "SearchParameterReport",
                "SearchRegressionCorpusEntry",
                "SearchRegressionCorpusManifest",
                "SearchRegressionFixtureKind",
                "SearchResultColumnMapping",
                "SearchResultComparabilityReport",
                "SearchResultFamily",
                "SearchResultFamilyPolicy",
                "SearchResultMergeReport",
                "SearchResultProvenanceManifest",
                "SearchResultValidationIssue",
                "SearchScoreFamily",
                "SearchToleranceUnit",
                "TargetDecoyLabel",
                "TargetDecoyLabelPolicy",
                "assess_search_merge_compatibility",
                "assess_search_result_input",
                "build_search_adapter_capability_matrix",
                "build_search_adapter_conformance_report",
                "build_search_adapter_corpus_conformance_matrix",
                "build_search_adapter_provenance_manifest",
                "build_search_adapter_regression_corpus_manifest",
                "build_search_result_family_policy",
                "compare_search_parameters",
                "compare_search_result_reports",
                "get_search_adapter_manifest",
                "merge_search_result_reports",
                "merge_search_result_reports_with_compatibility",
                "normalize_search_results_with_adapter",
                "parse_psm_tsv",
                "parse_search_parameter_file",
                "search_adapter_dialect_registry",
                "search_adapter_registry",
                "validate_search_parameters",
                "build_comet_output_corpus_report",
                "build_diann_output_corpus_report",
                "build_external_engine_disagreement_report",
                "build_maxquant_output_corpus_report",
                "build_msfragger_output_corpus_report",
                "build_sage_output_corpus_report",
                "build_search_engine_corpus_report",
                "build_spectronaut_output_corpus_report",
            ),
        ),
    )


__all__ = ["ADAPTERS_FACADE_BUDGET", "list_identification_adapter_api_modules"]
