# SPDX-License-Identifier: Apache-2.0
# Copyright © 2026 Bijan Mousavi

"""Governed contract facade ledger for identification owner modules."""

from __future__ import annotations

from bijux_proteomics.identification.facade_ledger.models import (
    IdentificationFacadeBudget,
    IdentificationFacadeModule,
    build_facade_module,
)

CONTRACTS_FACADE_BUDGET = IdentificationFacadeBudget(
    max_public_symbols=140,
    max_init_lines=90,
)


def list_identification_contract_api_modules() -> tuple[
    IdentificationFacadeModule, ...
]:
    """Return the supported identification contract-facade modules."""

    return (
        build_facade_module(
            "bijux_proteomics.identification.contracts.psm",
            "identification_contract_owner",
            "Canonical PSM contract owner surface.",
            (
                "TargetDecoyLabel",
                "TargetDecoyContaminantClass",
                "PsmSortField",
                "SearchResultColumnMapping",
                "TargetDecoyLabelPolicy",
                "TargetDecoyContaminantClassification",
                "PsmRecord",
                "SearchResultValidationIssue",
                "RejectedPsmRow",
                "PsmParseReport",
                "TargetDecoyCollisionEntry",
                "TargetDecoyCollisionReport",
                "DecoyStrategyValidationIssue",
                "DecoyStrategyValidationReport",
                "classify_target_decoy_contaminant",
                "is_biological_foreground_class",
                "validate_target_decoy_policy",
                "parse_target_decoy_label",
                "validate_target_decoy_accession_collisions",
            ),
        ),
        build_facade_module(
            "bijux_proteomics.identification.contracts.psm_io",
            "identification_contract_owner",
            "PSM parsing and export contract owner surface.",
            (
                "parse_psm_tsv",
                "parse_psm_tsv_chunked",
                "normalize_psm_records",
                "export_psm_jsonl",
                "export_psm_tsv",
                "sort_psm_records",
                "select_best_psm_per_spectrum",
            ),
        ),
        build_facade_module(
            "bijux_proteomics.identification.contracts.evidence",
            "identification_contract_owner",
            "Peptide and protein evidence rollup contract owner surface.",
            (
                "PeptideEvidenceEntry",
                "ProteinEvidenceEntry",
                "PsmSummaryReport",
                "PeptideSummaryReport",
                "ProteinSummaryEntry",
                "ProteinSummaryReport",
                "rollup_peptide_evidence",
                "rollup_protein_evidence",
                "build_psm_summary_report",
                "build_peptide_summary_report",
                "build_protein_summary_report",
            ),
        ),
        build_facade_module(
            "bijux_proteomics.identification.contracts.confidence",
            "identification_contract_owner",
            "Confidence assignment contract owner surface.",
            (
                "ConfidenceLabel",
                "ConfidenceAssignment",
                "GroupedConfidenceEntry",
                "GroupedConfidenceReport",
                "LevelSpecificConfidenceAssignment",
                "LevelSpecificConfidenceReport",
                "ConfidenceThresholdSensitivityEntry",
                "ConfidenceThresholdSensitivityReport",
                "assign_confidence_labels",
                "build_grouped_confidence_report",
                "assign_level_specific_confidence_labels",
                "build_confidence_threshold_sensitivity_report",
            ),
        ),
        build_facade_module(
            "bijux_proteomics.identification.contracts.fdr_levels",
            "identification_contract_owner",
            "Level-specific and grouped FDR contract owner surface.",
            (
                "LevelSpecificFdrReport",
                "FdrQValueMonotonicityCheck",
                "FdrQValueMonotonicityReport",
                "FdrEvidenceLevel",
                "FdrLevelEntry",
                "GroupedFdrBucket",
                "GroupedFdrReport",
                "NormalizedScoreEntry",
                "AcceptedPsmProvenanceEntry",
                "AcceptedPsmProvenanceReport",
                "build_accepted_psm_provenance_report",
                "calculate_level_specific_fdr",
                "calculate_grouped_fdr",
                "calculate_basic_target_decoy_fdr",
                "normalize_psm_score_orientation",
                "verify_fdr_q_value_monotonicity",
            ),
        ),
        build_facade_module(
            "bijux_proteomics.identification.contracts.grouping",
            "identification_contract_owner",
            "Grouping and razor-peptide contract owner surface.",
            (
                "SharedPeptideAmbiguityReason",
                "ProteinGroupEntry",
                "SharedPeptideAmbiguityEntry",
                "SharedPeptideAmbiguityReport",
                "RazorPeptideAssignment",
                "RazorPeptideProvenanceEntry",
                "RazorPeptideProvenanceReport",
                "build_protein_groups",
                "build_shared_peptide_ambiguity_report",
                "assign_razor_peptides",
                "build_razor_peptide_provenance_report",
            ),
        ),
        build_facade_module(
            "bijux_proteomics.identification.contracts.protein_inference",
            "identification_contract_owner",
            "Protein inference contract owner surface.",
            (
                "ParsimonyVariant",
                "ParsimonyProteinEntry",
                "InferenceDisagreementKind",
                "InferenceDisagreementEntry",
                "InferenceDisagreementReport",
                "ParsimonyVariantResult",
                "ParsimonyVariantDifferenceEntry",
                "ParsimonyVariantComparisonReport",
                "build_inference_disagreement_report",
                "infer_proteins_by_parsimony",
                "compare_parsimony_variants",
            ),
        ),
        build_facade_module(
            "bijux_proteomics.identification.contracts.protein_review",
            "identification_contract_owner",
            "Protein review contract owner surface.",
            (
                "CombinedEvidenceQuantSupport",
                "CombinedEvidenceEntry",
                "CombinedEvidenceReport",
                "PeptideProteinTraceEntry",
                "PeptideProteinTraceReport",
                "ProteinCoverageEntry",
                "DatabasePeptideUniqueness",
                "DatabasePeptideUniquenessEntry",
                "PickedProteinFdrEntry",
                "build_combined_evidence_report",
                "build_peptide_protein_trace_report",
                "export_peptide_protein_trace_jsonl",
                "export_peptide_protein_trace_tsv",
                "build_protein_coverage_map",
                "build_peptide_uniqueness_across_database",
                "calculate_picked_protein_fdr",
            ),
        ),
        build_facade_module(
            "bijux_proteomics.identification.contracts.score_fdr",
            "identification_contract_owner",
            "Score and audit contract owner surface for FDR outputs.",
            (
                "FdrPolicy",
                "FdrAnnotatedPsm",
                "CalibrationPlotBin",
                "CalibrationPlotData",
                "ScoreOrientationAdvisoryCandidate",
                "ScoreOrientationAdvisory",
                "FdrAuditEntry",
                "FdrAuditTrail",
                "FdrEdgeCaseKind",
                "FdrEdgeCaseReport",
                "ConfidenceCalibrationLevel",
                "ConfidenceCalibrationEntry",
                "ConfidenceCalibrationReport",
                "detect_score_orientation_advisory",
                "build_confidence_calibration_report",
                "build_calibration_plot_data",
                "build_fdr_edge_case_report",
                "compute_fdr_reproducibility_hash",
                "build_fdr_audit_trail",
                "apply_q_values",
                "filter_psms_by_fdr",
            ),
        ),
        build_facade_module(
            "bijux_proteomics.identification.contracts.review",
            "identification_contract_owner",
            "Review-bundle contract owner surface for identification outputs.",
            (
                "SearchResultProvenanceManifest",
                "ReviewReadyEvidenceBundle",
                "PtmIdentificationObservation",
                "PtmIdentificationConfidenceIssue",
                "PtmIdentificationConfidenceEntry",
                "PtmIdentificationConfidenceReport",
                "validate_ptm_identification_confidence",
                "build_review_ready_evidence_bundle",
                "export_review_ready_evidence_bundle",
                "write_review_ready_evidence_bundle",
                "build_search_result_provenance_manifest",
            ),
        ),
    )


__all__ = ["CONTRACTS_FACADE_BUDGET", "list_identification_contract_api_modules"]
