PROJECT_ARTIFACTS_DIR ?= artifacts
DOCS_PYTHON ?= $(if $(wildcard $(VENV_PYTHON)),$(abspath $(VENV_PYTHON)),$(if $(wildcard $(VENV)/bin/python),$(abspath $(VENV)/bin/python),$(shell command -v python3 || command -v python)))
DOCS_SITE_DIR ?= $(PROJECT_ARTIFACTS_DIR)/root/docs/site
DOCS_BUILD_SITE_DIR ?= $(DOCS_SITE_DIR)
DOCS_CHECK_SITE_DIR ?= $(DOCS_SITE_DIR)
DOCS_SERVE_SITE_DIR ?= $(DOCS_SITE_DIR)
DOCS_CACHE_DIR ?= $(PROJECT_ARTIFACTS_DIR)/root/docs/.cache
DOCS_BUILD_CONFIG_FILE ?= $(MKDOCS_CFG)
DOCS_CHECK_CONFIG_FILE ?= $(MKDOCS_CFG)
DOCS_SERVE_CONFIG_FILE ?= $(MKDOCS_CFG)
DOCS_BUILD_PREPARE_TARGETS :=
DOCS_CHECK_PREPARE_TARGETS :=
DOCS_SERVE_PREPARE_TARGETS :=
DOCS_BUILD_PRE_CLEAN_PATHS ?= $(DOCS_BUILD_SITE_DIR) $(DOCS_CACHE_DIR)
DOCS_CHECK_PRE_CLEAN_PATHS ?= $(DOCS_CHECK_SITE_DIR) $(DOCS_CACHE_DIR)
DOCS_EXTRA_CLEAN_PATHS ?= $(DOCS_SITE_DIR) $(DOCS_CACHE_DIR)
DOCS_ADDR ?= 127.0.0.1:8001
DOCS_DEV_ADDR ?= $(DOCS_ADDR)

include $(abspath $(dir $(lastword $(MAKEFILE_LIST))))/bijux-py/docs.mk
