PACKAGE_KIND ?= repository-python
MYPY_CONFIG ?= $(MONOREPO_ROOT)/configs/mypy.ini
API_MODE ?= freeze
ENABLE_MYPY ?= 0
PYDOCSTYLE_ARGS ?= --convention=google --add-ignore=D100,D101,D102,D103,D104,D105,D106,D107
ENABLE_PYDOCSTYLE ?= 1
QUALITY_MYPY_CONFIG ?= $(MYPY_CONFIG)
QUALITY_MYPY_TARGETS ?= $(QUALITY_PATHS)
QUALITY_VULTURE_MIN_CONFIDENCE ?= 90
SECURITY_IGNORE_IDS ?= PYSEC-2022-42969 CVE-2025-68463
SECURITY_BANDIT_SKIP_IDS ?= B311
SECURITY_PIP_AUDIT_TEXT_COMMAND ?= PYTHONPATH="$(MONOREPO_ROOT)/packages/bijux-proteomics-dev/src$${PYTHONPATH:+:$$PYTHONPATH}" "$(VENV_PYTHON)" -m bijux_proteomics_dev.security.pip_audit_gate
BUILD_PER_PACKAGE_DIRS ?= 1
API_FREEZE_COMMAND ?= $(VENV_PYTHON) -m bijux_proteomics_dev.api.freeze_contracts
API_OPENAPI_DRIFT_COMMAND ?= $(VENV_PYTHON) -m bijux_proteomics_dev.api.openapi_drift
