version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - github

  - package-ecosystem: npm
    directory: "/configs"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - javascript

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - python

  - package-ecosystem: pip
    directory: "/packages/agentic-proteins"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - python

  - package-ecosystem: pip
    directory: "/packages/bijux-proteomics-core"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - python

  - package-ecosystem: pip
    directory: "/packages/bijux-proteomics-dev"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - python

  - package-ecosystem: pip
    directory: "/packages/bijux-proteomics-foundation"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - python

  - package-ecosystem: pip
    directory: "/packages/bijux-proteomics-intelligence"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - python

  - package-ecosystem: pip
    directory: "/packages/bijux-proteomics-knowledge"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - python

  - package-ecosystem: pip
    directory: "/packages/bijux-proteomics-lab"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - python
