# SPDX-License-Identifier: Apache-2.0
# Copyright © 2025 Bijan Mousavi

from __future__ import annotations

import bijux_proteomics
import bijux_proteomics_intelligence
import bijux_proteomics_knowledge
import bijux_proteomics_lab


def test_core_public_api_contains_expected_exports() -> None:
    assert "ProgramSpec" in bijux_proteomics.__all__
    assert "ExecutionBackend" in bijux_proteomics.__all__
    assert "ProteinSequence" in bijux_proteomics.__all__
    assert "FastaParseReport" in bijux_proteomics.__all__
    assert "SequenceResiduePolicy" in bijux_proteomics.__all__
    assert "build_sequence_residue_policy" in bijux_proteomics.__all__
    assert "generate_decoy_records" in bijux_proteomics.__all__
    assert "DecoyGenerationManifest" in bijux_proteomics.__all__
    assert "build_decoy_generation_manifest" in bijux_proteomics.__all__
    assert "compute_decoy_generation_reproducibility_hash" in bijux_proteomics.__all__
    assert "validate_target_decoy_database" in bijux_proteomics.__all__
    assert "digest_sequence" in bijux_proteomics.__all__
    assert "DigestDuplicateAccounting" in bijux_proteomics.__all__
    assert "build_digest_duplicate_accounting" in bijux_proteomics.__all__
    assert "DigestPolicy" in bijux_proteomics.__all__
    assert "build_digest_policy" in bijux_proteomics.__all__
    assert "compute_digest_policy_hash" in bijux_proteomics.__all__
    assert "protease_registry" in bijux_proteomics.__all__
    assert "build_peptide_protein_index" in bijux_proteomics.__all__
    assert "PeptideOriginCoordinate" in bijux_proteomics.__all__
    assert "calculate_monoisotopic_peptide_mass" in bijux_proteomics.__all__
    assert "calculate_fragment_ions" in bijux_proteomics.__all__
    assert "validate_modified_peptide_fragment_ions" in bijux_proteomics.__all__
    assert "enumerate_variable_modifications" in bijux_proteomics.__all__
    assert "modification_registry" in bijux_proteomics.__all__
    assert "canonicalize_modified_peptide" in bijux_proteomics.__all__
    assert "build_peptide_charge_state" in bijux_proteomics.__all__
    assert "approximate_peptide_isotope_envelope" in bijux_proteomics.__all__
    assert "ModificationLocalizationState" in bijux_proteomics.__all__
    assert "ModificationProvenance" in bijux_proteomics.__all__
    assert "validate_modification_registry" in bijux_proteomics.__all__
    assert "IsotopicLabelingPolicy" in bijux_proteomics.__all__
    assert "PsmRecord" in bijux_proteomics.__all__
    assert "parse_psm_tsv" in bijux_proteomics.__all__
    assert "rollup_protein_evidence" in bijux_proteomics.__all__
    assert "filter_psms_by_fdr" in bijux_proteomics.__all__
    assert "build_fdr_audit_trail" in bijux_proteomics.__all__
    assert "build_fdr_edge_case_report" in bijux_proteomics.__all__
    assert "compute_fdr_reproducibility_hash" in bijux_proteomics.__all__
    assert "validate_target_decoy_accession_collisions" in bijux_proteomics.__all__
    assert "verify_fdr_q_value_monotonicity" in bijux_proteomics.__all__
    assert "build_accepted_psm_provenance_report" in bijux_proteomics.__all__
    assert "build_confidence_threshold_sensitivity_report" in bijux_proteomics.__all__
    assert "normalize_psm_score_orientation" in bijux_proteomics.__all__
    assert "detect_score_orientation_advisory" in bijux_proteomics.__all__
    assert "calculate_level_specific_fdr" in bijux_proteomics.__all__
    assert "assign_level_specific_confidence_labels" in bijux_proteomics.__all__
    assert "calculate_grouped_fdr" in bijux_proteomics.__all__
    assert "calculate_picked_protein_fdr" in bijux_proteomics.__all__
    assert "build_protein_groups" in bijux_proteomics.__all__
    assert "build_shared_peptide_ambiguity_report" in bijux_proteomics.__all__
    assert "infer_proteins_by_parsimony" in bijux_proteomics.__all__
    assert "assign_razor_peptides" in bijux_proteomics.__all__
    assert "build_protein_coverage_map" in bijux_proteomics.__all__
    assert "build_peptide_uniqueness_across_database" in bijux_proteomics.__all__
    assert "assign_confidence_labels" in bijux_proteomics.__all__
    assert "build_search_result_provenance_manifest" in bijux_proteomics.__all__
    assert "export_psm_tsv" in bijux_proteomics.__all__
    assert "SpectrumModel" in bijux_proteomics.__all__
    assert "parse_mgf" in bijux_proteomics.__all__
    assert "build_spectrum_lookup_index" in bijux_proteomics.__all__
    assert "build_annotated_spectrum_bundle" in bijux_proteomics.__all__
    assert "lookup_spectra" in bijux_proteomics.__all__
    assert "annotate_spectrum_fragments" in bijux_proteomics.__all__
    assert "SpectrumAnnotationAmbiguityWarning" in bijux_proteomics.__all__
    assert "calculate_spectral_similarity" in bijux_proteomics.__all__
    assert "SpectrumSimilarityMode" in bijux_proteomics.__all__
    assert "detect_precursor_isotope_offset_advisory" in bijux_proteomics.__all__
    assert "build_spectrum_provenance_manifest" in bijux_proteomics.__all__
    assert "parse_mzml" in bijux_proteomics.__all__
    assert "detect_proteomics_format" in bijux_proteomics.__all__
    assert "diagnose_proteomics_format" in bijux_proteomics.__all__
    assert "build_normalized_run_bundle" in bijux_proteomics.__all__
    assert "normalize_search_results_with_adapter" in bijux_proteomics.__all__
    assert "build_search_adapter_capability_matrix" in bijux_proteomics.__all__
    assert "build_search_engine_corpus_report" in bijux_proteomics.__all__
    assert "build_comet_output_corpus_report" in bijux_proteomics.__all__
    assert "build_msfragger_output_corpus_report" in bijux_proteomics.__all__
    assert "build_sage_output_corpus_report" in bijux_proteomics.__all__
    assert "build_maxquant_output_corpus_report" in bijux_proteomics.__all__
    assert "build_diann_output_corpus_report" in bijux_proteomics.__all__
    assert "build_spectronaut_output_corpus_report" in bijux_proteomics.__all__
    assert "parse_search_parameter_file" in bijux_proteomics.__all__
    assert "validate_search_parameters" in bijux_proteomics.__all__
    assert "compare_search_result_reports" in bijux_proteomics.__all__
    assert "assess_search_merge_compatibility" in bijux_proteomics.__all__
    assert "merge_search_result_reports_with_compatibility" in bijux_proteomics.__all__
    assert "build_search_adapter_conformance_report" in bijux_proteomics.__all__
    assert "build_search_adapter_corpus_conformance_matrix" in bijux_proteomics.__all__
    assert "build_external_engine_disagreement_report" in bijux_proteomics.__all__
    assert "SearchAdapterKind" in bijux_proteomics.__all__
    assert "build_target_decoy_strategy_registry" in bijux_proteomics.__all__
    assert "build_empirical_score_calibration_report" in bijux_proteomics.__all__
    assert "compare_protein_inference_strategies" in bijux_proteomics.__all__
    assert "build_psm_peptide_protein_trace_bundle" in bijux_proteomics.__all__
    assert "build_confidence_threshold_sensitivity_bundle" in bijux_proteomics.__all__
    assert "build_grouped_confidence_summary_report" in bijux_proteomics.__all__
    assert "validate_custom_decoy_strategy" in bijux_proteomics.__all__
    assert "evaluate_library_search_confidence_boundary" in bijux_proteomics.__all__
    assert "build_dia_native_fdr_model_report" in bijux_proteomics.__all__
    assert "build_inference_disagreement_review_packet" in bijux_proteomics.__all__
    assert "TargetDecoyStrategyKind" in bijux_proteomics.__all__
    assert "EmpiricalScoreCalibrationReport" in bijux_proteomics.__all__
    assert "ProteinInferenceStrategyComparisonReport" in bijux_proteomics.__all__
    assert "PsmPeptideProteinTraceBundle" in bijux_proteomics.__all__
    assert "ConfidenceThresholdSensitivityBundle" in bijux_proteomics.__all__
    assert "GroupedConfidenceSummaryReport" in bijux_proteomics.__all__
    assert "CustomDecoyValidationReport" in bijux_proteomics.__all__
    assert "LibrarySearchConfidenceBoundaryReport" in bijux_proteomics.__all__
    assert "DiaNativeFdrModelReport" in bijux_proteomics.__all__
    assert "InferenceDisagreementReviewPacket" in bijux_proteomics.__all__
    assert "Ms1FeatureRecord" in bijux_proteomics.__all__
    assert "parse_ms1_feature_table" in bijux_proteomics.__all__
    assert "build_label_free_intensity_table" in bijux_proteomics.__all__
    assert "build_normalization_comparison_report" in bijux_proteomics.__all__
    assert "build_protein_quant_rollup_evidence" in bijux_proteomics.__all__
    assert "build_quant_matrix_export" in bijux_proteomics.__all__
    assert "build_spectral_count_table" in bijux_proteomics.__all__
    assert "normalize_label_free_table" in bijux_proteomics.__all__
    assert "build_batch_effect_advisory" in bijux_proteomics.__all__
    assert "build_replicate_correlation_report" in bijux_proteomics.__all__
    assert "build_differential_abundance_report" in bijux_proteomics.__all__
    assert "build_lfq_feature_peptide_protein_provenance_report" in bijux_proteomics.__all__
    assert "build_label_based_quant_channel_ledger" in bijux_proteomics.__all__
    assert "build_multiplex_channel_balance_diagnostics_report" in bijux_proteomics.__all__
    assert "build_normalization_policy_comparison_matrix_report" in bijux_proteomics.__all__
    assert "build_protein_rollup_strategy_comparison_report" in bijux_proteomics.__all__
    assert "validate_differential_abundance_design_context" in bijux_proteomics.__all__
    assert "build_effect_size_first_differential_abundance_report" in bijux_proteomics.__all__
    assert "build_missingness_mechanism_profile_report" in bijux_proteomics.__all__
    assert "build_replicate_and_batch_qc_report" in bijux_proteomics.__all__
    assert "build_quant_review_bundle" in bijux_proteomics.__all__
    assert "DifferentialReplicatePolicy" in bijux_proteomics.__all__
    assert "LfqFeaturePeptideProteinProvenanceReport" in bijux_proteomics.__all__
    assert "LabelBasedQuantChannelLedgerReport" in bijux_proteomics.__all__
    assert "MultiplexChannelBalanceDiagnosticsReport" in bijux_proteomics.__all__
    assert "NormalizationPolicyComparisonMatrixReport" in bijux_proteomics.__all__
    assert "ProteinRollupStrategyComparisonReport" in bijux_proteomics.__all__
    assert "DifferentialAbundanceDesignValidationReport" in bijux_proteomics.__all__
    assert "EffectSizeFirstDaReport" in bijux_proteomics.__all__
    assert "MissingnessMechanismProfileReport" in bijux_proteomics.__all__
    assert "ReplicateAndBatchQcReport" in bijux_proteomics.__all__
    assert "QuantReviewBundle" in bijux_proteomics.__all__
    assert "DifferentialAbundanceAssumptionReport" in bijux_proteomics.__all__
    assert "MissingValueCorrectionPolicy" in bijux_proteomics.__all__
    assert "MissingValueSummaryPolicy" in bijux_proteomics.__all__
    assert "apply_benjamini_hochberg" in bijux_proteomics.__all__
    assert "PtmEvidenceRecord" in bijux_proteomics.__all__
    assert "parse_ptm_localization_tsv" in bijux_proteomics.__all__
    assert "map_ptm_evidence_to_protein_sites" in bijux_proteomics.__all__
    assert "validate_ptm_site_coordinates" in bijux_proteomics.__all__
    assert "build_ptm_site_table" in bijux_proteomics.__all__
    assert "build_ptm_site_fdr" in bijux_proteomics.__all__
    assert "estimate_ptm_site_occupancy" in bijux_proteomics.__all__
    assert "build_ptm_site_localization_evidence_graph" in bijux_proteomics.__all__
    assert "evaluate_ptm_site_fdr_boundary" in bijux_proteomics.__all__
    assert "build_ptm_occupancy_counterpart_report" in bijux_proteomics.__all__
    assert "build_ptm_motif_enrichment_background_provenance_report" in bijux_proteomics.__all__
    assert "build_phospho_specific_review_fixture_report" in bijux_proteomics.__all__
    assert "build_acetyl_specific_review_fixture_report" in bijux_proteomics.__all__
    assert "build_ubiquitin_remnant_workflow_report" in bijux_proteomics.__all__
    assert "evaluate_glycopeptide_support_boundary" in bijux_proteomics.__all__
    assert "build_ptm_cooccurrence_caution_report" in bijux_proteomics.__all__
    assert "build_ptm_lab_validation_packet" in bijux_proteomics.__all__
    assert "build_ptm_motif_background_report" in bijux_proteomics.__all__
    assert "PtmOccupancyUncertainty" in bijux_proteomics.__all__
    assert "PtmSiteLocalizationEvidenceGraph" in bijux_proteomics.__all__
    assert "PtmSiteFdrBoundaryReport" in bijux_proteomics.__all__
    assert "PtmOccupancyCounterpartEvidenceReport" in bijux_proteomics.__all__
    assert "PtmMotifEnrichmentBackgroundProvenanceReport" in bijux_proteomics.__all__
    assert "PtmPhosphoReviewFixtureReport" in bijux_proteomics.__all__
    assert "PtmAcetylReviewFixtureReport" in bijux_proteomics.__all__
    assert "UbiquitinRemnantWorkflowReport" in bijux_proteomics.__all__
    assert "GlycopeptideSupportBoundaryReport" in bijux_proteomics.__all__
    assert "PtmCooccurrenceCautionReport" in bijux_proteomics.__all__
    assert "PtmLabValidationPacket" in bijux_proteomics.__all__
    assert "build_lcms_run_qc_report" in bijux_proteomics.__all__
    assert "build_instrument_batch_qc_report" in bijux_proteomics.__all__
    assert "build_study_qc_summary" in bijux_proteomics.__all__
    assert "default_qc_threshold_policy" in bijux_proteomics.__all__
    assert "build_qc_threshold_profile" in bijux_proteomics.__all__
    assert "build_run_qc_assessment" in bijux_proteomics.__all__
    assert "build_qc_evidence_manifest" in bijux_proteomics.__all__
    assert "build_qc_publication_decision" in bijux_proteomics.__all__
    assert "build_qc_run_bundle_summary" in bijux_proteomics.__all__
    assert "build_performance_snapshot" in bijux_proteomics.__all__
    assert "build_proteomics_workflow_manifest" in bijux_proteomics.__all__
    assert "build_reproducible_workflow_blueprint" in bijux_proteomics.__all__
    assert "build_workflow_manifest_explanation_report" in bijux_proteomics.__all__
    assert "build_workflow_rerun_comparison_artifact" in bijux_proteomics.__all__
    assert "build_workflow_step_provenance_report" in bijux_proteomics.__all__
    assert "build_workflow_replay_proof_report" in bijux_proteomics.__all__
    assert "build_workflow_runtime_archive_bundle" in bijux_proteomics.__all__
    assert "build_proteomics_dag_plan" in bijux_proteomics.__all__
    assert "build_containerized_step_specs" in bijux_proteomics.__all__
    assert "build_workflow_cache_miss_explanation_report" in bijux_proteomics.__all__
    assert "build_deterministic_execution_contract" in bijux_proteomics.__all__
    assert "build_external_tool_capability_report" in bijux_proteomics.__all__
    assert "build_external_search_tool_contract" in bijux_proteomics.__all__
    assert "build_workflow_diff_report" in bijux_proteomics.__all__
    assert "build_workflow_execution_readiness_report" in bijux_proteomics.__all__
    assert "build_proteomics_workflow_template" in bijux_proteomics.__all__
    assert "instantiate_proteomics_workflow_template" in bijux_proteomics.__all__
    assert "build_hpc_job_descriptor" in bijux_proteomics.__all__
    assert "build_workflow_runtime_cache" in bijux_proteomics.__all__
    assert "build_proteomics_artifact_inventory" in bijux_proteomics.__all__
    assert "build_proteomics_artifact_registry" in bijux_proteomics.__all__
    assert "build_large_file_streaming_policy" in bijux_proteomics.__all__
    assert "build_parallel_execution_plan" in bijux_proteomics.__all__
    assert "build_workflow_run_directory_layout" in bijux_proteomics.__all__
    assert "build_workflow_runtime_export_bundle" in bijux_proteomics.__all__
    assert "import_workflow_runtime_archive_bundle" in bijux_proteomics.__all__
    assert "build_workflow_runtime_validation_report" in bijux_proteomics.__all__
    assert "build_workflow_runtime_state_manifest" in bijux_proteomics.__all__
    assert "build_workflow_checkpoint" in bijux_proteomics.__all__
    assert "build_proteomics_workflow_runtime_bundle" in bijux_proteomics.__all__
    assert "run_sequence_to_digest_workflow_end_to_end" in bijux_proteomics.__all__
    assert "run_dda_import_workflow_end_to_end" in bijux_proteomics.__all__
    assert "run_dia_import_workflow_end_to_end" in bijux_proteomics.__all__
    assert "run_quant_workflow_end_to_end" in bijux_proteomics.__all__
    assert "run_ptm_workflow_end_to_end" in bijux_proteomics.__all__
    assert "run_knowledge_review_workflow_end_to_end" in bijux_proteomics.__all__
    assert "run_lab_handoff_workflow_end_to_end" in bijux_proteomics.__all__
    assert "build_fake_external_engine_harness" in bijux_proteomics.__all__
    assert "run_local_external_tool" in bijux_proteomics.__all__
    assert "build_proteomics_workflow_cache_replay_report" in bijux_proteomics.__all__
    assert "build_study_metadata_model" in bijux_proteomics.__all__
    assert "parse_study_design_table" in bijux_proteomics.__all__
    assert "validate_experimental_design_records" in bijux_proteomics.__all__
    assert "build_fractionation_aggregation_report" in bijux_proteomics.__all__
    assert "build_instrument_run_summary_report" in bijux_proteomics.__all__
    assert "build_sample_lineage_report" in bijux_proteomics.__all__
    assert "validate_plate_layout" in bijux_proteomics.__all__
    assert "validate_lab_request_schema" in bijux_proteomics.__all__
    assert "build_lab_handoff_export_bundle" in bijux_proteomics.__all__
    assert "reconcile_planned_and_observed_lab_outcomes" in bijux_proteomics.__all__
    assert "query_evidence_graph" in bijux_proteomics.__all__
    assert "classify_contradictions" in bijux_proteomics.__all__
    assert "decompose_trust_score" in bijux_proteomics.__all__
    assert "build_ranking_sensitivity_report" in bijux_proteomics.__all__
    assert "replay_candidate_lifecycle" in bijux_proteomics.__all__
    assert "prioritize_evidence_gaps" in bijux_proteomics.__all__
    assert "build_review_packet_schema" in bijux_proteomics.__all__
    assert "run_reviewer_challenge_workflow" in bijux_proteomics.__all__
    assert "generate_review_narrative_from_structured_facts" in bijux_proteomics.__all__
    assert "diff_review_packets" in bijux_proteomics.__all__
    assert "transition_assay_progression" in bijux_proteomics.__all__
    assert "compare_assay_designs" in bijux_proteomics.__all__
    assert "build_default_lab_risk_library" in bijux_proteomics.__all__
    assert "evaluate_lab_risks" in bijux_proteomics.__all__
    assert "build_capacity_model_with_uncertainty" in bijux_proteomics.__all__
    assert "validate_targeted_transition_list" in bijux_proteomics.__all__
    assert "evaluate_targeted_workflow_boundary" in bijux_proteomics.__all__
    assert "build_lims_handoff_profile" in bijux_proteomics.__all__
    assert "apply_planned_observed_learning_loop" in bijux_proteomics.__all__
    assert "render_lab_review_packet" in bijux_proteomics.__all__
    assert "enforce_wet_lab_automation_boundary" in bijux_proteomics.__all__
    assert "build_complete_dda_mini_study_bundle" in bijux_proteomics.__all__
    assert "build_complete_dia_mini_study_bundle" in bijux_proteomics.__all__
    assert "build_complete_lfq_mini_study_bundle" in bijux_proteomics.__all__
    assert "build_complete_tmt_mini_study_bundle" in bijux_proteomics.__all__
    assert "build_complete_ptm_mini_study_bundle" in bijux_proteomics.__all__
    assert "build_known_mixture_mini_study_bundle" in bijux_proteomics.__all__
    assert "build_contradiction_mini_study_bundle" in bijux_proteomics.__all__
    assert "build_negative_science_corpus_report" in bijux_proteomics.__all__
    assert "build_external_engine_corpus_licensing_plan" in bijux_proteomics.__all__
    assert "build_example_index_by_scientific_question" in bijux_proteomics.__all__
    assert "build_dia_native_data_model" in bijux_proteomics.__all__
    assert "build_spectral_library_identity_ledger" in bijux_proteomics.__all__
    assert "validate_spectral_library_identity_entries" in bijux_proteomics.__all__
    assert "import_dia_nn_rows" in bijux_proteomics.__all__
    assert "compare_library_and_database_search_evidence" in bijux_proteomics.__all__
    assert "build_dia_quant_missingness_report" in bijux_proteomics.__all__
    assert "build_dia_ion_mobility_evidence_report" in bijux_proteomics.__all__
    assert "optimize_targeted_assay_candidates" in bijux_proteomics.__all__
    assert "export_transition_list_candidates" in bijux_proteomics.__all__
    assert "build_dia_capability_matrix" in bijux_proteomics.__all__
    assert "build_docker_image_descriptor" in bijux_proteomics.__all__
    assert "build_container_build_definition" in bijux_proteomics.__all__
    assert "run_container_smoke_execution" in bijux_proteomics.__all__
    assert "evaluate_apptainer_hpc_boundary" in bijux_proteomics.__all__
    assert "export_slurm_job_script" in bijux_proteomics.__all__
    assert "run_mocked_slurm_lifecycle" in bijux_proteomics.__all__
    assert "build_external_search_execution_contract" in bijux_proteomics.__all__
    assert "build_external_quant_execution_contract" in bijux_proteomics.__all__
    assert "build_provider_capability_registry" in bijux_proteomics.__all__
    assert "run_environment_qa_for_proteomics_workflows" in bijux_proteomics.__all__
    assert "build_runtime_workflow_blueprint" in bijux_proteomics.__all__
    assert "build_workflow_run_diff_report" in bijux_proteomics.__all__
    assert "plan_partial_workflow_rerun" in bijux_proteomics.__all__
    assert "verify_workflow_artifact_inventory" in bijux_proteomics.__all__
    assert "build_portable_workflow_run_bundle" in bijux_proteomics.__all__
    assert "explain_workflow_cache_decisions" in bijux_proteomics.__all__
    assert "query_workflow_run_history" in bijux_proteomics.__all__
    assert "evaluate_workflow_api_cli_parity" in bijux_proteomics.__all__
    assert "guard_large_artifact_uploads" in bijux_proteomics.__all__
    assert "build_stable_runtime_error_envelope" in bijux_proteomics.__all__
    assert "build_enrichment_background_provenance" in bijux_proteomics.__all__
    assert "build_pathway_network_caution_report" in bijux_proteomics.__all__
    assert "build_outlier_qc_integrated_report" in bijux_proteomics.__all__
    assert "prioritize_candidates_from_evidence_graph" in bijux_proteomics.__all__
    assert "build_multi_objective_ranking_report" in bijux_proteomics.__all__
    assert "build_ranking_policy_language_document" in bijux_proteomics.__all__
    assert "build_candidate_comparison_packet" in bijux_proteomics.__all__
    assert "run_review_board_workflow" in bijux_proteomics.__all__
    assert "build_evidence_freshness_report" in bijux_proteomics.__all__
    assert "build_contradiction_aware_lab_recommendation_report" in bijux_proteomics.__all__
    assert "build_lab_cost_model_report" in bijux_proteomics.__all__
    assert "build_plate_randomization_plan" in bijux_proteomics.__all__
    assert "evaluate_validation_stage_progression_policy" in bijux_proteomics.__all__
    assert "ingest_lab_outcomes_with_versioned_policy" in bijux_proteomics.__all__
    assert "build_lab_risk_dashboard_report" in bijux_proteomics.__all__
    assert "evaluate_protocol_attachment_boundary" in bijux_proteomics.__all__
    assert "build_lims_oriented_export_bundle" in bijux_proteomics.__all__
    assert "build_assay_expected_evidence_gain_report" in bijux_proteomics.__all__
    assert "build_lab_queue_prioritization_report" in bijux_proteomics.__all__
    assert "apply_lab_feedback_to_intelligence_prioritization" in bijux_proteomics.__all__
    assert "build_million_psm_ingestion_benchmark_report" in bijux_proteomics.__all__
    assert "build_dense_quant_matrix_benchmark_report" in bijux_proteomics.__all__
    assert "build_large_spectra_streaming_benchmark_report" in bijux_proteomics.__all__
    assert "build_evidence_graph_scale_benchmark_report" in bijux_proteomics.__all__
    assert "build_review_packet_scale_benchmark_report" in bijux_proteomics.__all__
    assert "build_workflow_startup_benchmark_report" in bijux_proteomics.__all__
    assert "classify_benchmark_corpus" in bijux_proteomics.__all__
    assert "build_benchmark_output_bundle" in bijux_proteomics.__all__
    assert "build_long_horizon_reproducibility_report" in bijux_proteomics.__all__
    assert "build_dependency_update_replay_report" in bijux_proteomics.__all__
    assert "build_external_reviewer_bundle" in bijux_proteomics.__all__
    assert "build_redacted_collaboration_bundle" in bijux_proteomics.__all__
    assert "generate_methods_section_from_workflow_evidence" in bijux_proteomics.__all__
    assert "build_citation_registry_document" in bijux_proteomics.__all__
    assert "run_standalone_bundle_verifier" in bijux_proteomics.__all__
    assert "build_archive_retention_package" in bijux_proteomics.__all__
    assert "run_collaborator_challenge_workflow" in bijux_proteomics.__all__
    assert "build_signed_reviewer_bundle" in bijux_proteomics.__all__
    assert "verify_signed_reviewer_bundle" in bijux_proteomics.__all__
    assert "redact_collaboration_surfaces" in bijux_proteomics.__all__
    assert "run_hostile_input_protection" in bijux_proteomics.__all__
    assert "build_package_level_example_workflow_catalog" in bijux_proteomics.__all__
    assert "build_unified_cli_workflow_story" in bijux_proteomics.__all__
    assert "route_review_packet_api" in bijux_proteomics.__all__
    assert "route_lab_handoff_api" in bijux_proteomics.__all__
    assert "route_evidence_graph_query_api" in bijux_proteomics.__all__
    assert "route_runtime_execution_api" in bijux_proteomics.__all__
    assert "route_quant_report_api" in bijux_proteomics.__all__
    assert "route_ptm_report_api" in bijux_proteomics.__all__
    assert "route_adapter_conformance_api" in bijux_proteomics.__all__
    assert "build_script_safe_command_output" in bijux_proteomics.__all__
    assert "build_external_strong_user_dda_trial_report" in bijux_proteomics.__all__
    assert "build_external_strong_user_dia_trial_report" in bijux_proteomics.__all__
    assert "build_external_strong_user_quant_trial_report" in bijux_proteomics.__all__
    assert "build_external_strong_user_ptm_trial_report" in bijux_proteomics.__all__
    assert "build_external_strong_user_lab_trial_report" in bijux_proteomics.__all__
    assert "build_mature_ecosystem_comparison_report" in bijux_proteomics.__all__
    assert "build_bijux_core_integration_contract_report" in bijux_proteomics.__all__
    assert "build_agentic_proteins_migration_report" in bijux_proteomics.__all__
    assert "build_final_flagship_proteomics_demo_report" in bijux_proteomics.__all__
    assert "build_product_simplification_by_real_usage_report" in bijux_proteomics.__all__
    assert "SequenceToDigestWorkflowRunReport" in bijux_proteomics.__all__
    assert "DdaImportWorkflowRunReport" in bijux_proteomics.__all__
    assert "DiaImportWorkflowRunReport" in bijux_proteomics.__all__
    assert "QuantRuntimeWorkflowRunReport" in bijux_proteomics.__all__
    assert "PtmRuntimeWorkflowRunReport" in bijux_proteomics.__all__
    assert "KnowledgeReviewWorkflowRunReport" in bijux_proteomics.__all__
    assert "LabHandoffWorkflowRunReport" in bijux_proteomics.__all__
    assert "FakeExternalEngineHarnessReport" in bijux_proteomics.__all__
    assert "LocalExternalToolRunReport" in bijux_proteomics.__all__
    assert "WorkflowCacheReplayReport" in bijux_proteomics.__all__
    assert "StudyMetadataModel" in bijux_proteomics.__all__
    assert "DesignTableParseReport" in bijux_proteomics.__all__
    assert "ExperimentalDesignValidationReport" in bijux_proteomics.__all__
    assert "FractionationAggregationReport" in bijux_proteomics.__all__
    assert "InstrumentRunSummaryReport" in bijux_proteomics.__all__
    assert "SampleLineageReport" in bijux_proteomics.__all__
    assert "PlateLayoutValidationReport" in bijux_proteomics.__all__
    assert "LabRequestSchema" in bijux_proteomics.__all__
    assert "LabRequestValidationReport" in bijux_proteomics.__all__
    assert "LabHandoffExportBundle" in bijux_proteomics.__all__
    assert "LabOutcomeReconciliationReport" in bijux_proteomics.__all__
    assert "EvidenceGraphQueryResult" in bijux_proteomics.__all__
    assert "ContradictionTaxonomyReport" in bijux_proteomics.__all__
    assert "TrustScoreDecomposition" in bijux_proteomics.__all__
    assert "RankingSensitivityReport" in bijux_proteomics.__all__
    assert "CandidateLifecycleReplayReport" in bijux_proteomics.__all__
    assert "EvidenceGapPrioritizationReport" in bijux_proteomics.__all__
    assert "ReviewPacketSchema" in bijux_proteomics.__all__
    assert "ReviewerChallengeWorkflowReport" in bijux_proteomics.__all__
    assert "ReviewNarrativeReport" in bijux_proteomics.__all__
    assert "ReviewPacketDiffReport" in bijux_proteomics.__all__
    assert "AssayProgressionModel" in bijux_proteomics.__all__
    assert "AssayDesignComparisonReport" in bijux_proteomics.__all__
    assert "LabRiskAssessmentReport" in bijux_proteomics.__all__
    assert "LabCapacityModelWithUncertainty" in bijux_proteomics.__all__
    assert "TargetedTransitionListValidationReport" in bijux_proteomics.__all__
    assert "TargetedWorkflowBoundaryReport" in bijux_proteomics.__all__
    assert "LimsHandoffProfile" in bijux_proteomics.__all__
    assert "PlannedObservedLearningLoopReport" in bijux_proteomics.__all__
    assert "LabReviewPacketRendered" in bijux_proteomics.__all__
    assert "WetLabAutomationBoundaryReport" in bijux_proteomics.__all__
    assert "DdaMiniStudyBundle" in bijux_proteomics.__all__
    assert "DiaMiniStudyBundle" in bijux_proteomics.__all__
    assert "LfqMiniStudyBundle" in bijux_proteomics.__all__
    assert "TmtMiniStudyBundle" in bijux_proteomics.__all__
    assert "PtmMiniStudyBundle" in bijux_proteomics.__all__
    assert "KnownMixtureMiniStudyBundle" in bijux_proteomics.__all__
    assert "ContradictionMiniStudyBundle" in bijux_proteomics.__all__
    assert "NegativeScienceCorpusReport" in bijux_proteomics.__all__
    assert "ExternalEngineCorpusLicensingPlan" in bijux_proteomics.__all__
    assert "ScientificQuestionExampleIndex" in bijux_proteomics.__all__
    assert "DiaNativeDataModel" in bijux_proteomics.__all__
    assert "SpectralLibraryIdentityLedger" in bijux_proteomics.__all__
    assert "SpectralLibraryValidationReport" in bijux_proteomics.__all__
    assert "DiaNnImportReport" in bijux_proteomics.__all__
    assert "LibrarySearchComparisonReport" in bijux_proteomics.__all__
    assert "DiaQuantMissingnessReport" in bijux_proteomics.__all__
    assert "DiaIonMobilityEvidenceReport" in bijux_proteomics.__all__
    assert "TargetedAssayOptimizationReport" in bijux_proteomics.__all__
    assert "TransitionListExportBundle" in bijux_proteomics.__all__
    assert "DiaCapabilityMatrixReport" in bijux_proteomics.__all__
    assert "DockerImageDescriptor" in bijux_proteomics.__all__
    assert "ContainerBuildDefinition" in bijux_proteomics.__all__
    assert "ContainerSmokeExecutionReport" in bijux_proteomics.__all__
    assert "HpcContainerBoundaryReport" in bijux_proteomics.__all__
    assert "SlurmJobScriptExport" in bijux_proteomics.__all__
    assert "SlurmLifecycleReport" in bijux_proteomics.__all__
    assert "ExternalSearchExecutionContract" in bijux_proteomics.__all__
    assert "ExternalQuantExecutionContract" in bijux_proteomics.__all__
    assert "ProviderCapabilityRegistry" in bijux_proteomics.__all__
    assert "EnvironmentQaReport" in bijux_proteomics.__all__
    assert "RuntimeWorkflowBlueprint" in bijux_proteomics.__all__
    assert "WorkflowRunDiffReport" in bijux_proteomics.__all__
    assert "PartialWorkflowRerunPlan" in bijux_proteomics.__all__
    assert "ArtifactInventoryVerificationReport" in bijux_proteomics.__all__
    assert "PortableRunBundle" in bijux_proteomics.__all__
    assert "CacheDecisionExplanationReport" in bijux_proteomics.__all__
    assert "WorkflowRunHistoryQueryReport" in bijux_proteomics.__all__
    assert "WorkflowApiCliParityReport" in bijux_proteomics.__all__
    assert "LargeArtifactUploadGuardReport" in bijux_proteomics.__all__
    assert "StableRuntimeErrorEnvelope" in bijux_proteomics.__all__
    assert "EnrichmentBackgroundProvenance" in bijux_proteomics.__all__
    assert "PathwayCautionReport" in bijux_proteomics.__all__
    assert "OutlierQcIntegratedReport" in bijux_proteomics.__all__
    assert "CandidatePriorityReport" in bijux_proteomics.__all__
    assert "MultiObjectiveRankingReport" in bijux_proteomics.__all__
    assert "RankingPolicyLanguageDocument" in bijux_proteomics.__all__
    assert "CandidateComparisonPacket" in bijux_proteomics.__all__
    assert "ReviewBoardWorkflowReport" in bijux_proteomics.__all__
    assert "EvidenceFreshnessReport" in bijux_proteomics.__all__
    assert "ContradictionAwareLabRecommendationReport" in bijux_proteomics.__all__
    assert "LabCostModelReport" in bijux_proteomics.__all__
    assert "PlateRandomizationPlan" in bijux_proteomics.__all__
    assert "ValidationStageProgressionDecision" in bijux_proteomics.__all__
    assert "LabOutcomeIngestionReport" in bijux_proteomics.__all__
    assert "LabRiskDashboardReport" in bijux_proteomics.__all__
    assert "ProtocolAttachmentBoundaryReport" in bijux_proteomics.__all__
    assert "LimsOrientedExportBundle" in bijux_proteomics.__all__
    assert "AssayExpectedEvidenceGainReport" in bijux_proteomics.__all__
    assert "LabQueuePrioritizationReport" in bijux_proteomics.__all__
    assert "IntelligenceFeedbackReport" in bijux_proteomics.__all__
    assert "MillionPsmIngestionBenchmarkReport" in bijux_proteomics.__all__
    assert "DenseQuantMatrixBenchmarkReport" in bijux_proteomics.__all__
    assert "LargeSpectraStreamingBenchmarkReport" in bijux_proteomics.__all__
    assert "EvidenceGraphScaleBenchmarkReport" in bijux_proteomics.__all__
    assert "ReviewPacketScaleBenchmarkReport" in bijux_proteomics.__all__
    assert "WorkflowStartupBenchmarkReport" in bijux_proteomics.__all__
    assert "BenchmarkCorpusDescriptor" in bijux_proteomics.__all__
    assert "BenchmarkOutputBundle" in bijux_proteomics.__all__
    assert "LongHorizonReproducibilityReport" in bijux_proteomics.__all__
    assert "DependencyUpdateReplayReport" in bijux_proteomics.__all__
    assert "ExternalReviewerBundleInput" in bijux_proteomics.__all__
    assert "ExternalReviewerBundle" in bijux_proteomics.__all__
    assert "RedactedCollaborationBundleInput" in bijux_proteomics.__all__
    assert "RedactedCollaborationBundle" in bijux_proteomics.__all__
    assert "MethodsSectionInput" in bijux_proteomics.__all__
    assert "MethodsSectionDocument" in bijux_proteomics.__all__
    assert "CitationRegistryEntry" in bijux_proteomics.__all__
    assert "CitationRegistryDocument" in bijux_proteomics.__all__
    assert "StandaloneVerifierInput" in bijux_proteomics.__all__
    assert "StandaloneVerifierIssue" in bijux_proteomics.__all__
    assert "StandaloneVerifierReport" in bijux_proteomics.__all__
    assert "ArchiveRetentionPackageInput" in bijux_proteomics.__all__
    assert "ArchiveRetentionPackage" in bijux_proteomics.__all__
    assert "CollaboratorChallengeInput" in bijux_proteomics.__all__
    assert "CollaboratorChallengeEntry" in bijux_proteomics.__all__
    assert "CollaboratorChallengeWorkflowReport" in bijux_proteomics.__all__
    assert "SignedReviewerBundleInput" in bijux_proteomics.__all__
    assert "SignedReviewerBundle" in bijux_proteomics.__all__
    assert "CollaborationSurfaceRedactionInput" in bijux_proteomics.__all__
    assert "CollaborationSurfaceRedactionReport" in bijux_proteomics.__all__
    assert "HostileInputProtectionInput" in bijux_proteomics.__all__
    assert "HostileInputProtectionIssue" in bijux_proteomics.__all__
    assert "HostileInputProtectionReport" in bijux_proteomics.__all__
    assert "ExampleWorkflowPackageEntry" in bijux_proteomics.__all__
    assert "PackageLevelExampleWorkflowCatalog" in bijux_proteomics.__all__
    assert "CliWorkflowCommandEntry" in bijux_proteomics.__all__
    assert "UnifiedCliWorkflowStoryReport" in bijux_proteomics.__all__
    assert "ReviewPacketRouteRequest" in bijux_proteomics.__all__
    assert "ReviewPacketRouteIssue" in bijux_proteomics.__all__
    assert "ReviewPacketRouteResponse" in bijux_proteomics.__all__
    assert "LabHandoffRouteRequest" in bijux_proteomics.__all__
    assert "LabHandoffRouteResponse" in bijux_proteomics.__all__
    assert "EvidenceGraphQueryRouteRequest" in bijux_proteomics.__all__
    assert "EvidenceGraphQueryRouteResponse" in bijux_proteomics.__all__
    assert "RuntimeExecutionRouteRequest" in bijux_proteomics.__all__
    assert "RuntimeExecutionRouteResponse" in bijux_proteomics.__all__
    assert "QuantReportRouteRequest" in bijux_proteomics.__all__
    assert "QuantReportRouteResponse" in bijux_proteomics.__all__
    assert "PtmReportRouteRequest" in bijux_proteomics.__all__
    assert "PtmReportRouteResponse" in bijux_proteomics.__all__
    assert "AdapterConformanceRouteRequest" in bijux_proteomics.__all__
    assert "AdapterConformanceRouteResponse" in bijux_proteomics.__all__
    assert "ScriptSafeOutputField" in bijux_proteomics.__all__
    assert "ScriptSafeCommandOutput" in bijux_proteomics.__all__
    assert "TrialIssueEntry" in bijux_proteomics.__all__
    assert "ExternalDdaTrialInput" in bijux_proteomics.__all__
    assert "ExternalDdaTrialReport" in bijux_proteomics.__all__
    assert "ExternalDiaTrialInput" in bijux_proteomics.__all__
    assert "ExternalDiaTrialReport" in bijux_proteomics.__all__
    assert "ExternalQuantTrialInput" in bijux_proteomics.__all__
    assert "ExternalQuantTrialReport" in bijux_proteomics.__all__
    assert "ExternalPtmTrialInput" in bijux_proteomics.__all__
    assert "ExternalPtmTrialReport" in bijux_proteomics.__all__
    assert "ExternalLabTrialInput" in bijux_proteomics.__all__
    assert "ExternalLabTrialReport" in bijux_proteomics.__all__
    assert "EcosystemComparisonEntry" in bijux_proteomics.__all__
    assert "MatureEcosystemComparisonReport" in bijux_proteomics.__all__
    assert "BijuxCoreIntegrationContractInput" in bijux_proteomics.__all__
    assert "BijuxCoreIntegrationContractReport" in bijux_proteomics.__all__
    assert "AgenticProteinsMigrationItem" in bijux_proteomics.__all__
    assert "AgenticProteinsMigrationReport" in bijux_proteomics.__all__
    assert "FlagshipDemoInput" in bijux_proteomics.__all__
    assert "FlagshipDemoReport" in bijux_proteomics.__all__
    assert "UsageSimplificationCandidate" in bijux_proteomics.__all__
    assert "ProductSimplificationByUsageReport" in bijux_proteomics.__all__
    assert "LcmsRunQcReport" in bijux_proteomics.__all__
    assert "InstrumentBatchQcReport" in bijux_proteomics.__all__
    assert "QcInstrumentSummary" in bijux_proteomics.__all__
    assert "QcIdentificationSummary" in bijux_proteomics.__all__
    assert "QcQuantSummary" in bijux_proteomics.__all__
    assert "QcPublicationDecision" in bijux_proteomics.__all__
    assert "QcAssessmentProvenance" in bijux_proteomics.__all__
    assert "QcRunBundleSummary" in bijux_proteomics.__all__
    assert "QcRunAnomalyCategory" in bijux_proteomics.__all__
    assert "QcRunAnomalyEntry" in bijux_proteomics.__all__
    assert "QcThresholdPolicyProfile" in bijux_proteomics.__all__
    assert "QcThresholdPolicy" in bijux_proteomics.__all__
    assert "QcUnknownStateReason" in bijux_proteomics.__all__
    assert "StudyQcSummaryReport" in bijux_proteomics.__all__
    assert "QcEvidenceManifest" in bijux_proteomics.__all__
    assert "ProteomicsOperatorErrorCode" in bijux_proteomics.__all__
    assert "ProteomicsWorkflowManifest" in bijux_proteomics.__all__
    assert "ReproducibleWorkflowBlueprint" in bijux_proteomics.__all__
    assert "RerunArtifactDriftEntry" in bijux_proteomics.__all__
    assert "RerunComparisonScope" in bijux_proteomics.__all__
    assert "WorkflowManifestExplanationReport" in bijux_proteomics.__all__
    assert "WorkflowStepProvenanceReport" in bijux_proteomics.__all__
    assert "WorkflowStepReplayDisposition" in bijux_proteomics.__all__
    assert "WorkflowReplayProofReport" in bijux_proteomics.__all__
    assert "WorkflowScientificSurface" in bijux_proteomics.__all__
    assert "ProteomicsDagPlan" in bijux_proteomics.__all__
    assert "CoreResultRuntimeBinding" in bijux_proteomics.__all__
    assert "DeterministicExecutionContract" in bijux_proteomics.__all__
    assert "ExternalToolCapabilityReport" in bijux_proteomics.__all__
    assert "ExternalSearchToolContract" in bijux_proteomics.__all__
    assert "HpcJobDescriptor" in bijux_proteomics.__all__
    assert "WorkflowExecutionReadinessReport" in bijux_proteomics.__all__
    assert "WorkflowDiffReport" in bijux_proteomics.__all__
    assert "WorkflowCacheManifest" in bijux_proteomics.__all__
    assert "ProteomicsWorkflowTemplate" in bijux_proteomics.__all__
    assert "WorkflowTemplateKind" in bijux_proteomics.__all__
    assert "WorkflowCacheMissExplanationEntry" in bijux_proteomics.__all__
    assert "WorkflowCacheMissExplanationReport" in bijux_proteomics.__all__
    assert "WorkflowCacheMissReason" in bijux_proteomics.__all__
    assert "WorkflowArchiveMedium" in bijux_proteomics.__all__
    assert "WorkflowPathKind" in bijux_proteomics.__all__
    assert "WorkflowResumeKind" in bijux_proteomics.__all__
    assert "WorkflowRuntimeArchiveBundle" in bijux_proteomics.__all__
    assert "WorkflowRuntimeArchiveImportReport" in bijux_proteomics.__all__
    assert "WorkflowRerunComparisonArtifact" in bijux_proteomics.__all__
    assert "WorkflowRuntimeExportBundle" in bijux_proteomics.__all__
    assert "WorkflowRuntimeValidationIssue" in bijux_proteomics.__all__
    assert "WorkflowRuntimeValidationReport" in bijux_proteomics.__all__
    assert "WorkflowRunDirectoryLayout" in bijux_proteomics.__all__
    assert "WorkflowRunDirectoryLayoutEntry" in bijux_proteomics.__all__
    assert "WorkflowRuntimeStateManifest" in bijux_proteomics.__all__
    assert "ArchivedArtifactDescriptor" in bijux_proteomics.__all__
    assert "ArtifactInventoryEntry" in bijux_proteomics.__all__
    assert "ProteomicsArtifactInventory" in bijux_proteomics.__all__
    assert "ProteomicsArtifactRegistry" in bijux_proteomics.__all__
    assert "LargeFileStreamingPolicy" in bijux_proteomics.__all__
    assert "ParallelExecutionPlan" in bijux_proteomics.__all__
    assert "WorkflowCheckpoint" in bijux_proteomics.__all__


def test_intelligence_public_api_contains_expected_exports() -> None:
    assert "RankingPolicy" in bijux_proteomics_intelligence.__all__
    assert "ScenarioEvaluation" in bijux_proteomics_intelligence.__all__
    assert "CandidateRejection" in bijux_proteomics_intelligence.__all__


def test_knowledge_public_api_contains_expected_exports() -> None:
    assert "EvidenceClaim" in bijux_proteomics_knowledge.__all__
    assert "ResolutionAction" in bijux_proteomics_knowledge.__all__
    assert "EvidenceGraph" in bijux_proteomics_knowledge.__all__


def test_lab_public_api_contains_expected_exports() -> None:
    assert "ScheduledPlan" in bijux_proteomics_lab.__all__
    assert "AssayOutcome" in bijux_proteomics_lab.__all__
    assert "AssayDependency" in bijux_proteomics_lab.__all__
