# SPDX-License-Identifier: Apache-2.0
# Copyright © 2025 Bijan Mousavi

from __future__ import annotations

import bijux_proteomics
import bijux_proteomics_intelligence
import bijux_proteomics_knowledge
import bijux_proteomics_lab


def test_core_public_api_contains_expected_exports() -> None:
    assert "ProgramSpec" in bijux_proteomics.__all__
    assert "ExecutionBackend" in bijux_proteomics.__all__
    assert "ProteinSequence" in bijux_proteomics.__all__
    assert "FastaParseReport" in bijux_proteomics.__all__
    assert "SequenceResiduePolicy" in bijux_proteomics.__all__
    assert "build_sequence_residue_policy" in bijux_proteomics.__all__
    assert "generate_decoy_records" in bijux_proteomics.__all__
    assert "DecoyGenerationManifest" in bijux_proteomics.__all__
    assert "build_decoy_generation_manifest" in bijux_proteomics.__all__
    assert "compute_decoy_generation_reproducibility_hash" in bijux_proteomics.__all__
    assert "validate_target_decoy_database" in bijux_proteomics.__all__
    assert "digest_sequence" in bijux_proteomics.__all__
    assert "DigestDuplicateAccounting" in bijux_proteomics.__all__
    assert "build_digest_duplicate_accounting" in bijux_proteomics.__all__
    assert "DigestPolicy" in bijux_proteomics.__all__
    assert "build_digest_policy" in bijux_proteomics.__all__
    assert "compute_digest_policy_hash" in bijux_proteomics.__all__
    assert "protease_registry" in bijux_proteomics.__all__
    assert "build_peptide_protein_index" in bijux_proteomics.__all__
    assert "PeptideOriginCoordinate" in bijux_proteomics.__all__
    assert "calculate_monoisotopic_peptide_mass" in bijux_proteomics.__all__
    assert "calculate_fragment_ions" in bijux_proteomics.__all__
    assert "validate_modified_peptide_fragment_ions" in bijux_proteomics.__all__
    assert "enumerate_variable_modifications" in bijux_proteomics.__all__
    assert "modification_registry" in bijux_proteomics.__all__
    assert "canonicalize_modified_peptide" in bijux_proteomics.__all__
    assert "build_peptide_charge_state" in bijux_proteomics.__all__
    assert "approximate_peptide_isotope_envelope" in bijux_proteomics.__all__
    assert "ModificationLocalizationState" in bijux_proteomics.__all__
    assert "ModificationProvenance" in bijux_proteomics.__all__
    assert "validate_modification_registry" in bijux_proteomics.__all__
    assert "IsotopicLabelingPolicy" in bijux_proteomics.__all__
    assert "PsmRecord" in bijux_proteomics.__all__
    assert "parse_psm_tsv" in bijux_proteomics.__all__
    assert "rollup_protein_evidence" in bijux_proteomics.__all__
    assert "filter_psms_by_fdr" in bijux_proteomics.__all__
    assert "build_fdr_audit_trail" in bijux_proteomics.__all__
    assert "build_fdr_edge_case_report" in bijux_proteomics.__all__
    assert "compute_fdr_reproducibility_hash" in bijux_proteomics.__all__
    assert "validate_target_decoy_accession_collisions" in bijux_proteomics.__all__
    assert "verify_fdr_q_value_monotonicity" in bijux_proteomics.__all__
    assert "build_accepted_psm_provenance_report" in bijux_proteomics.__all__
    assert "build_confidence_threshold_sensitivity_report" in bijux_proteomics.__all__
    assert "normalize_psm_score_orientation" in bijux_proteomics.__all__
    assert "detect_score_orientation_advisory" in bijux_proteomics.__all__
    assert "calculate_level_specific_fdr" in bijux_proteomics.__all__
    assert "assign_level_specific_confidence_labels" in bijux_proteomics.__all__
    assert "calculate_grouped_fdr" in bijux_proteomics.__all__
    assert "calculate_picked_protein_fdr" in bijux_proteomics.__all__
    assert "build_protein_groups" in bijux_proteomics.__all__
    assert "build_shared_peptide_ambiguity_report" in bijux_proteomics.__all__
    assert "infer_proteins_by_parsimony" in bijux_proteomics.__all__
    assert "assign_razor_peptides" in bijux_proteomics.__all__
    assert "build_protein_coverage_map" in bijux_proteomics.__all__
    assert "build_peptide_uniqueness_across_database" in bijux_proteomics.__all__
    assert "assign_confidence_labels" in bijux_proteomics.__all__
    assert "build_search_result_provenance_manifest" in bijux_proteomics.__all__
    assert "export_psm_tsv" in bijux_proteomics.__all__
    assert "SpectrumModel" in bijux_proteomics.__all__
    assert "parse_mgf" in bijux_proteomics.__all__
    assert "build_spectrum_lookup_index" in bijux_proteomics.__all__
    assert "build_annotated_spectrum_bundle" in bijux_proteomics.__all__
    assert "lookup_spectra" in bijux_proteomics.__all__
    assert "annotate_spectrum_fragments" in bijux_proteomics.__all__
    assert "SpectrumAnnotationAmbiguityWarning" in bijux_proteomics.__all__
    assert "calculate_spectral_similarity" in bijux_proteomics.__all__
    assert "SpectrumSimilarityMode" in bijux_proteomics.__all__
    assert "detect_precursor_isotope_offset_advisory" in bijux_proteomics.__all__
    assert "build_spectrum_provenance_manifest" in bijux_proteomics.__all__
    assert "parse_mzml" in bijux_proteomics.__all__
    assert "detect_proteomics_format" in bijux_proteomics.__all__
    assert "diagnose_proteomics_format" in bijux_proteomics.__all__
    assert "build_normalized_run_bundle" in bijux_proteomics.__all__
    assert "normalize_search_results_with_adapter" in bijux_proteomics.__all__
    assert "build_search_adapter_capability_matrix" in bijux_proteomics.__all__
    assert "parse_search_parameter_file" in bijux_proteomics.__all__
    assert "validate_search_parameters" in bijux_proteomics.__all__
    assert "compare_search_result_reports" in bijux_proteomics.__all__
    assert "build_search_adapter_conformance_report" in bijux_proteomics.__all__
    assert "SearchAdapterKind" in bijux_proteomics.__all__
    assert "Ms1FeatureRecord" in bijux_proteomics.__all__
    assert "parse_ms1_feature_table" in bijux_proteomics.__all__
    assert "build_label_free_intensity_table" in bijux_proteomics.__all__
    assert "build_normalization_comparison_report" in bijux_proteomics.__all__
    assert "build_protein_quant_rollup_evidence" in bijux_proteomics.__all__
    assert "build_quant_matrix_export" in bijux_proteomics.__all__
    assert "build_spectral_count_table" in bijux_proteomics.__all__
    assert "normalize_label_free_table" in bijux_proteomics.__all__
    assert "build_batch_effect_advisory" in bijux_proteomics.__all__
    assert "build_replicate_correlation_report" in bijux_proteomics.__all__
    assert "build_differential_abundance_report" in bijux_proteomics.__all__
    assert "DifferentialReplicatePolicy" in bijux_proteomics.__all__
    assert "DifferentialAbundanceAssumptionReport" in bijux_proteomics.__all__
    assert "MissingValueCorrectionPolicy" in bijux_proteomics.__all__
    assert "MissingValueSummaryPolicy" in bijux_proteomics.__all__
    assert "apply_benjamini_hochberg" in bijux_proteomics.__all__
    assert "PtmEvidenceRecord" in bijux_proteomics.__all__
    assert "parse_ptm_localization_tsv" in bijux_proteomics.__all__
    assert "map_ptm_evidence_to_protein_sites" in bijux_proteomics.__all__
    assert "validate_ptm_site_coordinates" in bijux_proteomics.__all__
    assert "build_ptm_site_table" in bijux_proteomics.__all__
    assert "build_ptm_site_fdr" in bijux_proteomics.__all__
    assert "estimate_ptm_site_occupancy" in bijux_proteomics.__all__
    assert "build_ptm_motif_background_report" in bijux_proteomics.__all__
    assert "PtmOccupancyUncertainty" in bijux_proteomics.__all__
    assert "build_lcms_run_qc_report" in bijux_proteomics.__all__
    assert "build_instrument_batch_qc_report" in bijux_proteomics.__all__
    assert "build_study_qc_summary" in bijux_proteomics.__all__
    assert "default_qc_threshold_policy" in bijux_proteomics.__all__
    assert "build_qc_threshold_profile" in bijux_proteomics.__all__
    assert "build_run_qc_assessment" in bijux_proteomics.__all__
    assert "build_qc_evidence_manifest" in bijux_proteomics.__all__
    assert "build_qc_publication_decision" in bijux_proteomics.__all__
    assert "build_qc_run_bundle_summary" in bijux_proteomics.__all__
    assert "build_performance_snapshot" in bijux_proteomics.__all__
    assert "build_proteomics_workflow_manifest" in bijux_proteomics.__all__
    assert "build_reproducible_workflow_blueprint" in bijux_proteomics.__all__
    assert "build_workflow_manifest_explanation_report" in bijux_proteomics.__all__
    assert "build_workflow_step_provenance_report" in bijux_proteomics.__all__
    assert "build_proteomics_dag_plan" in bijux_proteomics.__all__
    assert "build_containerized_step_specs" in bijux_proteomics.__all__
    assert "build_workflow_cache_miss_explanation_report" in bijux_proteomics.__all__
    assert "build_deterministic_execution_contract" in bijux_proteomics.__all__
    assert "build_external_tool_capability_report" in bijux_proteomics.__all__
    assert "build_external_search_tool_contract" in bijux_proteomics.__all__
    assert "build_workflow_diff_report" in bijux_proteomics.__all__
    assert "build_workflow_execution_readiness_report" in bijux_proteomics.__all__
    assert "build_hpc_job_descriptor" in bijux_proteomics.__all__
    assert "build_workflow_runtime_cache" in bijux_proteomics.__all__
    assert "build_proteomics_artifact_inventory" in bijux_proteomics.__all__
    assert "build_proteomics_artifact_registry" in bijux_proteomics.__all__
    assert "build_large_file_streaming_policy" in bijux_proteomics.__all__
    assert "build_parallel_execution_plan" in bijux_proteomics.__all__
    assert "build_workflow_run_directory_layout" in bijux_proteomics.__all__
    assert "build_workflow_runtime_export_bundle" in bijux_proteomics.__all__
    assert "build_workflow_runtime_validation_report" in bijux_proteomics.__all__
    assert "build_workflow_runtime_state_manifest" in bijux_proteomics.__all__
    assert "build_workflow_checkpoint" in bijux_proteomics.__all__
    assert "build_proteomics_workflow_runtime_bundle" in bijux_proteomics.__all__
    assert "LcmsRunQcReport" in bijux_proteomics.__all__
    assert "InstrumentBatchQcReport" in bijux_proteomics.__all__
    assert "QcInstrumentSummary" in bijux_proteomics.__all__
    assert "QcIdentificationSummary" in bijux_proteomics.__all__
    assert "QcQuantSummary" in bijux_proteomics.__all__
    assert "QcPublicationDecision" in bijux_proteomics.__all__
    assert "QcAssessmentProvenance" in bijux_proteomics.__all__
    assert "QcRunBundleSummary" in bijux_proteomics.__all__
    assert "QcRunAnomalyCategory" in bijux_proteomics.__all__
    assert "QcRunAnomalyEntry" in bijux_proteomics.__all__
    assert "QcThresholdPolicyProfile" in bijux_proteomics.__all__
    assert "QcThresholdPolicy" in bijux_proteomics.__all__
    assert "QcUnknownStateReason" in bijux_proteomics.__all__
    assert "StudyQcSummaryReport" in bijux_proteomics.__all__
    assert "QcEvidenceManifest" in bijux_proteomics.__all__
    assert "ProteomicsOperatorErrorCode" in bijux_proteomics.__all__
    assert "ProteomicsWorkflowManifest" in bijux_proteomics.__all__
    assert "ReproducibleWorkflowBlueprint" in bijux_proteomics.__all__
    assert "WorkflowManifestExplanationReport" in bijux_proteomics.__all__
    assert "WorkflowStepProvenanceReport" in bijux_proteomics.__all__
    assert "WorkflowStepReplayDisposition" in bijux_proteomics.__all__
    assert "WorkflowScientificSurface" in bijux_proteomics.__all__
    assert "ProteomicsDagPlan" in bijux_proteomics.__all__
    assert "CoreResultRuntimeBinding" in bijux_proteomics.__all__
    assert "DeterministicExecutionContract" in bijux_proteomics.__all__
    assert "ExternalToolCapabilityReport" in bijux_proteomics.__all__
    assert "ExternalSearchToolContract" in bijux_proteomics.__all__
    assert "HpcJobDescriptor" in bijux_proteomics.__all__
    assert "WorkflowExecutionReadinessReport" in bijux_proteomics.__all__
    assert "WorkflowDiffReport" in bijux_proteomics.__all__
    assert "WorkflowCacheManifest" in bijux_proteomics.__all__
    assert "WorkflowCacheMissExplanationEntry" in bijux_proteomics.__all__
    assert "WorkflowCacheMissExplanationReport" in bijux_proteomics.__all__
    assert "WorkflowCacheMissReason" in bijux_proteomics.__all__
    assert "WorkflowPathKind" in bijux_proteomics.__all__
    assert "WorkflowResumeKind" in bijux_proteomics.__all__
    assert "WorkflowRuntimeExportBundle" in bijux_proteomics.__all__
    assert "WorkflowRuntimeValidationIssue" in bijux_proteomics.__all__
    assert "WorkflowRuntimeValidationReport" in bijux_proteomics.__all__
    assert "WorkflowRunDirectoryLayout" in bijux_proteomics.__all__
    assert "WorkflowRunDirectoryLayoutEntry" in bijux_proteomics.__all__
    assert "WorkflowRuntimeStateManifest" in bijux_proteomics.__all__
    assert "ArtifactInventoryEntry" in bijux_proteomics.__all__
    assert "ProteomicsArtifactInventory" in bijux_proteomics.__all__
    assert "ProteomicsArtifactRegistry" in bijux_proteomics.__all__
    assert "LargeFileStreamingPolicy" in bijux_proteomics.__all__
    assert "ParallelExecutionPlan" in bijux_proteomics.__all__
    assert "WorkflowCheckpoint" in bijux_proteomics.__all__


def test_intelligence_public_api_contains_expected_exports() -> None:
    assert "RankingPolicy" in bijux_proteomics_intelligence.__all__
    assert "ScenarioEvaluation" in bijux_proteomics_intelligence.__all__
    assert "CandidateRejection" in bijux_proteomics_intelligence.__all__


def test_knowledge_public_api_contains_expected_exports() -> None:
    assert "EvidenceClaim" in bijux_proteomics_knowledge.__all__
    assert "ResolutionAction" in bijux_proteomics_knowledge.__all__
    assert "EvidenceGraph" in bijux_proteomics_knowledge.__all__


def test_lab_public_api_contains_expected_exports() -> None:
    assert "ScheduledPlan" in bijux_proteomics_lab.__all__
    assert "AssayOutcome" in bijux_proteomics_lab.__all__
    assert "AssayDependency" in bijux_proteomics_lab.__all__
