# SPDX-License-Identifier: Apache-2.0
# Copyright © 2025 Bijan Mousavi
# ruff: noqa: F401,F403,F405

"""Sequence, FASTA, and click-choice helpers shared by CLI command modules."""

from __future__ import annotations

from typing import cast

from ..imports import *  # noqa: F401,F403
from ..output_protocol import _emit_json, _write_text_output
from .cli_choices import (
    _conversion_target_choice,
    _decoy_mode_choice,
    _digestion_mode_choice,
    _duplicate_accession_policy_choice,
    _export_format_choice,
    _fragment_series_choice,
    _heatmap_missing_value_choice,
    _imputation_choice,
    _label_based_differential_normalization_choice,
    _mode_choice,
    _modified_peptide_dialect_choice,
    _normalization_choice,
    _peptide_matrix_builder_input_kind_choice,
    _peptide_matrix_grouping_choice,
    _peptide_matrix_input_kind_choice,
    _protein_matrix_target_choice,
    _quant_entity_level_choice,
    _quant_measure_choice,
    _quant_rollup_choice,
    _score_orientation_choice,
    _search_adapter_choice,
    _silac_label_choice,
    _tmt_normalization_method_choice,
    _tmt_ratio_normalization_choice,
    _tmt_source_kind_choice,
    _validate_kind_choice,
    _workflow_scheduler_choice,
)


def _resolve_cli_protease_rule(
    *,
    protease: str,
    custom_protease: str | None,
    custom_protease_name: str,
) -> tuple[ProteaseRule, str | None]:
    specification = custom_protease.strip() if custom_protease is not None else ""
    if not specification:
        rule = resolve_protease_rule(protease)
        return rule, None
    if protease != "trypsin":
        raise ValueError(
            "custom protease rules cannot be combined with a second built-in protease name"
        )
    rule = resolve_protease_rule(
        custom_specification=specification,
        custom_name=custom_protease_name,
    )
    return rule, specification


def _resolve_cli_theoretical_digest_modifications(
    *,
    static_modifications: tuple[str, ...],
    variable_modifications: tuple[str, ...],
    registry_path: Path | None,
    allow_isotopic_labels: bool,
    allowed_label_families: tuple[str, ...],
) -> tuple[
    ModificationRegistryDocument | None,
    tuple[StaticModification, ...],
    tuple[VariableModification, ...],
    IsotopicLabelingPolicy | None,
]:
    registry = (
        load_modification_registry(registry_path) if registry_path is not None else None
    )
    resolved_static: list[StaticModification] = []
    for token in static_modifications:
        definition = get_modification(token, registry=registry)
        if not isinstance(definition, StaticModification):
            raise ValueError(
                f"static modification {token!r} is not a static definition"
            )
        resolved_static.append(definition)
    resolved_variable: list[VariableModification] = []
    for token in variable_modifications:
        definition = get_modification(token, registry=registry)
        if not isinstance(definition, VariableModification):
            raise ValueError(
                f"variable modification {token!r} is not a variable definition"
            )
        resolved_variable.append(definition)
    labeling_policy = (
        IsotopicLabelingPolicy(
            allow_isotopic_labels=allow_isotopic_labels,
            allowed_label_families=allowed_label_families,
        )
        if allow_isotopic_labels or allowed_label_families
        else None
    )
    return registry, tuple(resolved_static), tuple(resolved_variable), labeling_policy


def _emit_fasta_profile(
    profile: FastaDatabaseProfile,
    *,
    out_path: Path | None,
    summary_tsv_out: Path | None,
    length_tsv_out: Path | None,
    organism_tsv_out: Path | None,
    invalid_sequence_tsv_out: Path | None,
) -> None:
    if summary_tsv_out is not None:
        _write_text_output(summary_tsv_out, render_fasta_profile_summary_tsv(profile))
    if length_tsv_out is not None:
        _write_text_output(
            length_tsv_out, render_fasta_profile_length_distribution_tsv(profile)
        )
    if organism_tsv_out is not None:
        _write_text_output(
            organism_tsv_out, render_fasta_profile_organism_distribution_tsv(profile)
        )
    if invalid_sequence_tsv_out is not None:
        _write_text_output(
            invalid_sequence_tsv_out,
            render_fasta_profile_invalid_sequence_tsv(profile),
        )
    _emit_json(profile, out_path=out_path)


def _file_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _load_fasta_report(
    input_path: Path,
    *,
    mode: FastaParseMode,
    duplicate_accession_policy: DuplicateAccessionPolicy = DuplicateAccessionPolicy.REJECT,
    allow_rejected: bool,
) -> FastaParseReport:
    report = parse_fasta_document(
        input_path.read_text(),
        mode=mode,
        duplicate_accession_policy=duplicate_accession_policy,
    )
    if report.rejected_records and not allow_rejected:
        rejected = ", ".join(
            rejected.source_identifier for rejected in report.rejected_records
        )
        raise click.ClickException(
            f"FASTA input contains rejected records under {mode.value} mode: {rejected}"
        )
    return report


def _load_precursor_mass_error_queries(
    input_tsv: Path,
    *,
    peptide_column: str,
    observed_mz_column: str,
    charge_column: str,
    spectrum_id_column: str | None,
) -> tuple[PrecursorMassErrorQuery, ...]:
    queries: list[PrecursorMassErrorQuery] = []
    with input_tsv.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        if reader.fieldnames is None:
            raise click.ClickException(
                "precursor mass-error TSV must include a header row"
            )
        for required_column in (peptide_column, observed_mz_column, charge_column):
            if required_column not in reader.fieldnames:
                raise click.ClickException(
                    f"missing required precursor mass-error column {required_column!r}"
                )

        for row_number, row in enumerate(reader, start=2):
            try:
                peptide = str(row.get(peptide_column, "")).strip()
                observed_mz = float(str(row.get(observed_mz_column, "")).strip())
                charge = int(str(row.get(charge_column, "")).strip())
                if not peptide:
                    raise ValueError("peptide must not be blank")
                if observed_mz <= 0:
                    raise ValueError("observed_mz must be greater than zero")
                if charge < 1:
                    raise ValueError("charge must be at least 1")
                spectrum_id = (
                    str(row.get(spectrum_id_column, "")).strip()
                    if spectrum_id_column is not None
                    else ""
                )
                queries.append(
                    PrecursorMassErrorQuery(
                        peptide=peptide,
                        observed_mz=observed_mz,
                        charge=charge,
                        spectrum_id=spectrum_id or None,
                    )
                )
            except (TypeError, ValueError) as exc:
                raise click.ClickException(
                    f"invalid precursor mass-error row at line {row_number}: {exc}"
                ) from exc
    return tuple(queries)


def _parse_tmt_channel_column_specs(
    specs: tuple[str, ...],
) -> tuple[TmtReporterChannelColumn, ...]:
    resolved: list[TmtReporterChannelColumn] = []
    for spec in specs:
        if "=" not in spec:
            raise click.ClickException("channel-column must use CHANNEL=COLUMN syntax")
        channel, column_name = spec.split("=", 1)
        channel = channel.strip()
        column_name = column_name.strip()
        if not channel or not column_name:
            raise click.ClickException("channel-column must use CHANNEL=COLUMN syntax")
        resolved.append(
            TmtReporterChannelColumn(
                multiplex_channel=channel,
                column_name=column_name,
            )
        )
    return tuple(resolved)


def _parse_silac_label_spec(spec: str) -> tuple[SilacLabel, ...]:
    labels = tuple(
        SilacLabel(token.strip().lower()) for token in spec.split(",") if token.strip()
    )
    if len(labels) < 2:
        raise click.ClickException("labels must name at least two SILAC label states")
    return labels


def _select_design_entry(
    design_path: Path | None,
    *,
    sample_id: str | None,
    spectra_path: Path,
) -> ExperimentalDesignEntry | None:
    if design_path is None:
        return None
    report = parse_experimental_design_table(design_path)
    if report.rejected_rows:
        raise ProteomicsOperatorError(
            ProteomicsOperatorErrorCode.INPUT_DESIGN_INVALID,
            "design table contains rejected rows",
        )
    if sample_id is not None:
        for entry in report.accepted_entries:
            if entry.sample_id == sample_id:
                return entry
        raise ProteomicsOperatorError(
            ProteomicsOperatorErrorCode.QC_SAMPLE_NOT_FOUND,
            f"sample {sample_id!r} is not present in the design table",
        )
    matching_entries = [
        entry
        for entry in report.accepted_entries
        if Path(entry.spectra_file).name == spectra_path.name
    ]
    if len(matching_entries) == 1:
        return matching_entries[0]
    if len(report.accepted_entries) == 1:
        return report.accepted_entries[0]
    raise ProteomicsOperatorError(
        ProteomicsOperatorErrorCode.QC_SAMPLE_NOT_FOUND,
        "design table requires --sample-id when multiple rows are present",
    )


def _build_psm_mapping(
    *,
    run_id_column: str | None,
    spectrum_id_column: str,
    peptide_column: str,
    modified_peptide_column: str | None,
    charge_column: str,
    score_column: str,
    q_value_column: str | None,
    protein_refs_column: str | None,
    decoy_label_column: str | None,
    contaminant_label_column: str | None,
    protein_separator: str,
    posterior_error_probability_column: str | None = None,
    intensity_column: str | None = None,
) -> SearchResultColumnMapping:
    return SearchResultColumnMapping(
        run_id=run_id_column,
        spectrum_id=spectrum_id_column,
        peptide=peptide_column,
        modified_peptide=modified_peptide_column,
        charge=charge_column,
        score=score_column,
        intensity=intensity_column,
        q_value=q_value_column,
        posterior_error_probability=posterior_error_probability_column,
        protein_refs=protein_refs_column,
        decoy_label=decoy_label_column,
        contaminant_label=contaminant_label_column,
        protein_separator=protein_separator,
    )


def _build_decoy_policy(
    *,
    decoy_prefix: str | None,
    decoy_suffix: str | None,
) -> TargetDecoyLabelPolicy:
    return TargetDecoyLabelPolicy(
        protein_prefix=decoy_prefix,
        protein_suffix=decoy_suffix,
    )


def _build_run_detection_contexts(
    design_entries: tuple[ExperimentalDesignEntry, ...],
) -> tuple[RunDetectionContext, ...]:
    return tuple(
        RunDetectionContext(
            run_id=entry.spectra_file,
            sample_id=entry.sample_id,
            condition_id=entry.condition,
            replicate_id=str(entry.replicate),
        )
        for entry in design_entries
    )


def _filter_review_psms(
    records: tuple[PsmRecord, ...],
    *,
    threshold: float,
    score_orientation: str,
) -> tuple[PsmRecord, ...]:
    """Preserve imported q-values for review surfaces when they are complete."""
    if records and all(record.q_value is not None for record in records):
        return tuple(
            record
            for record in records
            if record.q_value is not None and record.q_value <= threshold
        )
    return cast(
        tuple[PsmRecord, ...],
        filter_psms_by_fdr(
            records,
            threshold=threshold,
            score_orientation=score_orientation,
        ),
    )


def _default_psm_mapping() -> SearchResultColumnMapping:
    return SearchResultColumnMapping(
        spectrum_id="spectrum_id",
        peptide="peptide",
        charge="charge",
        score="score",
        q_value="q_value",
        protein_refs="proteins",
    )


def _infer_input_kind(input_path: Path, explicit_kind: str) -> str:
    if explicit_kind != "auto":
        return explicit_kind
    suffix = input_path.suffix.lower()
    if suffix in {".fasta", ".fa", ".faa"}:
        return "fasta"
    if suffix == ".mgf":
        return "mgf"
    if suffix == ".mzml":
        return "mzml"
    if input_path.name.endswith(".design.tsv") or input_path.name.endswith(
        ".design.csv"
    ):
        return "design-table"
    if suffix == ".tsv":
        return "psm"
    if suffix == ".json":
        return "mod-registry"
    raise click.ClickException(
        f"cannot infer input kind for {input_path.name!r}; use --kind fasta, psm, mgf, mzml, design-table, or mod-registry"
    )


__all__ = [
    "Any",
    "BiologicalContextColumnMapping",
    "BiologicalContextKind",
    "BiomarkerCandidateKind",
    "BiomarkerCandidateRankingInput",
    "BiomarkerStabilityPolicy",
    "BiomarkerStabilityReasonCode",
    "CompartmentBiologyPolicy",
    "ComplexActivityPolicy",
    "ComplexEnrichmentCorrectionPolicy",
    "ComplexMembershipColumnMapping",
    "CrossRunReproducibilityClass",
    "DecoyGenerationMode",
    "DiaPeptideRollupMethod",
    "DiaPrecursorMatrixPolicy",
    "DiaPrecursorQValueFilterTiming",
    "DiaProteinMatrixTargetKind",
    "DiaProteinRollupMethod",
    "DiaSharedPeptidePolicy",
    "DifferentialAbundanceTestType",
    "DiscoveryTargetProteinEntry",
    "DiscoveryTargetedPeptideSelectionEntry",
    "DiseasePhenotypeInterpretationPolicy",
    "DrugTargetInterpretationPolicy",
    "DuplicateAccessionPolicy",
    "ExperimentalDesignEntry",
    "FailureExplanationRequest",
    "FastaDatabaseProfile",
    "FastaParseMode",
    "FastaParseReport",
    "FdrPolicy",
    "FormatConversionTarget",
    "FragmentIonSeries",
    "GoAnnotationColumnMapping",
    "GoEnrichmentCorrectionPolicy",
    "HeatmapMissingValuePolicy",
    "HeatmapPreparationPolicy",
    "ImputationMethod",
    "IsotopicLabelingPolicy",
    "ModificationRegistryDocument",
    "Ms1FeatureColumnMapping",
    "NormalizationMethod",
    "NormalizedProteinRecord",
    "OrthologColumnMapping",
    "PairedDifferentialPolicy",
    "PanelRedundancyCandidateInput",
    "PanelRedundancyPolicy",
    "ParsimonyVariant",
    "Path",
    "PathwayActivityPolicy",
    "PathwayEnrichmentCorrectionPolicy",
    "PathwayMembershipColumnMapping",
    "PeptideChemicalLiabilityTier",
    "PeptideDetectabilityTier",
    "PeptideDigestionMode",
    "PeptideEvidenceClass",
    "PeptideEvidenceEntry",
    "PeptideMatrixGroupingMode",
    "PeptideUniquenessClass",
    "PowerEstimationPolicy",
    "PpiEdgeColumnMapping",
    "PrecursorIntensityColumnMapping",
    "PrecursorMassErrorQuery",
    "ProgramSpec",
    "ProteaseRule",
    "ProteinAnnotationColumnMapping",
    "ProteinMatrixTargetKind",
    "ProteinReferenceColumnMapping",
    "ProteinReferenceEntry",
    "ProteinSetColumnMapping",
    "ProteinSetEnrichmentMissingBackgroundPolicy",
    "ProteinSetEnrichmentPolicy",
    "ProteinSetScoringPolicy",
    "ProteomicsFormatKind",
    "ProteomicsOperatorError",
    "ProteomicsOperatorErrorCode",
    "PsmRecord",
    "PtmLocalizationColumnMapping",
    "PtmMotifBackgroundMode",
    "PtmMotifComparisonPolicy",
    "PtmMotifRegulationDirection",
    "PtmPeptideColumnMapping",
    "PtmPhosphositeSelectionPolicy",
    "PtmProteinCorrectionMode",
    "PtmRegulatorEnrichmentPolicy",
    "PtmSiteAnnotationColumnMapping",
    "PtmSiteContextColumnMapping",
    "PtmSiteQuantAmbiguityPolicy",
    "QcEvidenceInputFile",
    "QuantEntityLevel",
    "QuantMeasureKind",
    "QuantRollupMethod",
    "RegulatorEvidenceColumnMapping",
    "RegulatorSiteSignalColumnMapping",
    "ResultExplanationKind",
    "ResultExplanationRequest",
    "ResultQueryKind",
    "ResultQueryRequest",
    "RunDetectionContext",
    "ScoreOrientation",
    "SearchAdapterKind",
    "SearchEngineModifiedPeptideDialect",
    "SearchResultColumnMapping",
    "SilacColumnMapping",
    "SilacLabel",
    "SilacQuantificationPolicy",
    "SilacValidationPolicy",
    "SpectralLibraryEntry",
    "SpectralLibraryFormat",
    "SpectralSimilarityMethod",
    "SpectrumModel",
    "SpectrumSimilarityMode",
    "StaticModification",
    "TargetDecoyContaminantClass",
    "TargetDecoyLabel",
    "TargetDecoyLabelPolicy",
    "TargetDecoyReferenceCase",
    "TargetPanelSourceKind",
    "TargetedAssayInterferenceReason",
    "TargetedAssayInterferenceRiskTier",
    "TargetedPanelAssayInput",
    "TargetedPanelBiomarkerCandidateInput",
    "TargetedPanelCandidateKind",
    "TargetedPanelSelectedPeptideInput",
    "TargetedPanelTransitionInput",
    "TargetedPanelWarningCode",
    "TargetedPeptideCandidateSource",
    "TargetedResultSourceKind",
    "TargetedResultValidationPolicy",
    "TargetedTransitionInterferenceRisk",
    "TargetedTransitionSelectionFragment",
    "TargetedTransitionSelectionPeptideEntry",
    "TargetedValidationDiscoveryClaimInput",
    "TargetedValidationPanelAssayInput",
    "TargetedValidationReasonCode",
    "TargetedValidationVerdict",
    "TimeCourseTestingPolicy",
    "TmtInterferencePolicy",
    "TmtNormalizationMethod",
    "TmtNormalizationPolicy",
    "TmtPlexIntegrationPolicy",
    "TmtReporterChannelColumn",
    "TmtReporterColumnMapping",
    "TmtSearchResultSourceKind",
    "TmtValidationPolicy",
    "ValidationEvidenceDiscoveryInput",
    "ValidationEvidenceOmittedCandidateInput",
    "ValidationEvidencePanelAssayInput",
    "ValidationEvidenceRedundancyInput",
    "ValidationEvidenceResultAssayInput",
    "ValidationEvidenceResultInput",
    "ValidationEvidenceStabilityInput",
    "ValidationExperimentPlanningPolicy",
    "ValidationPlanningBiomarkerCandidateInput",
    "ValidationPlanningOmittedCandidateInput",
    "ValidationPlanningPanelAssayInput",
    "ValidationPlanningPilotVarianceInput",
    "ValidationPlanningSelectedPeptideInput",
    "VariableModification",
    "VolcanoReviewPolicy",
    "WorkflowSchedulerKind",
    "_build_decoy_policy",
    "_build_psm_mapping",
    "_build_run_detection_contexts",
    "_conversion_target_choice",
    "_decoy_mode_choice",
    "_default_psm_mapping",
    "_digestion_mode_choice",
    "_duplicate_accession_policy_choice",
    "_emit_fasta_profile",
    "_emit_json",
    "_export_format_choice",
    "_file_sha256",
    "_filter_review_psms",
    "_fragment_series_choice",
    "_heatmap_missing_value_choice",
    "_imputation_choice",
    "_infer_input_kind",
    "_label_based_differential_normalization_choice",
    "_load_fasta_report",
    "_load_precursor_mass_error_queries",
    "_mode_choice",
    "_modified_peptide_dialect_choice",
    "_normalization_choice",
    "_parse_silac_label_spec",
    "_parse_tmt_channel_column_specs",
    "_peptide_matrix_builder_input_kind_choice",
    "_peptide_matrix_grouping_choice",
    "_peptide_matrix_input_kind_choice",
    "_protein_matrix_target_choice",
    "_quant_entity_level_choice",
    "_quant_measure_choice",
    "_quant_rollup_choice",
    "_resolve_cli_protease_rule",
    "_resolve_cli_theoretical_digest_modifications",
    "_score_orientation_choice",
    "_search_adapter_choice",
    "_select_design_entry",
    "_silac_label_choice",
    "_tmt_normalization_method_choice",
    "_tmt_ratio_normalization_choice",
    "_tmt_source_kind_choice",
    "_validate_kind_choice",
    "_workflow_scheduler_choice",
    "_write_text_output",
    "annotate_psm_error_rates",
    "annotate_spectrum_fragments",
    "append_contaminant_database",
    "apply_benjamini_hochberg",
    "apply_complex_enrichment_multiple_testing",
    "apply_go_enrichment_multiple_testing",
    "apply_pathway_enrichment_multiple_testing",
    "apply_q_values",
    "approximate_peptide_isotope_envelope",
    "assign_confidence_labels",
    "assign_razor_peptides",
    "build_analysis_recommendation_report_from_artifacts",
    "build_batch_effect_estimator_report",
    "build_batch_qc_assessment",
    "build_belief_audit_report_from_artifacts",
    "build_biological_context_mapping_report",
    "build_biomarker_candidate_ranking_report",
    "build_biomarker_stability_report",
    "build_calibration_plot_data",
    "build_comet_import_report",
    "build_compact_result_summary_report_from_artifacts",
    "build_compartment_biology_report",
    "build_complex_activity_report",
    "build_complex_enrichment_report",
    "build_contaminant_evidence_report",
    "build_contaminant_peptide_match_report",
    "build_core_protein_inference_benchmark_suite",
    "build_decoy_generation_manifest",
    "build_decoy_generation_report",
    "build_dia_protein_matrix_report",
    "build_dia_volcano_review",
    "build_diann_import_report",
    "build_diann_library_coverage_report",
    "build_diann_peptide_matrix_report",
    "build_diann_peptide_target_panel_report",
    "build_diann_precursor_matrix_report",
    "build_diann_protein_target_panel_report",
    "build_diann_run_qc_report",
    "build_differential_abundance_report",
    "build_digest_manifest",
    "build_discovery_targeted_peptide_selection_report",
    "build_disease_phenotype_interpretation_report",
    "build_drug_target_interpretation_report",
    "build_evidence_level_fdr_review_report",
    "build_experiment_feasibility_report",
    "build_failure_explanation_report",
    "build_fasta_database_profile",
    "build_fasta_provenance_manifest",
    "build_fasta_stats",
    "build_fdr_audit_trail",
    "build_fragment_ion_review_report",
    "build_fragpipe_import_benchmark_report",
    "build_fragpipe_import_report",
    "build_generic_psm_mapper_report",
    "build_go_enrichment_report",
    "build_heatmap_preparation_report",
    "build_imputation_report",
    "build_imputation_sensitivity_report",
    "build_instrument_batch_qc_report",
    "build_lab_protocol_interpretation_profile",
    "build_label_based_volcano_review",
    "build_label_free_intensity_table",
    "build_lcms_run_qc_report",
    "build_lfq_peptide_target_panel_report",
    "build_lfq_protein_lfq_target_panel_report",
    "build_lfq_protein_target_panel_report",
    "build_limma_compatible_quant_package",
    "build_maxquant_import_report",
    "build_missingness_classifier_report",
    "build_modification_localization_advisory",
    "build_modification_resolution_report",
    "build_modified_peptide",
    "build_msstats_compatible_input_report",
    "build_multi_condition_differential_abundance_report",
    "build_multi_contrast_consistency_report",
    "build_multiplex_metadata_validation_report",
    "build_mzml_collection_summary",
    "build_mzml_practical_review_report",
    "build_normalization_comparison_report",
    "build_normalization_strategy_comparison_report",
    "build_normalized_run_bundle",
    "build_openms_import_report",
    "build_ortholog_mapping_report",
    "build_panel_redundancy_report",
    "build_parsimony_review_report",
    "build_pathway_activity_report",
    "build_pathway_enrichment_report",
    "build_peptide_charge_state",
    "build_peptide_cross_run_reproducibility_report",
    "build_peptide_database_lookup_report",
    "build_peptide_detectability_report",
    "build_peptide_elemental_composition",
    "build_peptide_evidence_review_report",
    "build_peptide_intensity_matrix_from_features",
    "build_peptide_intensity_matrix_from_precursors",
    "build_peptide_intensity_matrix_from_psms",
    "build_peptide_profile_inconsistency_report",
    "build_peptide_property_report",
    "build_peptide_summary_report",
    "build_peptide_uniqueness_across_database",
    "build_performance_snapshot",
    "build_picked_protein_fdr_review_report",
    "build_power_estimation_report",
    "build_ppi_network_module_report",
    "build_precursor_mass_error_report",
    "build_protein_ambiguity_review_report",
    "build_protein_annotation_mapping_report",
    "build_protein_coverage_map",
    "build_protein_coverage_plot_report",
    "build_protein_coverage_review_report",
    "build_protein_cross_run_reproducibility_report",
    "build_protein_evidence_review_report",
    "build_protein_grouping_review_report",
    "build_protein_groups",
    "build_protein_intensity_matrix_from_features",
    "build_protein_intensity_matrix_from_psms",
    "build_protein_lfq_report_from_peptides",
    "build_protein_set_enrichment_report",
    "build_protein_set_scoring_report",
    "build_protein_summary_report",
    "build_proteomics_workflow_runtime_bundle",
    "build_protocol_aware_qc_threshold_policy",
    "build_protocol_consistency_report",
    "build_psm_error_rate_annotation_report",
    "build_psm_evidence_inspection_report",
    "build_psm_summary_report",
    "build_psm_target_decoy_fdr_report",
    "build_ptm_ambiguity_review_report",
    "build_ptm_differential_analysis_report",
    "build_ptm_differential_volcano_plot",
    "build_ptm_enrichment_input",
    "build_ptm_localization_scoring_report",
    "build_ptm_motif_windows",
    "build_ptm_occupancy_counterpart_report",
    "build_ptm_phosphosite_motif_enrichment_report",
    "build_ptm_protein_site_mapping_report",
    "build_ptm_regulator_enrichment_report",
    "build_ptm_site_annotation_biology_summary",
    "build_ptm_site_annotation_mapping_report",
    "build_ptm_site_context_report",
    "build_ptm_site_coverage_report",
    "build_ptm_site_fdr",
    "build_ptm_site_group_quantification_report",
    "build_ptm_site_occupancy_report",
    "build_ptm_site_quantification_report",
    "build_ptm_site_table",
    "build_ptm_volcano_review",
    "build_qc_evidence_manifest",
    "build_quant_design_matrix_report",
    "build_regulator_inference_report",
    "build_replicate_and_batch_qc_report",
    "build_result_explanation_report_from_artifacts",
    "build_result_query_report_from_artifacts",
    "build_run_qc_assessment",
    "build_sage_import_report",
    "build_sample_exploration_report",
    "build_sample_sheet_repair_suggestion_report",
    "build_score_separation_diagnostic_report",
    "build_search_adapter_capability_matrix",
    "build_search_adapter_conformance_report",
    "build_search_adapter_provenance_manifest",
    "build_search_engine_modified_peptide_report",
    "build_search_result_provenance_manifest",
    "build_silac_ratio_report",
    "build_silac_validation_report",
    "build_skyline_result_import_report",
    "build_spectral_count_table",
    "build_spectral_library_index",
    "build_spectral_library_summary",
    "build_spectronaut_import_report",
    "build_spectronaut_peptide_matrix_report",
    "build_spectronaut_precursor_matrix_report",
    "build_spectronaut_protein_matrix_report",
    "build_spectrum_collection_summary",
    "build_spectrum_library_similarity_report",
    "build_spectrum_metrics",
    "build_spectrum_peak_match_report",
    "build_spectrum_plot_payload",
    "build_spectrum_provenance_manifest",
    "build_spectrum_run_qc_plot_payload",
    "build_spectrum_run_qc_report",
    "build_spectrum_similarity_comparison_report",
    "build_spectrum_summary_table_report",
    "build_statistical_backend_validation_report",
    "build_streaming_parse_profile",
    "build_target_decoy_reference_validation_report",
    "build_targeted_assay_interference_report",
    "build_targeted_carryover_report",
    "build_targeted_panel_design_report",
    "build_targeted_result_validation_report",
    "build_targeted_transition_selection_report",
    "build_theoretical_digest_bundle",
    "build_time_course_differential_report",
    "build_tmt_interference_report",
    "build_tmt_normalization_report",
    "build_tmt_plex_integration_report",
    "build_tmt_ratio_report",
    "build_tmt_reporter_feature_bundle",
    "build_tmt_reporter_matrix_report",
    "build_tmt_validation_report",
    "build_transition_qc_report_from_table",
    "build_transition_table_result_import_report",
    "build_validation_evidence_card_report",
    "build_validation_experiment_planning_report",
    "build_workflow_runtime_validation_report",
    "calculate_fragment_ions",
    "calculate_grouped_fdr",
    "calculate_level_specific_fdr",
    "calculate_picked_protein_fdr",
    "canonicalize_modified_peptide",
    "click",
    "compare_search_result_reports",
    "convert_proteomics_format",
    "create_program_spec",
    "csv",
    "deduplicate_fasta_records",
    "default_qc_threshold_policy",
    "digest_protein_records",
    "export_batch_effect_batches_tsv",
    "export_batch_effect_principal_components_tsv",
    "export_batch_effect_summary_tsv",
    "export_differential_abundance_tsv",
    "export_differential_broken_pairs_tsv",
    "export_heatmap_column_metadata_tsv",
    "export_heatmap_matrix_tsv",
    "export_heatmap_row_metadata_tsv",
    "export_heatmap_summary_tsv",
    "export_limma_assay_matrix_tsv",
    "export_limma_contrast_matrix_tsv",
    "export_limma_design_matrix_tsv",
    "export_limma_sample_annotations_tsv",
    "export_msstats_compatible_input_tsv",
    "export_multi_condition_differential_abundance_tsv",
    "export_multi_contrast_consistency_tsv",
    "export_multiplex_channel_assignment_tsv",
    "export_multiplex_duplicate_assignment_tsv",
    "export_multiplex_metadata_summary_tsv",
    "export_multiplex_missing_condition_tsv",
    "export_peptide_protein_table_tsv",
    "export_peptides_fasta",
    "export_peptides_jsonl",
    "export_peptides_parquet",
    "export_peptides_tsv",
    "export_power_effect_size_grid_tsv",
    "export_power_estimation_summary_tsv",
    "export_power_variance_tsv",
    "export_psm_jsonl",
    "export_psm_tsv",
    "export_ptm_differential_volcano_tsv",
    "export_ptm_mapped_site_annotation_tsv",
    "export_ptm_phosphosite_motif_enriched_term_tsv",
    "export_ptm_phosphosite_motif_frequency_tsv",
    "export_ptm_phosphosite_motif_logo_tsv",
    "export_ptm_phosphosite_motif_window_tsv",
    "export_ptm_regulator_enrichment_summary_tsv",
    "export_ptm_regulator_enrichment_tsv",
    "export_ptm_site_annotation_biology_tsv",
    "export_ptm_site_annotation_mapping_summary_tsv",
    "export_ptm_site_context_summary_tsv",
    "export_ptm_site_context_tsv",
    "export_ptm_site_differential_broken_pairs_tsv",
    "export_ptm_site_differential_tsv",
    "export_ptm_unmapped_site_annotation_tsv",
    "export_quant_design_contrast_estimates_tsv",
    "export_quant_design_matrix_tsv",
    "export_quant_design_model_coefficients_tsv",
    "export_sample_cluster_tsv",
    "export_sample_correlation_tsv",
    "export_sample_distance_tsv",
    "export_sample_exploration_summary_tsv",
    "export_sample_outlier_tsv",
    "export_sample_pca_scores_tsv",
    "export_sample_pca_variance_tsv",
    "export_sample_sheet_repair_suggestions_tsv",
    "export_silac_peptide_ratio_tsv",
    "export_silac_protein_ratio_tsv",
    "export_silac_ratio_summary_tsv",
    "export_silac_validation_distribution_tsv",
    "export_silac_validation_label_tsv",
    "export_silac_validation_summary_tsv",
    "export_silac_validation_weak_tsv",
    "export_spectra_jsonl",
    "export_spectrum_peak_match_tsv",
    "export_spectrum_unmatched_peak_tsv",
    "export_time_course_differential_tsv",
    "export_tmt_channel_distribution_tsv",
    "export_tmt_channel_mapping_tsv",
    "export_tmt_channel_totals_tsv",
    "export_tmt_filtered_interference_tsv",
    "export_tmt_integrated_protein_matrix_tsv",
    "export_tmt_interference_channel_summary_tsv",
    "export_tmt_interference_observation_tsv",
    "export_tmt_interference_summary_tsv",
    "export_tmt_normalization_summary_tsv",
    "export_tmt_normalization_transform_tsv",
    "export_tmt_normalized_peptide_matrix_tsv",
    "export_tmt_normalized_protein_matrix_tsv",
    "export_tmt_peptide_matrix_tsv",
    "export_tmt_peptide_ratio_tsv",
    "export_tmt_plex_alignment_tsv",
    "export_tmt_plex_effect_tsv",
    "export_tmt_plex_integration_summary_tsv",
    "export_tmt_protein_matrix_tsv",
    "export_tmt_protein_ratio_tsv",
    "export_tmt_ratio_summary_tsv",
    "export_tmt_report_summary_tsv",
    "export_tmt_validation_channel_tsv",
    "export_tmt_validation_distribution_tsv",
    "export_tmt_validation_summary_tsv",
    "export_tmt_validation_weak_tsv",
    "export_volcano_review_html",
    "export_volcano_review_json",
    "export_volcano_review_svg",
    "extract_mzml_chromatograms",
    "extract_mzml_chromatographic_evidence",
    "extract_mzml_chromatographic_peaks",
    "extract_mzml_dia_fragment_trace_coelution",
    "extract_mzml_precursor_isotope_fit",
    "extract_mzml_raw_signal_evidence_cards",
    "extract_mzml_retention_time_alignment",
    "extract_mzml_xic_traces",
    "filter_fasta_records",
    "filter_psms_by_fdr",
    "find_spectral_library_candidates",
    "fit_quant_design_matrix_model",
    "format_failure_explanation_for_cli",
    "generate_decoy_records",
    "get_modification",
    "get_search_adapter_manifest",
    "hashlib",
    "import_spectral_library",
    "impute_label_free_table",
    "infer_proteins_by_parsimony",
    "json",
    "load_modification_registry",
    "load_qc_threshold_policy",
    "map_ptm_evidence_to_protein_sites",
    "normalize_label_free_table",
    "normalize_search_results_with_adapter",
    "parse_biological_context_table",
    "parse_complex_membership_table",
    "parse_experimental_design_table",
    "parse_fasta_document",
    "parse_go_annotation_table",
    "parse_lab_protocol_context_table",
    "parse_limma_result_table",
    "parse_mgf",
    "parse_ms1_feature_table",
    "parse_msstats_result_table",
    "parse_mzml",
    "parse_ortholog_table",
    "parse_pathway_membership_table",
    "parse_ppi_edge_table",
    "parse_precursor_intensity_table",
    "parse_protein_annotation_table",
    "parse_protein_reference_table",
    "parse_protein_set_table",
    "parse_psm_tsv",
    "parse_ptm_localization_tsv",
    "parse_ptm_peptide",
    "parse_ptm_peptide_tsv",
    "parse_ptm_site_annotation_tsv",
    "parse_ptm_site_context_tsv",
    "parse_regulator_evidence_table",
    "parse_regulator_site_signal_table",
    "parse_search_parameter_file",
    "parse_silac_feature_table",
    "parse_tmt_reporter_table",
    "peptide_export_fingerprint",
    "predict_peptide_isotope_envelopes",
    "program_summary",
    "render_analysis_recommendation_summary_tsv",
    "render_analysis_recommendation_tsv",
    "render_belief_audit_html",
    "render_belief_audit_summary_tsv",
    "render_belief_audit_tsv",
    "render_biological_context_mapping_summary_tsv",
    "render_biological_context_mapping_tsv",
    "render_biological_context_term_tsv",
    "render_biomarker_candidate_ranking_summary_tsv",
    "render_biomarker_candidate_ranking_tsv",
    "render_biomarker_stability_candidate_tsv",
    "render_biomarker_stability_subgroup_tsv",
    "render_biomarker_stability_summary_tsv",
    "render_biomarker_stability_tsv",
    "render_chimeric_spectrum_competing_evidence_tsv",
    "render_chimeric_spectrum_spectra_tsv",
    "render_chromatographic_peaks_tsv",
    "render_chromatographic_peptide_evidence_tsv",
    "render_chromatographic_target_evidence_tsv",
    "render_comet_canonical_psm_tsv",
    "render_comet_psm_tsv",
    "render_comet_summary_tsv",
    "render_compact_result_summary_entry_tsv",
    "render_compact_result_summary_markdown",
    "render_compact_result_summary_overview_tsv",
    "render_compartment_activity_condition_comparison_tsv",
    "render_compartment_activity_condition_score_tsv",
    "render_compartment_activity_matrix_tsv",
    "render_compartment_activity_sample_score_tsv",
    "render_compartment_activity_unresolved_member_tsv",
    "render_compartment_biology_summary_tsv",
    "render_compartment_enrichment_tsv",
    "render_complex_activity_condition_comparison_tsv",
    "render_complex_activity_condition_score_tsv",
    "render_complex_activity_matrix_tsv",
    "render_complex_activity_sample_score_tsv",
    "render_complex_activity_summary_tsv",
    "render_complex_activity_unresolved_member_tsv",
    "render_complex_enrichment_entry_tsv",
    "render_complex_enrichment_summary_tsv",
    "render_complex_member_contribution_tsv",
    "render_complex_unresolved_member_tsv",
    "render_contaminant_burden_tsv",
    "render_contaminant_proteins_tsv",
    "render_cross_run_reproducibility_entries_tsv",
    "render_cross_run_reproducibility_summary_tsv",
    "render_dia_fragment_coelution_fragments_tsv",
    "render_dia_fragment_coelution_runs_tsv",
    "render_dia_library_coverage_condition_tsv",
    "render_dia_library_coverage_observed_outside_peptide_tsv",
    "render_dia_library_coverage_observed_outside_protein_tsv",
    "render_dia_library_coverage_peptide_tsv",
    "render_dia_library_coverage_protein_tsv",
    "render_dia_library_coverage_sample_tsv",
    "render_dia_library_coverage_summary_tsv",
    "render_dia_peptide_quantity_matrix_tsv",
    "render_dia_precursor_matrix_summary_tsv",
    "render_dia_precursor_metadata_tsv",
    "render_dia_precursor_q_value_matrix_tsv",
    "render_dia_precursor_quantity_matrix_tsv",
    "render_dia_protein_matrix_summary_tsv",
    "render_dia_protein_quantity_matrix_tsv",
    "render_dia_protein_rollup_evidence_tsv",
    "render_dia_run_qc_correlation_tsv",
    "render_dia_run_qc_intensity_distribution_tsv",
    "render_dia_run_qc_outlier_tsv",
    "render_dia_run_qc_run_table_tsv",
    "render_dia_run_qc_summary_tsv",
    "render_diann_precursor_tsv",
    "render_diann_protein_group_tsv",
    "render_diann_summary_tsv",
    "render_discovery_targeted_peptide_selection_rejected_tsv",
    "render_discovery_targeted_peptide_selection_selected_tsv",
    "render_discovery_targeted_peptide_selection_summary_tsv",
    "render_disease_phenotype_interpretation_summary_tsv",
    "render_disease_phenotype_interpretation_tsv",
    "render_drug_target_interpretation_summary_tsv",
    "render_drug_target_interpretation_tsv",
    "render_evidence_level_fdr_entries_tsv",
    "render_evidence_level_fdr_summary_tsv",
    "render_experiment_feasibility_group_sizes_tsv",
    "render_experiment_feasibility_invalid_contrasts_tsv",
    "render_experiment_feasibility_missing_metadata_tsv",
    "render_experiment_feasibility_model_support_tsv",
    "render_experiment_feasibility_valid_contrasts_tsv",
    "render_failure_explanation_summary_tsv",
    "render_failure_explanation_tsv",
    "render_fasta_profile_invalid_sequence_tsv",
    "render_fasta_profile_length_distribution_tsv",
    "render_fasta_profile_organism_distribution_tsv",
    "render_fasta_profile_summary_tsv",
    "render_fragment_ion_report_tsv",
    "render_fragment_ratio_stability_fragments_tsv",
    "render_fragment_ratio_stability_observations_tsv",
    "render_fragpipe_benchmark_summary_tsv",
    "render_fragpipe_canonical_psm_tsv",
    "render_fragpipe_count_comparisons_tsv",
    "render_fragpipe_open_search_evidence_tsv",
    "render_fragpipe_peptide_tsv",
    "render_fragpipe_protein_group_comparison_tsv",
    "render_fragpipe_protein_quantity_tsv",
    "render_fragpipe_protein_tsv",
    "render_fragpipe_psm_tsv",
    "render_fragpipe_q_value_comparison_tsv",
    "render_fragpipe_summary_tsv",
    "render_generic_psm_mapper_tsv",
    "render_go_enrichment_summary_tsv",
    "render_go_enrichment_term_tsv",
    "render_go_enrichment_unannotated_tsv",
    "render_isotope_envelopes_tsv",
    "render_mapped_ortholog_tsv",
    "render_maxquant_evidence_tsv",
    "render_maxquant_lfq_candidate_tsv",
    "render_maxquant_peptide_tsv",
    "render_maxquant_protein_group_tsv",
    "render_maxquant_summary_tsv",
    "render_openms_feature_tsv",
    "render_openms_protein_tsv",
    "render_openms_psm_tsv",
    "render_openms_summary_tsv",
    "render_ortholog_mapping_summary_tsv",
    "render_panel_redundancy_candidate_tsv",
    "render_panel_redundancy_cluster_tsv",
    "render_panel_redundancy_dropped_tsv",
    "render_panel_redundancy_summary_tsv",
    "render_parsimony_review_ambiguities_tsv",
    "render_parsimony_review_proteins_tsv",
    "render_parsimony_review_summary_tsv",
    "render_pathway_activity_condition_comparison_tsv",
    "render_pathway_activity_condition_score_tsv",
    "render_pathway_activity_matrix_tsv",
    "render_pathway_activity_sample_score_tsv",
    "render_pathway_activity_summary_tsv",
    "render_pathway_activity_unresolved_member_tsv",
    "render_pathway_enrichment_entry_tsv",
    "render_pathway_enrichment_summary_tsv",
    "render_pathway_member_contribution_tsv",
    "render_pathway_unresolved_member_tsv",
    "render_peptide_detectability_tsv",
    "render_peptide_evidence_entries_tsv",
    "render_peptide_evidence_summary_tsv",
    "render_peptide_intensity_aggregation_tsv",
    "render_peptide_intensity_matrix_summary_tsv",
    "render_peptide_intensity_matrix_tsv",
    "render_peptide_intensity_missingness_mask_tsv",
    "render_peptide_intensity_missingness_tsv",
    "render_peptide_profile_inconsistency_tsv",
    "render_picked_protein_fdr_entries_tsv",
    "render_picked_protein_fdr_summary_tsv",
    "render_ppi_isolated_protein_tsv",
    "render_ppi_module_enrichment_tsv",
    "render_ppi_module_tsv",
    "render_ppi_network_edge_tsv",
    "render_ppi_network_module_summary_tsv",
    "render_precursor_isotope_fit_entries_tsv",
    "render_precursor_isotope_fit_peaks_tsv",
    "render_precursor_isotope_fit_summary_tsv",
    "render_precursor_mass_error_distribution_tsv",
    "render_precursor_mass_error_observations_tsv",
    "render_precursor_mass_error_summary_tsv",
    "render_protein_ambiguity_entries_tsv",
    "render_protein_ambiguity_summary_tsv",
    "render_protein_annotation_summary_tsv",
    "render_protein_annotation_tsv",
    "render_protein_coverage_entries_tsv",
    "render_protein_coverage_peptide_coordinates_tsv",
    "render_protein_coverage_plot_html",
    "render_protein_coverage_plot_positions_tsv",
    "render_protein_coverage_plot_svg",
    "render_protein_coverage_regions_tsv",
    "render_protein_coverage_summary_tsv",
    "render_protein_coverage_uncovered_regions_tsv",
    "render_protein_evidence_entries_tsv",
    "render_protein_evidence_summary_tsv",
    "render_protein_grouping_entries_tsv",
    "render_protein_grouping_summary_tsv",
    "render_protein_inference_benchmark_assessments_tsv",
    "render_protein_inference_benchmark_scenarios_tsv",
    "render_protein_inference_benchmark_summary_tsv",
    "render_protein_intensity_matrix_summary_tsv",
    "render_protein_intensity_matrix_tsv",
    "render_protein_intensity_missingness_tsv",
    "render_protein_lfq_disconnected_components_tsv",
    "render_protein_lfq_matrix_tsv",
    "render_protein_lfq_missingness_tsv",
    "render_protein_lfq_pairwise_ratios_tsv",
    "render_protein_lfq_summary_tsv",
    "render_protein_peptide_contribution_tsv",
    "render_protein_set_condition_comparison_tsv",
    "render_protein_set_condition_score_tsv",
    "render_protein_set_enrichment_summary_tsv",
    "render_protein_set_enrichment_tsv",
    "render_protein_set_sample_score_tsv",
    "render_protein_set_score_matrix_tsv",
    "render_protein_set_scoring_summary_tsv",
    "render_protein_set_universe_gap_tsv",
    "render_protein_set_unresolved_member_tsv",
    "render_protocol_consistency_tsv",
    "render_psm_error_rate_annotation_summary_tsv",
    "render_psm_error_rate_annotation_tsv",
    "render_psm_evidence_inspection_summary_tsv",
    "render_psm_inspection_distribution_tsv",
    "render_psm_target_decoy_fdr_summary_tsv",
    "render_psm_target_decoy_fdr_tsv",
    "render_ptm_ambiguity_review_summary_tsv",
    "render_ptm_coordinate_validation_tsv",
    "render_ptm_evidence_site_candidate_tsv",
    "render_ptm_localization_scoring_entry_tsv",
    "render_ptm_localization_scoring_summary_tsv",
    "render_ptm_localized_site_review_tsv",
    "render_ptm_occupancy_counterpart_tsv",
    "render_ptm_peptide_record_tsv",
    "render_ptm_peptide_rejected_tsv",
    "render_ptm_peptide_site_tsv",
    "render_ptm_peptide_summary_tsv",
    "render_ptm_protein_site_mapping_tsv",
    "render_ptm_site_coverage_tsv",
    "render_ptm_site_group_quant_matrix_tsv",
    "render_ptm_site_group_quant_missingness_tsv",
    "render_ptm_site_group_quant_summary_tsv",
    "render_ptm_site_occupancy_entry_tsv",
    "render_ptm_site_occupancy_summary_tsv",
    "render_ptm_site_quant_excluded_tsv",
    "render_ptm_site_quant_matrix_tsv",
    "render_ptm_site_quant_missingness_tsv",
    "render_ptm_site_quant_summary_tsv",
    "render_ptm_site_table_tsv",
    "render_ptm_unlocalized_group_review_tsv",
    "render_ptm_unmapped_peptide_tsv",
    "render_qc_assessment_html",
    "render_qc_assessment_tsv",
    "render_raw_signal_evidence_card_summary_tsv",
    "render_raw_signal_evidence_card_tsv",
    "render_raw_signal_evidence_cards_html",
    "render_records_fasta",
    "render_regulator_inference_summary_tsv",
    "render_regulator_inference_tsv",
    "render_rejected_biological_context_tsv",
    "render_rejected_complex_membership_tsv",
    "render_rejected_evidence_tsv",
    "render_rejected_go_annotation_tsv",
    "render_rejected_ortholog_tsv",
    "render_rejected_pathway_membership_tsv",
    "render_rejected_ppi_edge_tsv",
    "render_rejected_protein_annotation_tsv",
    "render_rejected_protein_reference_tsv",
    "render_rejected_protein_set_membership_tsv",
    "render_rejected_protein_set_tsv",
    "render_rejected_regulator_evidence_tsv",
    "render_rejected_regulator_site_signal_tsv",
    "render_result_explanation_evidence_tsv",
    "render_result_explanation_summary_tsv",
    "render_result_explanation_tsv",
    "render_result_query_answer_tsv",
    "render_result_query_evidence_tsv",
    "render_result_query_summary_tsv",
    "render_retention_time_alignment_failed_anchors_tsv",
    "render_retention_time_alignment_models_tsv",
    "render_retention_time_alignment_residuals_tsv",
    "render_sage_canonical_psm_tsv",
    "render_sage_psm_tsv",
    "render_sage_summary_tsv",
    "render_score_separation_bins_tsv",
    "render_score_separation_summary_tsv",
    "render_spectral_library_candidates_tsv",
    "render_spectral_library_search_tsv",
    "render_spectral_library_summary_tsv",
    "render_spectronaut_precursor_quantity_tsv",
    "render_spectronaut_precursor_tsv",
    "render_spectronaut_protein_group_quantity_tsv",
    "render_spectronaut_protein_group_tsv",
    "render_spectronaut_summary_tsv",
    "render_spectrum_distribution_tsv",
    "render_spectrum_run_qc_distribution_tsv",
    "render_spectrum_run_qc_flagged_spectra_tsv",
    "render_spectrum_run_qc_spectra_tsv",
    "render_spectrum_run_qc_summary_tsv",
    "render_spectrum_run_qc_time_bins_tsv",
    "render_spectrum_run_qc_trace_tsv",
    "render_spectrum_similarity_tsv",
    "render_spectrum_summary_tsv",
    "render_target_decoy_reference_entries_tsv",
    "render_target_decoy_reference_summary_tsv",
    "render_target_panel_intensity_tsv",
    "render_target_panel_matrix_tsv",
    "render_target_panel_missing_tsv",
    "render_target_panel_summary_tsv",
    "render_target_panel_target_tsv",
    "render_targeted_assay_interference_assay_tsv",
    "render_targeted_assay_interference_panel_tsv",
    "render_targeted_assay_interference_summary_tsv",
    "render_targeted_assay_interference_transition_tsv",
    "render_targeted_assay_qc_coelution_tsv",
    "render_targeted_assay_qc_fragment_ratio_tsv",
    "render_targeted_assay_qc_replicate_cv_tsv",
    "render_targeted_assay_qc_retention_tsv",
    "render_targeted_assay_qc_summary_tsv",
    "render_targeted_assay_qc_target_tsv",
    "render_targeted_assay_qc_transition_coelution_tsv",
    "render_targeted_assay_qc_transition_qc_tsv",
    "render_targeted_assay_qc_transition_tsv",
    "render_targeted_assay_qc_unreliable_tsv",
    "render_targeted_carryover_candidates_tsv",
    "render_targeted_carryover_summary_tsv",
    "render_targeted_matrix_excluded_transition_tsv",
    "render_targeted_matrix_flagged_tsv",
    "render_targeted_matrix_missingness_tsv",
    "render_targeted_matrix_retained_transition_tsv",
    "render_targeted_matrix_sample_tsv",
    "render_targeted_matrix_summary_tsv",
    "render_targeted_matrix_target_tsv",
    "render_targeted_panel_design_assay_tsv",
    "render_targeted_panel_design_omitted_candidate_tsv",
    "render_targeted_panel_design_panel_tsv",
    "render_targeted_panel_design_summary_tsv",
    "render_targeted_result_observation_tsv",
    "render_targeted_result_validation_evidence_tsv",
    "render_targeted_result_validation_summary_tsv",
    "render_targeted_result_validation_tsv",
    "render_targeted_transition_selection_rejected_tsv",
    "render_targeted_transition_selection_selected_tsv",
    "render_targeted_transition_selection_summary_tsv",
    "render_transition_qc_sample_tsv",
    "render_transition_qc_summary_tsv",
    "render_transition_qc_transition_tsv",
    "render_transition_qc_weak_tsv",
    "render_unknown_compartment_localization_tsv",
    "render_unknown_disease_phenotype_annotation_tsv",
    "render_unmapped_biological_context_tsv",
    "render_unmapped_ortholog_tsv",
    "render_unmapped_protein_annotation_tsv",
    "render_unresolved_regulator_target_tsv",
    "render_validation_evidence_card_assay_tsv",
    "render_validation_evidence_card_summary_tsv",
    "render_validation_evidence_card_tsv",
    "render_validation_evidence_card_warning_tsv",
    "render_validation_experiment_planning_plan_tsv",
    "render_validation_experiment_planning_summary_tsv",
    "render_validation_experiment_planning_warning_tsv",
    "render_xic_traces_tsv",
    "require_single_lab_protocol_context",
    "resolve_protease_rule",
    "score_chimeric_spectra_from_psms",
    "score_dia_fragment_ratio_stability",
    "search_spectral_library",
    "sequence_checksum",
    "summarize_missing_values",
    "time",
    "validate_proteomics_input",
    "validate_ptm_site_coordinates",
    "validate_search_parameters",
    "validate_target_decoy_database",
    "write_theoretical_digest_bundle",
]
