# SPDX-License-Identifier: Apache-2.0
# Copyright © 2026 Bijan Mousavi

"""Canonical evidence-graph review surfaces."""

from __future__ import annotations

from bijux_proteomics.review.evidence_graph.evidence_chain_reconstruction import (
    EvidenceChainClaimKind,
    EvidenceChainNodeStep,
    EvidenceChainReport,
    EvidenceChainSourceRow,
    reconstruct_pathway_evidence_chain,
    reconstruct_protein_evidence_chain,
    reconstruct_ptm_site_evidence_chain,
    render_evidence_chain_tsv,
)
from bijux_proteomics.review.evidence_graph.evidence_graph import (
    ProteomicsEvidenceContextRef,
    ProteomicsEvidenceEdge,
    ProteomicsEvidenceEdgeKind,
    ProteomicsEvidenceGraph,
    ProteomicsEvidenceGraphBuilder,
    ProteomicsEvidenceGraphSummary,
    ProteomicsEvidenceNode,
    ProteomicsEvidenceNodeKind,
    ProteomicsEvidenceType,
    build_proteomics_evidence_graph,
)
from bijux_proteomics.review.evidence_graph.evidence_graph_confidence import (
    EvidenceGraphConfidenceEntry,
    EvidenceGraphConfidenceReport,
    EvidenceGraphConfidenceTier,
    propagate_evidence_graph_confidence,
    render_evidence_graph_confidence_tsv,
)
from bijux_proteomics.review.evidence_graph.evidence_graph_contradictions import (
    EvidenceGraphContradictionEntry,
    EvidenceGraphContradictionKind,
    EvidenceGraphContradictionReport,
    EvidenceGraphContradictionSeverity,
    detect_evidence_graph_contradictions,
    render_evidence_graph_contradictions_tsv,
)
from bijux_proteomics.review.evidence_graph.evidence_graph_downgrades import (
    EvidenceGraphDowngradeReason,
    EvidenceGraphFinalResultEntry,
    EvidenceGraphFinalResultReport,
    FinalClaimEvidenceTier,
    build_evidence_graph_final_result_table,
    render_evidence_graph_final_results_tsv,
)
from bijux_proteomics.review.evidence_graph.evidence_graph_export import (
    EvidenceGraphExportBundle,
    EvidenceGraphExportContextRef,
    EvidenceGraphExportEdge,
    EvidenceGraphExportNode,
    export_proteomics_evidence_graph,
    render_proteomics_evidence_graph_compact_json,
    render_proteomics_evidence_graph_edges_tsv,
    render_proteomics_evidence_graph_nodes_tsv,
)
from bijux_proteomics.review.evidence_graph.evidence_graph_queries import (
    EvidenceGraphPathStep,
    PathwaySupportProteinReport,
    PeptideSupportChainReport,
    ProteinEvidenceSummaryReport,
    PtmSiteEvidenceReport,
    RejectedEvidencePathReport,
    SampleQcReasonReport,
    query_pathway_support_proteins,
    query_peptide_support_chain,
    query_protein_evidence_summary,
    query_ptm_site_evidence,
    query_rejected_evidence_path,
    query_sample_qc_reasons,
    render_pathway_support_proteins_tsv,
    render_peptide_support_chain_tsv,
    render_protein_evidence_summary_tsv,
    render_ptm_site_evidence_tsv,
    render_rejected_evidence_path_tsv,
    render_sample_qc_reasons_tsv,
)
from bijux_proteomics.review.evidence_graph.evidence_graph_run_diff import (
    EvidenceGraphRunDiffCategory,
    EvidenceGraphRunDiffEntry,
    EvidenceGraphRunDiffKind,
    EvidenceGraphRunDiffReport,
    compare_evidence_graph_runs,
    render_evidence_graph_run_diff_tsv,
)
from bijux_proteomics.review.evidence_graph.lazy_evidence_graph import (
    LazyProteomicsEvidenceGraph,
    load_lazy_proteomics_evidence_graph,
)

__all__ = [
    "EvidenceChainClaimKind",
    "EvidenceChainNodeStep",
    "EvidenceChainReport",
    "EvidenceChainSourceRow",
    "EvidenceGraphConfidenceEntry",
    "EvidenceGraphConfidenceReport",
    "EvidenceGraphConfidenceTier",
    "EvidenceGraphContradictionEntry",
    "EvidenceGraphContradictionKind",
    "EvidenceGraphContradictionReport",
    "EvidenceGraphContradictionSeverity",
    "EvidenceGraphDowngradeReason",
    "EvidenceGraphExportBundle",
    "EvidenceGraphExportContextRef",
    "EvidenceGraphExportEdge",
    "EvidenceGraphExportNode",
    "EvidenceGraphFinalResultEntry",
    "EvidenceGraphFinalResultReport",
    "EvidenceGraphPathStep",
    "EvidenceGraphRunDiffCategory",
    "EvidenceGraphRunDiffEntry",
    "EvidenceGraphRunDiffKind",
    "EvidenceGraphRunDiffReport",
    "FinalClaimEvidenceTier",
    "LazyProteomicsEvidenceGraph",
    "PathwaySupportProteinReport",
    "PeptideSupportChainReport",
    "ProteinEvidenceSummaryReport",
    "ProteomicsEvidenceContextRef",
    "ProteomicsEvidenceEdge",
    "ProteomicsEvidenceEdgeKind",
    "ProteomicsEvidenceGraph",
    "ProteomicsEvidenceGraphBuilder",
    "ProteomicsEvidenceGraphSummary",
    "ProteomicsEvidenceNode",
    "ProteomicsEvidenceNodeKind",
    "ProteomicsEvidenceType",
    "PtmSiteEvidenceReport",
    "RejectedEvidencePathReport",
    "SampleQcReasonReport",
    "build_evidence_graph_final_result_table",
    "build_proteomics_evidence_graph",
    "compare_evidence_graph_runs",
    "detect_evidence_graph_contradictions",
    "export_proteomics_evidence_graph",
    "load_lazy_proteomics_evidence_graph",
    "propagate_evidence_graph_confidence",
    "query_pathway_support_proteins",
    "query_peptide_support_chain",
    "query_protein_evidence_summary",
    "query_ptm_site_evidence",
    "query_rejected_evidence_path",
    "query_sample_qc_reasons",
    "reconstruct_pathway_evidence_chain",
    "reconstruct_protein_evidence_chain",
    "reconstruct_ptm_site_evidence_chain",
    "render_evidence_chain_tsv",
    "render_evidence_graph_confidence_tsv",
    "render_evidence_graph_contradictions_tsv",
    "render_evidence_graph_final_results_tsv",
    "render_evidence_graph_run_diff_tsv",
    "render_pathway_support_proteins_tsv",
    "render_peptide_support_chain_tsv",
    "render_protein_evidence_summary_tsv",
    "render_proteomics_evidence_graph_compact_json",
    "render_proteomics_evidence_graph_edges_tsv",
    "render_proteomics_evidence_graph_nodes_tsv",
    "render_ptm_site_evidence_tsv",
    "render_rejected_evidence_path_tsv",
    "render_sample_qc_reasons_tsv",
]
