# SPDX-License-Identifier: Apache-2.0
# Copyright © 2026 Bijan Mousavi

from __future__ import annotations

from pathlib import Path

from bijux_proteomics_foundation.testing.generated_file_markers import (
    GeneratedFileMarkerKind,
    detect_generated_file_marker,
    detect_generated_file_marker_lines,
    is_marked_generated_file,
)


def test_generated_file_marker_support_detects_regenerated_headers(
    tmp_path: Path,
) -> None:
    path = tmp_path / "generated_report.py"
    path.write_text(
        "# Generated generated-report fixture.\n"
        "# Regenerate with: ./.venv/bin/python -m repo.generated.report\n\n"
        "VALUE = 1\n",
        encoding="utf-8",
    )

    marker = detect_generated_file_marker(path)

    assert marker is not None
    assert marker.kind == GeneratedFileMarkerKind.GENERATED_HEADER
    assert marker.regenerate_command == "./.venv/bin/python -m repo.generated.report"
    assert is_marked_generated_file(path) is True


def test_generated_file_marker_support_detects_ssot_notice_headers() -> None:
    marker = detect_generated_file_marker_lines(
        (
            "# SSOT NOTICE: This file is generated by standards sync.",
            "# Do not edit this generated copy directly.",
            "",
        )
    )

    assert marker is not None
    assert marker.kind == GeneratedFileMarkerKind.SSOT_NOTICE
    assert marker.regenerate_command is None


def test_generated_file_marker_support_rejects_incomplete_generated_headers() -> None:
    marker = detect_generated_file_marker_lines(
        (
            "# Generated generated-report fixture.",
            "VALUE = 1",
        )
    )

    assert marker is None
