# SPDX-License-Identifier: Apache-2.0
# Copyright © 2026 Bijan Mousavi

"""Modified-peptide, registry, and notation ownership surface."""

from __future__ import annotations

from bijux_proteomics.chemistry.contracts import (
    AppliedModification,
    ModificationLocalizationAdvisory,
    ModificationLocalizationCandidate,
    ModificationLocalizationState,
    ModificationLocalizationStatus,
    ModificationPosition,
    ModificationProvenance,
    ModificationRegistryDocument,
    ModificationRegistryValidationIssue,
    ModificationRegistryValidationReport,
    ModificationSiteValidationIssue,
    ModificationSiteValidationReport,
    ModifiedPeptideExportRecord,
    ParsedModifiedPeptide,
    StaticModification,
    VariableModification,
    VariableModificationEnumerationEntry,
    VariableModificationEnumerationReport,
    build_modification_localization_advisory,
    build_modification_registry,
    build_modified_peptide,
    build_modified_peptide_export_record,
    canonicalize_modified_peptide,
    enumerate_variable_modifications,
    export_modified_peptides_jsonl,
    export_modified_peptides_tsv,
    get_modification,
    load_modification_registry,
    modification_registry,
    parse_modified_peptide,
    validate_modification_registry,
    validate_modified_peptide_sites,
)
from bijux_proteomics.chemistry.modification_packs import (
    ModificationPack,
    ModificationPackEntry,
    ModificationPackRejectedRow,
    ModificationPackSummary,
    ModificationPackTerminus,
    ModificationPackValidationError,
    ModificationPackValidationReport,
    load_modification_pack,
)
from bijux_proteomics.chemistry.modification_registry import (
    ModificationRegistryRejection,
    ModificationRegistryResolutionMode,
    ModificationRegistryResolutionReport,
    ModificationRegistryResolutionSource,
    resolve_modification,
    resolve_modification_definition,
    resolve_modification_site,
)
from bijux_proteomics.chemistry.modification_resolution import (
    ModificationResolutionReport,
    ModificationResolutionSource,
    build_modification_resolution_report,
)
from bijux_proteomics.chemistry.modified_peptide_conflicts import (
    ModifiedPeptideConflictIssue,
    ModifiedPeptideConflictReport,
    validate_advanced_modified_peptide_conflicts,
)
from bijux_proteomics.chemistry.modified_peptide_parser import (
    ModifiedPeptideNotationDialect,
    ModifiedPeptideParseReview,
    SearchEngineModifiedPeptideDialect,
    SearchEngineModifiedPeptideReport,
    build_modified_peptide_parse_review,
    build_search_engine_modified_peptide_report,
    canonicalize_modified_peptide_notation,
    canonicalize_search_engine_modified_peptide,
    parse_modified_peptide_notation,
    parse_search_engine_modified_peptide,
)
from bijux_proteomics.chemistry.open_search_unknown_mod import (
    OpenSearchUnknownModificationReport,
    UnknownModificationHypothesis,
    build_open_search_unknown_mod_report,
)
from bijux_proteomics.chemistry.public_api import rebind_package_export

rebind_package_export(
    "bijux_proteomics.chemistry",
    "modification_registry",
    modification_registry,
)

__all__ = [
    "AppliedModification",
    "ModificationLocalizationAdvisory",
    "ModificationLocalizationCandidate",
    "ModificationLocalizationState",
    "ModificationLocalizationStatus",
    "ModificationPack",
    "ModificationPackEntry",
    "ModificationPackRejectedRow",
    "ModificationPackSummary",
    "ModificationPackTerminus",
    "ModificationPackValidationError",
    "ModificationPackValidationReport",
    "ModificationPosition",
    "ModificationProvenance",
    "ModificationRegistryDocument",
    "ModificationRegistryRejection",
    "ModificationRegistryResolutionMode",
    "ModificationRegistryResolutionReport",
    "ModificationRegistryResolutionSource",
    "ModificationRegistryValidationIssue",
    "ModificationRegistryValidationReport",
    "ModificationResolutionReport",
    "ModificationResolutionSource",
    "ModificationSiteValidationIssue",
    "ModificationSiteValidationReport",
    "ModifiedPeptideConflictIssue",
    "ModifiedPeptideConflictReport",
    "ModifiedPeptideExportRecord",
    "ModifiedPeptideNotationDialect",
    "ModifiedPeptideParseReview",
    "OpenSearchUnknownModificationReport",
    "ParsedModifiedPeptide",
    "SearchEngineModifiedPeptideDialect",
    "SearchEngineModifiedPeptideReport",
    "StaticModification",
    "UnknownModificationHypothesis",
    "VariableModification",
    "VariableModificationEnumerationEntry",
    "VariableModificationEnumerationReport",
    "build_modification_localization_advisory",
    "build_modification_registry",
    "build_modification_resolution_report",
    "build_modified_peptide",
    "build_modified_peptide_export_record",
    "build_modified_peptide_parse_review",
    "build_open_search_unknown_mod_report",
    "build_search_engine_modified_peptide_report",
    "canonicalize_modified_peptide",
    "canonicalize_modified_peptide_notation",
    "canonicalize_search_engine_modified_peptide",
    "enumerate_variable_modifications",
    "export_modified_peptides_jsonl",
    "export_modified_peptides_tsv",
    "get_modification",
    "load_modification_pack",
    "load_modification_registry",
    "modification_registry",
    "parse_modified_peptide",
    "parse_modified_peptide_notation",
    "parse_search_engine_modified_peptide",
    "resolve_modification",
    "resolve_modification_definition",
    "resolve_modification_site",
    "validate_advanced_modified_peptide_conflicts",
    "validate_modification_registry",
    "validate_modified_peptide_sites",
]
