# SPDX-License-Identifier: Apache-2.0
# Copyright © 2026 Bijan Mousavi

from __future__ import annotations

from bijux_proteomics.io.formats import ExperimentalDesignEntry
from bijux_proteomics.quantification import (
    MissingValueKind,
    Ms1FeatureRecord,
    QuantEntityLevel,
    QuantRollupMethod,
    build_label_free_intensity_table,
)
from bijux_proteomics.quantification.missingness import (
    classify_missingness,
    render_missingness_classification_tsv,
)


def test_classify_missingness_distinguishes_all_five_goal_labels() -> None:
    table = build_label_free_intensity_table(
        (
            Ms1FeatureRecord(
                feature_id="cs-001",
                sample_id="case-1",
                peptide="COND",
                canonical_peptide="COND",
                intensity=400.0,
                protein_refs=("P_CONDITION",),
                missing_value_kind=MissingValueKind.OBSERVED,
            ),
            Ms1FeatureRecord(
                feature_id="cs-002",
                sample_id="case-2",
                peptide="COND",
                canonical_peptide="COND",
                intensity=420.0,
                protein_refs=("P_CONDITION",),
                missing_value_kind=MissingValueKind.OBSERVED,
            ),
            Ms1FeatureRecord(
                feature_id="cs-003",
                sample_id="ctrl-1",
                peptide="COND",
                canonical_peptide="COND",
                intensity=None,
                protein_refs=("P_CONDITION",),
                missing_value_kind=MissingValueKind.NOT_OBSERVED,
            ),
            Ms1FeatureRecord(
                feature_id="cs-004",
                sample_id="ctrl-2",
                peptide="COND",
                canonical_peptide="COND",
                intensity=None,
                protein_refs=("P_CONDITION",),
                missing_value_kind=MissingValueKind.NOT_OBSERVED,
            ),
            Ms1FeatureRecord(
                feature_id="sf-001",
                sample_id="case-1",
                peptide="FAIL",
                canonical_peptide="FAIL",
                intensity=500.0,
                protein_refs=("P_SAMPLE_FAILURE",),
                missing_value_kind=MissingValueKind.OBSERVED,
            ),
            Ms1FeatureRecord(
                feature_id="sf-002",
                sample_id="case-2",
                peptide="FAIL",
                canonical_peptide="FAIL",
                intensity=None,
                protein_refs=("P_SAMPLE_FAILURE",),
                missing_value_kind=MissingValueKind.NOT_OBSERVED,
            ),
            Ms1FeatureRecord(
                feature_id="sf-003",
                sample_id="ctrl-1",
                peptide="FAIL",
                canonical_peptide="FAIL",
                intensity=510.0,
                protein_refs=("P_SAMPLE_FAILURE",),
                missing_value_kind=MissingValueKind.OBSERVED,
            ),
            Ms1FeatureRecord(
                feature_id="sf-004",
                sample_id="ctrl-2",
                peptide="FAIL",
                canonical_peptide="FAIL",
                intensity=520.0,
                protein_refs=("P_SAMPLE_FAILURE",),
                missing_value_kind=MissingValueKind.OBSERVED,
            ),
            Ms1FeatureRecord(
                feature_id="ic-001",
                sample_id="case-1",
                peptide="LOWA",
                canonical_peptide="LOWA",
                intensity=12.0,
                protein_refs=("P_INTENSITY",),
                missing_value_kind=MissingValueKind.OBSERVED,
            ),
            Ms1FeatureRecord(
                feature_id="ic-002",
                sample_id="case-2",
                peptide="LOWA",
                canonical_peptide="LOWA",
                intensity=None,
                protein_refs=("P_INTENSITY",),
                missing_value_kind=MissingValueKind.NOT_OBSERVED,
            ),
            Ms1FeatureRecord(
                feature_id="ic-003",
                sample_id="ctrl-1",
                peptide="LOWA",
                canonical_peptide="LOWA",
                intensity=10.0,
                protein_refs=("P_INTENSITY",),
                missing_value_kind=MissingValueKind.OBSERVED,
            ),
            Ms1FeatureRecord(
                feature_id="ic-004",
                sample_id="ctrl-2",
                peptide="LOWA",
                canonical_peptide="LOWA",
                intensity=None,
                protein_refs=("P_INTENSITY",),
                missing_value_kind=MissingValueKind.NOT_OBSERVED,
            ),
            Ms1FeatureRecord(
                feature_id="rand-001",
                sample_id="case-1",
                peptide="RAND",
                canonical_peptide="RAND",
                intensity=200.0,
                protein_refs=("P_RANDOM",),
                missing_value_kind=MissingValueKind.OBSERVED,
            ),
            Ms1FeatureRecord(
                feature_id="rand-002",
                sample_id="case-2",
                peptide="RAND",
                canonical_peptide="RAND",
                intensity=None,
                protein_refs=("P_RANDOM",),
                missing_value_kind=MissingValueKind.NOT_OBSERVED,
            ),
            Ms1FeatureRecord(
                feature_id="rand-003",
                sample_id="ctrl-1",
                peptide="RAND",
                canonical_peptide="RAND",
                intensity=210.0,
                protein_refs=("P_RANDOM",),
                missing_value_kind=MissingValueKind.OBSERVED,
            ),
            Ms1FeatureRecord(
                feature_id="rand-004",
                sample_id="ctrl-2",
                peptide="RAND",
                canonical_peptide="RAND",
                intensity=None,
                protein_refs=("P_RANDOM",),
                missing_value_kind=MissingValueKind.NOT_OBSERVED,
            ),
            Ms1FeatureRecord(
                feature_id="struct-001",
                sample_id="case-1",
                peptide="NONE",
                canonical_peptide="NONE",
                intensity=None,
                protein_refs=("P_STRUCTURAL",),
                missing_value_kind=MissingValueKind.NOT_OBSERVED,
            ),
            Ms1FeatureRecord(
                feature_id="struct-002",
                sample_id="case-2",
                peptide="NONE",
                canonical_peptide="NONE",
                intensity=None,
                protein_refs=("P_STRUCTURAL",),
                missing_value_kind=MissingValueKind.NOT_OBSERVED,
            ),
            Ms1FeatureRecord(
                feature_id="struct-003",
                sample_id="ctrl-1",
                peptide="NONE",
                canonical_peptide="NONE",
                intensity=None,
                protein_refs=("P_STRUCTURAL",),
                missing_value_kind=MissingValueKind.NOT_OBSERVED,
            ),
            Ms1FeatureRecord(
                feature_id="struct-004",
                sample_id="ctrl-2",
                peptide="NONE",
                canonical_peptide="NONE",
                intensity=None,
                protein_refs=("P_STRUCTURAL",),
                missing_value_kind=MissingValueKind.NOT_OBSERVED,
            ),
            Ms1FeatureRecord(
                feature_id="anchor-001",
                sample_id="case-1",
                peptide="HIGH",
                canonical_peptide="HIGH",
                intensity=2000.0,
                protein_refs=("P_HIGH",),
                missing_value_kind=MissingValueKind.OBSERVED,
            ),
            Ms1FeatureRecord(
                feature_id="anchor-002",
                sample_id="case-2",
                peptide="HIGH",
                canonical_peptide="HIGH",
                intensity=2050.0,
                protein_refs=("P_HIGH",),
                missing_value_kind=MissingValueKind.OBSERVED,
            ),
            Ms1FeatureRecord(
                feature_id="anchor-003",
                sample_id="ctrl-1",
                peptide="HIGH",
                canonical_peptide="HIGH",
                intensity=1980.0,
                protein_refs=("P_HIGH",),
                missing_value_kind=MissingValueKind.OBSERVED,
            ),
            Ms1FeatureRecord(
                feature_id="anchor-004",
                sample_id="ctrl-2",
                peptide="HIGH",
                canonical_peptide="HIGH",
                intensity=2020.0,
                protein_refs=("P_HIGH",),
                missing_value_kind=MissingValueKind.OBSERVED,
            ),
            Ms1FeatureRecord(
                feature_id="fail-anchor-001",
                sample_id="case-1",
                peptide="FAILALL",
                canonical_peptide="FAILALL",
                intensity=300.0,
                protein_refs=("P_FAIL_ANCHOR_1",),
                missing_value_kind=MissingValueKind.OBSERVED,
            ),
            Ms1FeatureRecord(
                feature_id="fail-anchor-002",
                sample_id="case-2",
                peptide="FAILALL",
                canonical_peptide="FAILALL",
                intensity=None,
                protein_refs=("P_FAIL_ANCHOR_1",),
                missing_value_kind=MissingValueKind.NOT_OBSERVED,
            ),
            Ms1FeatureRecord(
                feature_id="fail-anchor-003",
                sample_id="ctrl-1",
                peptide="FAILALL",
                canonical_peptide="FAILALL",
                intensity=310.0,
                protein_refs=("P_FAIL_ANCHOR_1",),
                missing_value_kind=MissingValueKind.OBSERVED,
            ),
            Ms1FeatureRecord(
                feature_id="fail-anchor-004",
                sample_id="ctrl-2",
                peptide="FAILALL",
                canonical_peptide="FAILALL",
                intensity=320.0,
                protein_refs=("P_FAIL_ANCHOR_1",),
                missing_value_kind=MissingValueKind.OBSERVED,
            ),
            Ms1FeatureRecord(
                feature_id="fail-anchor-005",
                sample_id="case-1",
                peptide="FAILALL2",
                canonical_peptide="FAILALL2",
                intensity=330.0,
                protein_refs=("P_FAIL_ANCHOR_2",),
                missing_value_kind=MissingValueKind.OBSERVED,
            ),
            Ms1FeatureRecord(
                feature_id="fail-anchor-006",
                sample_id="case-2",
                peptide="FAILALL2",
                canonical_peptide="FAILALL2",
                intensity=None,
                protein_refs=("P_FAIL_ANCHOR_2",),
                missing_value_kind=MissingValueKind.NOT_OBSERVED,
            ),
            Ms1FeatureRecord(
                feature_id="fail-anchor-007",
                sample_id="ctrl-1",
                peptide="FAILALL2",
                canonical_peptide="FAILALL2",
                intensity=340.0,
                protein_refs=("P_FAIL_ANCHOR_2",),
                missing_value_kind=MissingValueKind.OBSERVED,
            ),
            Ms1FeatureRecord(
                feature_id="fail-anchor-008",
                sample_id="ctrl-2",
                peptide="FAILALL2",
                canonical_peptide="FAILALL2",
                intensity=350.0,
                protein_refs=("P_FAIL_ANCHOR_2",),
                missing_value_kind=MissingValueKind.OBSERVED,
            ),
        ),
        entity_level=QuantEntityLevel.PROTEIN,
        aggregation_method=QuantRollupMethod.SUM,
    )
    design = _design()

    report = classify_missingness(table, design)
    rendered = render_missingness_classification_tsv(report)
    labels = {entry.entity_id: entry.label.value for entry in report.entries}

    assert "case-2" in report.failed_sample_ids
    assert labels["P_CONDITION"] == "condition_specific"
    assert labels["P_SAMPLE_FAILURE"] == "sample_failure"
    assert labels["P_INTENSITY"] == "intensity_censored"
    assert labels["P_RANDOM"] == "random"
    assert labels["P_STRUCTURAL"] == "structural_absence"
    assert (
        "entity_id\tlabel\tobserved_sample_count\tmissing_sample_count\tmissing_fraction"
        in rendered
    )


def _design() -> tuple[ExperimentalDesignEntry, ...]:
    return (
        ExperimentalDesignEntry(
            sample_id="case-1",
            condition="case",
            replicate=1,
            fraction=1,
            spectra_file="case-1.mzml",
        ),
        ExperimentalDesignEntry(
            sample_id="case-2",
            condition="case",
            replicate=2,
            fraction=1,
            spectra_file="case-2.mzml",
        ),
        ExperimentalDesignEntry(
            sample_id="ctrl-1",
            condition="control",
            replicate=1,
            fraction=1,
            spectra_file="ctrl-1.mzml",
        ),
        ExperimentalDesignEntry(
            sample_id="ctrl-2",
            condition="control",
            replicate=2,
            fraction=1,
            spectra_file="ctrl-2.mzml",
        ),
    )
