# SPDX-License-Identifier: Apache-2.0
# Copyright © 2026 Bijan Mousavi

"""Peptide chemistry contracts and governed services."""

from __future__ import annotations

from bijux_proteomics.chemistry.contracts.fragment_ions import (
    calculate_fragment_ions,
    validate_modified_peptide_fragment_ions,
)
from bijux_proteomics.chemistry.contracts.mass_projection import (
    approximate_peptide_isotope_envelope,
    build_peptide_charge_state,
    calculate_average_peptide_mass,
    calculate_modified_peptide_mass,
    calculate_monoisotopic_peptide_mass,
    calculate_peptide_mz,
)
from bijux_proteomics.chemistry.contracts.models import (
    AppliedModification,
    FragmentIon,
    FragmentIonSeries,
    FragmentIonShiftValidationEntry,
    FragmentIonShiftValidationReport,
    IsotopeEnvelopeStatus,
    IsotopePeak,
    IsotopicLabelingPolicy,
    MassType,
    ModificationLocalizationAdvisory,
    ModificationLocalizationCandidate,
    ModificationLocalizationState,
    ModificationLocalizationStatus,
    ModificationPosition,
    ModificationProvenance,
    ModificationRegistryDocument,
    ModificationRegistryValidationIssue,
    ModificationRegistryValidationReport,
    ModificationSiteValidationIssue,
    ModificationSiteValidationReport,
    ModifiedPeptideExportRecord,
    NeutralLoss,
    ParsedModifiedPeptide,
    PeptideChargeState,
    PeptideIsotopeEnvelope,
    StaticModification,
    VariableModification,
    VariableModificationEnumerationEntry,
    VariableModificationEnumerationReport,
)
from bijux_proteomics.chemistry.contracts.modified_peptides import (
    build_modified_peptide,
    build_modified_peptide_export_record,
    build_modification_localization_advisory,
    canonicalize_modified_peptide,
    enumerate_variable_modifications,
    export_modified_peptides_jsonl,
    export_modified_peptides_tsv,
    parse_modified_peptide,
    validate_modified_peptide_sites,
)
from bijux_proteomics.chemistry.contracts.registry_access import (
    build_modification_registry,
    get_modification,
    load_modification_registry,
    modification_registry,
    validate_modification_registry,
)

__all__ = [
    "AppliedModification",
    "FragmentIon",
    "FragmentIonSeries",
    "FragmentIonShiftValidationEntry",
    "FragmentIonShiftValidationReport",
    "IsotopeEnvelopeStatus",
    "IsotopePeak",
    "IsotopicLabelingPolicy",
    "MassType",
    "ModificationLocalizationAdvisory",
    "ModificationLocalizationCandidate",
    "ModificationLocalizationState",
    "ModificationLocalizationStatus",
    "ModificationPosition",
    "ModificationProvenance",
    "ModificationRegistryDocument",
    "ModificationRegistryValidationIssue",
    "ModificationRegistryValidationReport",
    "ModificationSiteValidationIssue",
    "ModificationSiteValidationReport",
    "ModifiedPeptideExportRecord",
    "NeutralLoss",
    "ParsedModifiedPeptide",
    "PeptideChargeState",
    "PeptideIsotopeEnvelope",
    "StaticModification",
    "VariableModification",
    "VariableModificationEnumerationEntry",
    "VariableModificationEnumerationReport",
    "approximate_peptide_isotope_envelope",
    "build_modification_localization_advisory",
    "build_modification_registry",
    "build_modified_peptide",
    "build_modified_peptide_export_record",
    "build_peptide_charge_state",
    "calculate_average_peptide_mass",
    "calculate_fragment_ions",
    "calculate_modified_peptide_mass",
    "calculate_monoisotopic_peptide_mass",
    "calculate_peptide_mz",
    "canonicalize_modified_peptide",
    "enumerate_variable_modifications",
    "export_modified_peptides_jsonl",
    "export_modified_peptides_tsv",
    "get_modification",
    "load_modification_registry",
    "modification_registry",
    "parse_modified_peptide",
    "validate_modification_registry",
    "validate_modified_peptide_fragment_ions",
    "validate_modified_peptide_sites",
]
