include $(ROOT_MAKE_DIR)/bijux-py/package/python.mk

PYTHON ?= python3.11
ENABLE_CODESPELL ?= 1
ENABLE_RADON ?= 1
ENABLE_PYDOCSTYLE ?= 0
ENABLE_PYTYPE ?= 0
RUFF_CHECK_FIX ?= 1
QUALITY_VULTURE_MIN_CONFIDENCE ?= 80
SECURITY_IGNORE_IDS ?= PYSEC-2022-42969
API_MODE ?= contract
API_BASE_PATH ?=
BUILD_CHECK_DISTS ?= 1
BUILD_CLEAN_PATHS ?= $(COMMON_BUILD_CLEAN_PATHS)
BUILD_CLEAN_PYCACHE ?= 1
PACKAGE_BOOTSTRAP_TARGETS ?= lint quality security api
PACKAGE_CLEAN_EXTRA_PATHS ?= demo .tmp_home \
	$(COMMON_API_TEMP_CLEAN_PATHS) \
	docs/reference usage_test usage_test_artifacts \
	$(COMMON_CONFIG_CACHE_CLEAN_PATHS)
PACKAGE_ALL_TARGETS ?= clean install test lint quality security api build sbom
PACKAGE_DEFINE_ALL_PARALLEL ?= 1
