PACKAGE_IMPORT_NAME ?=
PACKAGE_SOURCE_DIR ?= $(if $(strip $(PACKAGE_IMPORT_NAME)),src/$(PACKAGE_IMPORT_NAME),src)
PACKAGE_TEST_DIRS ?= tests
PACKAGE_LINT_EXTRA_DIRS ?=
PACKAGE_CLEAN_EXTRA_PATHS ?=

LINT_DIRS ?= $(strip $(PACKAGE_SOURCE_DIR) $(PACKAGE_TEST_DIRS) $(PACKAGE_LINT_EXTRA_DIRS))
INTERROGATE_PATHS ?= $(PACKAGE_SOURCE_DIR)
QUALITY_PATHS ?= $(PACKAGE_SOURCE_DIR)
QUALITY_VULTURE_MIN_CONFIDENCE ?= 80
SECURITY_PATHS ?= $(PACKAGE_SOURCE_DIR)
PUBLISH_UPLOAD_ENABLED ?= 0
BUILD_CLEAN_PATHS ?= $(COMMON_BUILD_CLEAN_PATHS)
PACKAGE_CLEAN_PATHS ?= $(strip $(COMMON_PYTHON_CLEAN_PATHS) $(COMMON_ARTIFACT_CLEAN_PATHS) $(PACKAGE_CLEAN_EXTRA_PATHS))
