# SPDX-License-Identifier: Apache-2.0
# Copyright © 2025 Bijan Mousavi

"""Evidence models for Bijux Proteomics."""

from __future__ import annotations

from bijux_proteomics_knowledge.adapters import (
    AssayResultIngestionAdapter,
    IngestionReport,
    LiteratureIngestionAdapter,
    ManualEvidenceNote,
    ManualEvidenceNoteAdapter,
    NormalizedEvidenceInput,
    StructureAnnotationIngestionAdapter,
    attach_evidence_inputs,
    ingest_inputs_with_report,
    attach_manual_notes,
)
from bijux_proteomics_knowledge.claims import (
    ClaimType,
    ClaimPolarity,
    ClaimResolutionState,
    ClaimStatus,
    DecisionLineage,
    EvidenceClaim,
    build_claim,
    close_claim,
    build_decision_lineage,
    link_evidence_to_claim,
)
from bijux_proteomics_foundation import DocumentSchema, JsonModel
from bijux_proteomics_knowledge.graph import (
    EvidenceEdge,
    EvidenceGraph,
    EvidenceNode,
    EvidenceNodeType,
    build_evidence_graph,
)
from bijux_proteomics_knowledge.repositories import (
    ClaimResolutionRecord,
    ClaimResolutionRepository,
    EvidenceBundleRepository,
    EvidenceClaimRepository,
    EvidenceRecordRepository,
)
from bijux_proteomics_knowledge.resolution import (
    ConflictResolution,
    ResolutionAction,
    ResolutionPolicy,
    resolve_conflicts,
)
from bijux_proteomics_knowledge.evidence import (
    BundleTrustReport,
    DecisionReadiness,
    EvidenceConflict,
    EvidenceCoverage,
    EvidenceBundle,
    ConflictPolicy,
    EvidenceExtractionMethod,
    EvidenceRefreshNeed,
    EvidenceRefreshPriority,
    EvidenceKind,
    EvidenceOrigin,
    EvidenceRecord,
    EvidenceSourceType,
    EvidenceStrength,
    EvidenceQualityDecomposition,
    ContextCompatibilityReport,
    EvidenceTriangulationReport,
    QuantitativeSupport,
    TrustPolicy,
    BundleFreshnessReport,
    assess_decision_readiness,
    compute_bundle_trust,
    default_conflict_policy,
    default_trust_policy,
    coverage_report,
    deduplicate_records,
    decompose_evidence_quality,
    assess_context_compatibility,
    triangulate_evidence,
    evidence_gaps,
    flag_conflicting_evidence,
    plan_evidence_refresh,
    score_evidence_record,
    aging_records,
    stale_records,
    summarize_bundle,
    weight_source_type,
)

__all__ = [
    "AssayResultIngestionAdapter",
    "BundleTrustReport",
    "ClaimPolarity",
    "ClaimType",
    "ClaimResolutionState",
    "ClaimStatus",
    "ConflictResolution",
    "ConflictPolicy",
    "DecisionReadiness",
    "DecisionLineage",
    "BundleFreshnessReport",
    "EvidenceClaim",
    "EvidenceConflict",
    "EvidenceCoverage",
    "EvidenceBundle",
    "EvidenceEdge",
    "EvidenceGraph",
    "EvidenceExtractionMethod",
    "EvidenceRefreshNeed",
    "EvidenceRefreshPriority",
    "EvidenceKind",
    "EvidenceNode",
    "EvidenceNodeType",
    "EvidenceOrigin",
    "EvidenceRecord",
    "EvidenceQualityDecomposition",
    "ContextCompatibilityReport",
    "EvidenceTriangulationReport",
    "EvidenceSourceType",
    "EvidenceStrength",
    "QuantitativeSupport",
    "TrustPolicy",
    "assess_decision_readiness",
    "attach_evidence_inputs",
    "build_evidence_graph",
    "build_claim",
    "close_claim",
    "link_evidence_to_claim",
    "build_decision_lineage",
    "compute_bundle_trust",
    "coverage_report",
    "default_conflict_policy",
    "default_trust_policy",
    "deduplicate_records",
    "decompose_evidence_quality",
    "assess_context_compatibility",
    "triangulate_evidence",
    "evidence_gaps",
    "flag_conflicting_evidence",
    "plan_evidence_refresh",
    "score_evidence_record",
    "aging_records",
    "stale_records",
    "summarize_bundle",
    "weight_source_type",
    "JsonModel",
    "IngestionReport",
    "LiteratureIngestionAdapter",
    "ManualEvidenceNote",
    "ManualEvidenceNoteAdapter",
    "NormalizedEvidenceInput",
    "DocumentSchema",
    "EvidenceBundleRepository",
    "EvidenceClaimRepository",
    "ClaimResolutionRecord",
    "ClaimResolutionRepository",
    "EvidenceRecordRepository",
    "ResolutionAction",
    "ResolutionPolicy",
    "resolve_conflicts",
    "StructureAnnotationIngestionAdapter",
    "attach_manual_notes",
    "ingest_inputs_with_report",
]
