# SPDX-License-Identifier: Apache-2.0
# Copyright © 2025 Bijan Mousavi
# ruff: noqa: F401,F403,F405

"""Review, sequence, and study-domain imports shared by CLI command modules."""

from __future__ import annotations

from bijux_proteomics.lab.protocol_consistency import (
    build_protocol_consistency_report,
    render_protocol_consistency_tsv,
)
from bijux_proteomics.lab.protocol_context import (
    build_lab_protocol_interpretation_profile,
    parse_lab_protocol_context_table,
    require_single_lab_protocol_context,
)
from bijux_proteomics.lab.qc import (
    QcEvidenceInputFile,
    build_batch_qc_assessment,
    build_instrument_batch_qc_report,
    build_lcms_run_qc_report,
    build_performance_snapshot,
    build_protocol_aware_qc_threshold_policy,
    build_qc_evidence_manifest,
    build_run_qc_assessment,
    default_qc_threshold_policy,
    load_qc_threshold_policy,
    render_qc_assessment_html,
    render_qc_assessment_tsv,
)
from bijux_proteomics.review import (
    BiomarkerCandidateKind,
    BiomarkerCandidateRankingInput,
    FailureExplanationRequest,
    ResultExplanationKind,
    ResultExplanationRequest,
    ResultQueryKind,
    ResultQueryRequest,
    VolcanoReviewPolicy,
    build_analysis_recommendation_report_from_artifacts,
    build_belief_audit_report_from_artifacts,
    build_biomarker_candidate_ranking_report,
    build_compact_result_summary_report_from_artifacts,
    build_dia_volcano_review,
    build_failure_explanation_report,
    build_label_based_volcano_review,
    build_ptm_volcano_review,
    build_result_explanation_report_from_artifacts,
    build_result_query_report_from_artifacts,
    export_volcano_review_html,
    export_volcano_review_json,
    export_volcano_review_svg,
    format_failure_explanation_for_cli,
    render_analysis_recommendation_summary_tsv,
    render_analysis_recommendation_tsv,
    render_belief_audit_html,
    render_belief_audit_summary_tsv,
    render_belief_audit_tsv,
    render_biomarker_candidate_ranking_summary_tsv,
    render_biomarker_candidate_ranking_tsv,
    render_compact_result_summary_entry_tsv,
    render_compact_result_summary_markdown,
    render_compact_result_summary_overview_tsv,
    render_failure_explanation_summary_tsv,
    render_failure_explanation_tsv,
    render_result_explanation_evidence_tsv,
    render_result_explanation_summary_tsv,
    render_result_explanation_tsv,
    render_result_query_answer_tsv,
    render_result_query_evidence_tsv,
    render_result_query_summary_tsv,
)
from bijux_proteomics.sequences.contaminant_database import (
    append_contaminant_database,
)
from bijux_proteomics.sequences.fasta import (
    DecoyGenerationMode,
    DuplicateAccessionPolicy,
    FastaParseMode,
    FastaParseReport,
    build_decoy_generation_manifest,
    build_decoy_generation_report,
    build_fasta_provenance_manifest,
    build_fasta_stats,
    deduplicate_fasta_records,
    filter_fasta_records,
    generate_decoy_records,
    parse_fasta_document,
    render_records_fasta,
    sequence_checksum,
    validate_target_decoy_database,
)
from bijux_proteomics.sequences.fasta import NormalizedProteinRecord
from bijux_proteomics.sequences.fasta_profile import (
    FastaDatabaseProfile,
    build_fasta_database_profile,
    render_fasta_profile_invalid_sequence_tsv,
    render_fasta_profile_length_distribution_tsv,
    render_fasta_profile_organism_distribution_tsv,
    render_fasta_profile_summary_tsv,
)
from bijux_proteomics.sequences.peptide_chemical_liability import (
    PeptideChemicalLiabilityTier,
)
from bijux_proteomics.sequences.peptide_detectability import (
    PeptideDetectabilityTier,
    build_peptide_detectability_report,
    render_peptide_detectability_tsv,
)
from bijux_proteomics.sequences.peptide_properties import (
    build_peptide_property_report,
)
from bijux_proteomics.sequences.peptide_uniqueness_index import (
    PeptideUniquenessClass,
)
from bijux_proteomics.sequences.theoretical_digest import (
    build_theoretical_digest_bundle,
    write_theoretical_digest_bundle,
)
from bijux_proteomics.sequences.digestion import (
    PeptideDigestionMode,
    ProteaseRule,
    build_digest_manifest,
    digest_protein_records,
    export_peptide_protein_table_tsv,
    export_peptides_fasta,
    export_peptides_jsonl,
    export_peptides_parquet,
    export_peptides_tsv,
    peptide_export_fingerprint,
    resolve_protease_rule,
)
from bijux_proteomics.sequences.peptide_uniqueness_audit import (
    build_peptide_database_lookup_report,
)
from bijux_proteomics.study.experiment_feasibility import (
    build_experiment_feasibility_report,
    render_experiment_feasibility_group_sizes_tsv,
    render_experiment_feasibility_invalid_contrasts_tsv,
    render_experiment_feasibility_missing_metadata_tsv,
    render_experiment_feasibility_model_support_tsv,
    render_experiment_feasibility_valid_contrasts_tsv,
)
from bijux_proteomics.study.sample_sheet_repairs import (
    build_sample_sheet_repair_suggestion_report,
    export_sample_sheet_repair_suggestions_tsv,
)

__all__ = [
    "BiomarkerCandidateKind",
    "BiomarkerCandidateRankingInput",
    "DecoyGenerationMode",
    "DuplicateAccessionPolicy",
    "FailureExplanationRequest",
    "FastaDatabaseProfile",
    "FastaParseMode",
    "FastaParseReport",
    "NormalizedProteinRecord",
    "PeptideChemicalLiabilityTier",
    "PeptideDetectabilityTier",
    "PeptideDigestionMode",
    "PeptideUniquenessClass",
    "ProteaseRule",
    "QcEvidenceInputFile",
    "ResultExplanationKind",
    "ResultExplanationRequest",
    "ResultQueryKind",
    "ResultQueryRequest",
    "VolcanoReviewPolicy",
    "append_contaminant_database",
    "build_analysis_recommendation_report_from_artifacts",
    "build_batch_qc_assessment",
    "build_belief_audit_report_from_artifacts",
    "build_biomarker_candidate_ranking_report",
    "build_compact_result_summary_report_from_artifacts",
    "build_decoy_generation_manifest",
    "build_decoy_generation_report",
    "build_dia_volcano_review",
    "build_digest_manifest",
    "build_experiment_feasibility_report",
    "build_failure_explanation_report",
    "build_fasta_database_profile",
    "build_fasta_provenance_manifest",
    "build_fasta_stats",
    "build_instrument_batch_qc_report",
    "build_lab_protocol_interpretation_profile",
    "build_label_based_volcano_review",
    "build_lcms_run_qc_report",
    "build_peptide_database_lookup_report",
    "build_peptide_detectability_report",
    "build_peptide_property_report",
    "build_performance_snapshot",
    "build_protocol_aware_qc_threshold_policy",
    "build_protocol_consistency_report",
    "build_ptm_volcano_review",
    "build_qc_evidence_manifest",
    "build_result_explanation_report_from_artifacts",
    "build_result_query_report_from_artifacts",
    "build_run_qc_assessment",
    "build_sample_sheet_repair_suggestion_report",
    "build_theoretical_digest_bundle",
    "deduplicate_fasta_records",
    "default_qc_threshold_policy",
    "digest_protein_records",
    "export_peptide_protein_table_tsv",
    "export_peptides_fasta",
    "export_peptides_jsonl",
    "export_peptides_parquet",
    "export_peptides_tsv",
    "export_sample_sheet_repair_suggestions_tsv",
    "export_volcano_review_html",
    "export_volcano_review_json",
    "export_volcano_review_svg",
    "filter_fasta_records",
    "format_failure_explanation_for_cli",
    "generate_decoy_records",
    "load_qc_threshold_policy",
    "parse_fasta_document",
    "parse_lab_protocol_context_table",
    "peptide_export_fingerprint",
    "render_analysis_recommendation_summary_tsv",
    "render_analysis_recommendation_tsv",
    "render_belief_audit_html",
    "render_belief_audit_summary_tsv",
    "render_belief_audit_tsv",
    "render_biomarker_candidate_ranking_summary_tsv",
    "render_biomarker_candidate_ranking_tsv",
    "render_compact_result_summary_entry_tsv",
    "render_compact_result_summary_markdown",
    "render_compact_result_summary_overview_tsv",
    "render_experiment_feasibility_group_sizes_tsv",
    "render_experiment_feasibility_invalid_contrasts_tsv",
    "render_experiment_feasibility_missing_metadata_tsv",
    "render_experiment_feasibility_model_support_tsv",
    "render_experiment_feasibility_valid_contrasts_tsv",
    "render_failure_explanation_summary_tsv",
    "render_failure_explanation_tsv",
    "render_fasta_profile_invalid_sequence_tsv",
    "render_fasta_profile_length_distribution_tsv",
    "render_fasta_profile_organism_distribution_tsv",
    "render_fasta_profile_summary_tsv",
    "render_peptide_detectability_tsv",
    "render_protocol_consistency_tsv",
    "render_qc_assessment_html",
    "render_qc_assessment_tsv",
    "render_records_fasta",
    "render_result_explanation_evidence_tsv",
    "render_result_explanation_summary_tsv",
    "render_result_explanation_tsv",
    "render_result_query_answer_tsv",
    "render_result_query_evidence_tsv",
    "render_result_query_summary_tsv",
    "require_single_lab_protocol_context",
    "resolve_protease_rule",
    "sequence_checksum",
    "validate_target_decoy_database",
    "write_theoretical_digest_bundle",
]
