# SPDX-License-Identifier: Apache-2.0
# Copyright © 2025 Bijan Mousavi
# ruff: noqa: F401,F403,F405

"""Workflow-domain imports shared by CLI command modules."""

from __future__ import annotations

from bijux_proteomics.workflow import (
    BiologicalResultSelectionPolicy,
    DiaDifferentialSourceKind,
    ProteomicsRunEngine,
    build_diann_benchmark_report,
    build_maxquant_benchmark_report,
    build_proteomics_run_bundle,
    build_dia_differential_volcano_plot,
    build_diann_differential_analysis_report,
    build_diann_vs_dda_psm_comparison_report,
    build_label_based_differential_volcano_plot,
    build_silac_differential_analysis_report,
    build_tmt_differential_analysis_report,
    build_spectronaut_differential_analysis_report,
    export_dia_differential_matrix_tsv,
    export_dia_differential_qc_summary_tsv,
    export_dia_differential_results_tsv,
    export_dia_differential_volcano_plot_tsv,
    export_dia_normalization_balance_plot_tsv,
    export_label_based_differential_matrix_tsv,
    export_label_based_differential_results_tsv,
    export_label_based_differential_volcano_plot_tsv,
    export_label_based_normalization_balance_plot_tsv,
    render_diann_benchmark_count_comparisons_tsv,
    render_diann_benchmark_protein_quantities_tsv,
    render_diann_benchmark_summary_tsv,
    render_maxquant_benchmark_summary_tsv,
    render_maxquant_differential_comparison_tsv,
    render_maxquant_filtering_comparison_tsv,
    render_maxquant_lfq_comparison_tsv,
    render_maxquant_protein_identity_comparison_tsv,
    render_proteomics_run_summary_tsv,
    render_dia_dda_comparison_summary_tsv,
    render_dia_dda_conflicting_evidence_tsv,
    render_dia_dda_differential_comparison_tsv,
    render_dia_dda_exclusive_evidence_tsv,
    render_dia_dda_peptide_overlap_tsv,
    render_dia_dda_protein_overlap_tsv,
    render_dia_dda_shared_intensity_correlation_tsv,
    render_integrated_scientific_report_sentences_tsv,
    render_integrated_scientific_report_summary_tsv,
    render_public_benchmark_suite_failures_tsv,
    render_public_benchmark_suite_signal_assessments_tsv,
    render_public_benchmark_suite_summary_tsv,
    render_cross_study_evidence_card_summary_tsv,
    render_cross_study_evidence_card_tsv,
    render_cross_study_evidence_dataset_tsv,
    render_public_dataset_combined_summary_tsv,
    render_public_dataset_dataset_summary_tsv,
    render_public_dataset_effect_comparison_tsv,
    render_public_dataset_failure_tsv,
    render_public_dataset_meta_analysis_tsv,
    render_public_dataset_pathway_comparison_tsv,
    render_scale_demo_stage_metrics_tsv,
    render_scale_demo_summary_tsv,
    render_scale_demo_validation_tsv,
    render_surprising_demo_interrogation_answers_tsv,
    render_surprising_demo_interrogation_summary_tsv,
    render_surprising_demo_findings_tsv,
    render_surprising_demo_summary_tsv,
    render_trust_bundle_run_summary_tsv,
    ScaleDemoConfig,
    SurprisingDemoConfig,
    SurprisingDemoQueryKind,
    SurprisingDemoQueryRequest,
    build_public_dataset_evidence_card_report,
    build_public_benchmark_trust_bundle,
    build_public_dataset_comparison_report,
    run_scale_demo,
    build_surprising_demo_example_requests,
    build_surprising_demo_interrogation_report,
    build_interactive_result_comparison_from_artifacts,
    build_interactive_result_bundle_from_artifacts,
    build_integrated_scientific_report,
    build_result_manifest_from_artifacts,
    render_interactive_result_comparison_pathway_tsv,
    render_interactive_result_comparison_protein_tsv,
    render_interactive_result_comparison_ptm_site_tsv,
    render_interactive_result_comparison_qc_tsv,
    render_interactive_result_comparison_summary_tsv,
    render_interactive_result_bundle_summary_tsv,
    render_result_manifest_command_tsv,
    render_result_manifest_file_tsv,
    render_result_manifest_input_tsv,
    render_result_manifest_summary_tsv,
    render_result_manifest_warning_tsv,
    build_result_search_index_from_artifacts,
    render_result_search_hit_tsv,
    render_result_search_summary_tsv,
    search_result_index,
    ensure_surprising_demo_outputs,
    resolve_public_benchmark_path,
    resolve_public_benchmark_root,
    run_surprising_demo,
    run_public_benchmark_descriptor,
    run_public_benchmark_descriptor_suite,
    write_proteomics_run_bundle,
)
from bijux_proteomics.workflow.pipelines.orchestrator import (
    DdaWorkflowConfig,
    DiannWorkflowConfig,
    LabelFreeWorkflowConfig,
    MaxquantWorkflowConfig,
    PtmWorkflowConfig,
    SilacWorkflowConfig,
    TargetedWorkflowConfig,
    TargetedWorkflowStage,
    TmtWorkflowConfig,
    WorkflowMode,
    run_proteomics_workflow as _orchestrator_run_proteomics_workflow,
)


def run_proteomics_workflow(*args, **kwargs):
    """Delegate workflow orchestration through the canonical scientific owner."""

    return _orchestrator_run_proteomics_workflow(*args, **kwargs)



__all__ = [name for name in globals() if not name.startswith("__")]
