# SPDX-License-Identifier: Apache-2.0
# Copyright © 2025 Bijan Mousavi

"""Protein intelligence helpers for Bijux Proteomics."""

from __future__ import annotations

from importlib import import_module
from typing import Any

_INTELLIGENCE_EXPORT_GROUPS = {
    "bijux_proteomics_intelligence.briefs": [
        "CandidateAssessment",
        "CandidateExplainabilitySummary",
        "CandidateRanking",
        "CandidateRankingProvenanceReport",
        "CandidateScoreBreakdown",
        "CriterionSatisfactionItem",
        "CriterionSatisfactionVector",
        "DesignBrief",
        "LiabilityFlag",
        "LiabilityFocusSummary",
        "MetricCoverageSummary",
        "NoveltyDiversitySummary",
        "OptimizationAxis",
        "RankedCandidate",
        "RankingAssumptionScenario",
        "RankingDiagnostics",
        "RankingDriftItem",
        "RankingDriftReport",
        "RankingProvenanceEntry",
        "RankingRobustnessReport",
        "RankingSensitivityInput",
        "CandidateRankingSensitivityReport",
        "RankingStabilityReport",
        "UncertaintyPressureSummary",
        "analyze_ranking_stability",
        "build_design_brief",
        "build_ranking_diagnostics",
        "build_ranking_provenance_report",
        "build_ranking_robustness_report",
        "build_ranking_sensitivity_report",
        "candidate_score_breakdown",
        "criterion_satisfaction_vector",
        "prioritize_candidates",
        "summarize_candidate_explainability",
        "summarize_liability_focus",
        "summarize_metric_coverage",
        "summarize_novelty_diversity",
        "summarize_ranking_drift",
        "summarize_uncertainty_pressure",
    ],
    "bijux_proteomics_intelligence.charter": [
        "DEFAULT_INTELLIGENCE_CHARTER",
        "DEFAULT_INTELLIGENCE_CHARTER_ENTRIES",
        "DEFAULT_INTELLIGENCE_MODULE_AUDIT",
        "IntelligenceCharterCapability",
        "IntelligenceCharterEntry",
        "IntelligenceModuleAuditEntry",
        "IntelligenceModuleClassification",
        "IntelligenceProductCharter",
        "list_intelligence_capabilities",
        "list_intelligence_charter_entries",
    ],
    "bijux_proteomics_intelligence.decision_paths": [
        "AnomalyInterpretationRecommendation",
        "CautiousAnomalyInterpretationPath",
        "FollowUpCandidatePath",
        "FollowUpCandidateRecommendation",
        "ReviewBoardDecisionPath",
        "build_cautious_anomaly_interpretation_path",
        "build_follow_up_candidate_path",
        "build_review_board_decision_path",
    ],
    "bijux_proteomics_intelligence.evidence_posture": [
        "EvidenceContradictionSummary",
        "EvidenceFreshnessSummary",
        "assess_recommendation_readiness",
        "summarize_evidence_contradictions",
        "summarize_evidence_freshness",
    ],
    "bijux_proteomics_intelligence.skeptical_review": [
        "AnalyticalValueSignal",
        "ReviewChallenge",
        "ReviewChallengeDomain",
        "ReviewChallengeSeverity",
        "SkepticalReviewReport",
        "build_skeptical_review_report",
    ],
    "bijux_proteomics_intelligence.benchmark_reviews": [
        "BenchmarkReviewArtifact",
        "BenchmarkReviewClaim",
        "WorkflowBenchmarkReview",
        "build_dda_benchmark_review",
        "build_dia_benchmark_review",
        "build_lfq_benchmark_review",
        "build_multiplex_benchmark_review",
        "build_ptm_benchmark_review",
    ],
    "bijux_proteomics_intelligence.candidates": [
        "CandidateAssayAgendaItem",
        "CandidateDecision",
        "CandidateLifecycleSummary",
        "CandidatePortfolio",
        "CandidateProposal",
        "CandidateReviewMovement",
        "CandidateReviewMovementReport",
        "CandidateRiskProfile",
        "CandidateScientificProfile",
        "CandidateScreeningResult",
        "CandidateStatus",
        "CandidateTransition",
        "CandidateVariantContext",
        "MutationAnnotation",
        "MutationBurdenSignals",
        "MutationRiskSummary",
        "ParetoFrontResult",
        "ParsedMutation",
        "PortfolioMutationBurdenSummary",
        "PortfolioRiskSummary",
        "PortfolioSelectionPolicy",
        "PortfolioSelectionResult",
        "SequenceRiskSignals",
        "TransitionAuditIssue",
        "build_candidate_assay_agenda",
        "build_candidate_review_movement_report",
        "build_candidate_scientific_profile",
        "build_mutation_annotations",
        "build_risk_profile",
        "mutation_burden_signals",
        "parse_mutation_token",
        "portfolio_status",
        "select_pareto_candidates",
        "select_portfolio_shortlist",
        "sequence_risk_signals",
        "summarize_candidate_lifecycle",
        "summarize_mutation_risk",
        "summarize_portfolio_mutation_burden",
        "summarize_portfolio_risk",
        "summarize_variant_context",
        "transition_candidate",
        "validate_transition_history",
    ],
    "bijux_proteomics_intelligence.evaluators": [
        "AdvancedIntelligenceReviewPacket",
        "AssessmentMetricCoverageReport",
        "ComparativeCandidateReviewPacket",
        "DecisionEscalationFlags",
        "EvaluatorPolicyBundle",
        "FinalDecisionRecommendation",
        "HoldPressureSummary",
        "HypothesisStatus",
        "IntelligenceDecisionSupportEnvelope",
        "IntelligenceOutputMode",
        "IntelligenceReviewPacket",
        "PortfolioDecisionReport",
        "ProgressionPolicy",
        "RedesignPolicy",
        "ReviewBoardEvidenceLine",
        "ReviewBoardPacket",
        "ScaleUpPolicy",
        "ScenarioAction",
        "ScenarioConfidenceSpread",
        "ScenarioDecisionConsensus",
        "ScenarioEvaluation",
        "ScenarioSetEvaluation",
        "ScenarioUncertaintyEntry",
        "SynthesisPolicy",
        "UncertaintyPreservingInterpretationSummary",
        "UnresolvedQuestionLedger",
        "build_advanced_review_packet",
        "build_comparative_candidate_review_packet",
        "build_final_decision_recommendation",
        "build_intelligence_decision_support_envelope",
        "build_intelligence_review_packet",
        "build_review_board_packet",
        "derive_decision_escalation_flags",
        "evaluate_all_scenarios",
        "evaluate_for_progression",
        "evaluate_for_redesign",
        "evaluate_for_scale_up",
        "evaluate_for_synthesis",
        "evaluate_portfolio_balance",
        "promote_intelligence_output_to_policy",
        "summarize_assessment_metric_coverage",
        "summarize_hold_pressure",
        "summarize_scenario_confidence_spread",
        "summarize_scenario_consensus",
        "summarize_uncertainty_preserving_interpretation",
        "summarize_unresolved_question_ledger",
    ],
    "bijux_proteomics_knowledge.references": [
        "GroundedDecisionRule",
        "RankingRuleGroundingLedger",
        "build_ranking_rule_grounding_ledger",
        "rule_grounding_map",
    ],
    "bijux_proteomics_intelligence.interpretation": [
        "AnnotationCategory",
        "BiologicalTheme",
        "BiologicalThemeExtraction",
        "ContaminantArtifactFinding",
        "ContaminantArtifactIntelligence",
        "AnalyticalContrastRecommendation",
        "AnalyticalContrastRecommendationReport",
        "AnalyticalContrastRejectionReason",
        "DifferentialAbundanceInterpretation",
        "DifferentialConditionSignal",
        "DifferentialStatisticalProvenance",
        "EnrichmentProvenance",
        "MissingnessPatternAnalysis",
        "MissingnessPatternEntry",
        "MissingnessPatternLabel",
        "OutlierInterpretationClass",
        "OutlierSampleExplanation",
        "PathwayInterpretationCaution",
        "PathwayInterpretationCautionCode",
        "PathwayInterpretationCautionReport",
        "ProteinAnnotationAssignment",
        "ProteinSetEnrichmentEntry",
        "ProteinSetEnrichmentReport",
        "PtmInterpretationReport",
        "PtmInterpretationSite",
        "QuantQcEvidenceIntegrationReport",
        "RankedEnrichmentEntry",
        "RankedEnrichmentReport",
        "RankedEntityScore",
        "RunInterpretationSignal",
        "RunInterpretationSummary",
        "SignalDirection",
        "analyze_missingness_patterns",
        "build_run_interpretation_summary",
        "compute_protein_set_enrichment",
        "compute_ranked_enrichment",
        "explain_outlier_samples",
        "extract_biological_themes",
        "integrate_quant_qc_evidence",
        "interpret_contaminant_artifacts",
        "interpret_differential_abundance",
        "interpret_ptm_sites",
        "recommend_experimental_contrasts",
    ],
    "bijux_proteomics_intelligence.outcomes": [
        "CandidateRejection",
        "RejectionActionPlan",
        "RejectionReasonCode",
        "RejectionSummary",
        "TieBreakExplanation",
        "build_rejection_action_plan",
        "summarize_rejections",
    ],
    "bijux_proteomics_intelligence.policies": [
        "FactorWeightValidationReport",
        "HoldPolicyConfig",
        "MetricCatalogAuditReport",
        "MetricDefinition",
        "MetricDirection",
        "ProgressionPolicyConfig",
        "RankingFactor",
        "RankingPolicy",
        "RankingPolicyLineage",
        "RedesignPolicyConfig",
        "ScientificMetricClass",
        "TieBreakRule",
        "audit_metric_catalog",
        "classify_metric_name",
        "ranking_policy_lineage",
        "validate_factor_weights",
        "validate_metric_catalog",
    ],
}

_INTELLIGENCE_EXPORTS = {
    name: (module_name, name)
    for module_name, names in _INTELLIGENCE_EXPORT_GROUPS.items()
    for name in names
}

__all__ = sorted(_INTELLIGENCE_EXPORTS)


def __getattr__(name: str) -> Any:
    """Load public intelligence exports lazily to avoid import-time cycles."""

    target = _INTELLIGENCE_EXPORTS.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attribute_name = target
    module = import_module(module_name)
    return getattr(module, attribute_name)
