"""Public workflow import surface helpers."""

from __future__ import annotations

from importlib import import_module
from typing import Any

_WORKFLOW_EXPORT_GROUPS = {
    "bijux_proteomics_runtime.workflows.advanced_diann_comparison": [
        "AdvancedDiannClaimChangeEntry",
        "AdvancedDiannClaimComparisonState",
        "AdvancedDiannParameterChangeEntry",
        "AdvancedDiannProteinChangeEntry",
        "AdvancedDiannProteinComparisonState",
        "AdvancedDiannRejectedRowChangeEntry",
        "AdvancedDiannRejectedRowComparisonState",
        "AdvancedDiannRuntimeComparisonReport",
        "compare_advanced_diann_runtime_outputs",
    ],
    "bijux_proteomics_runtime.workflows.failure_reports": [
        "WorkflowFailureReport",
        "build_workflow_failure_report",
        "write_workflow_failure_report",
    ],
    "bijux_proteomics_runtime.workflows.advanced_diann": [
        "AdvancedDiannDryRunInputCheck",
        "AdvancedDiannDryRunIssue",
        "AdvancedDiannDryRunOutputPlan",
        "AdvancedDiannDryRunReport",
        "AdvancedDiannDryRunStagePlan",
        "AdvancedDiannDryRunStatus",
        "AdvancedDiannRuntimeRunReport",
        "AdvancedDiannRuntimeStage",
        "AdvancedDiannRuntimeStageDecision",
        "AdvancedDiannRuntimeStatus",
        "dry_run_resumable_advanced_diann_workflow",
        "run_resumable_advanced_diann_workflow",
    ],
    "bijux_proteomics_runtime.artifacts": [
        "StepArtifact",
        "build_step_artifact",
    ],
    "bijux_proteomics_runtime.workflows.flagship_workflow_chain": [
        "FlagshipWorkflowBreakageFinding",
        "FlagshipWorkflowBreakageReport",
        "FlagshipWorkflowDeterminismReport",
        "FlagshipWorkflowChain",
        "FlagshipWorkflowScopeDossier",
        "FlagshipWorkflowStage",
        "FlagshipWorkflowStageProof",
        "WorkflowArtifactClaim",
        "WorkflowClaimKind",
        "build_flagship_workflow_chain",
        "build_flagship_workflow_scope_dossier",
        "compare_flagship_workflow_chains",
        "evaluate_flagship_workflow_breakage",
    ],
    "bijux_proteomics_runtime.workflows.acceptance": [
        "WorkflowAcceptanceDossier",
        "WorkflowFailureCategory",
        "WorkflowFailureTaxonomy",
        "WorkflowFailureTaxonomyEntry",
        "WorkflowProofBar",
        "WorkflowProofRequirement",
        "WorkflowStageAcceptance",
        "build_flagship_workflow_acceptance_dossier",
        "build_flagship_workflow_failure_taxonomy",
        "build_minimum_real_workflow_proof_bar",
    ],
    "bijux_proteomics_runtime.workflows.assurance": [
        "FlagshipOperatorPath",
        "WorkflowAssuranceLane",
        "WorkflowAssuranceMatrixRow",
        "WorkflowAssuranceTier",
        "build_flagship_operator_path",
        "build_workflow_assurance_matrix",
        "major_workflow_families",
        "simulation_contract_lane_ids",
        "workflow_assurance_lanes",
    ],
    "bijux_proteomics_runtime.workflows.benchmark_runs": [
        "BenchmarkArtifactBrowser",
        "BenchmarkArtifactEntry",
        "BenchmarkCostArtifact",
        "BenchmarkDigestRecord",
        "BenchmarkExecutionCostReport",
        "BenchmarkFailureRecoveryBundle",
        "BenchmarkPortabilityCheck",
        "BenchmarkReplayAudit",
        "BenchmarkReplayDecision",
        "BenchmarkRunMode",
        "BenchmarkRunProvenanceReport",
        "BenchmarkRunSpec",
        "BenchmarkRuntimeTruthRow",
        "build_benchmark_artifact_browser",
        "build_benchmark_execution_cost_report",
        "build_benchmark_failure_recovery_bundle",
        "build_benchmark_portability_check",
        "build_benchmark_replay_audit",
        "build_benchmark_run_provenance_report",
        "build_benchmark_run_specs",
        "build_benchmark_runtime_truth_surface",
        "run_benchmark_dda_generalization_import_path",
        "run_benchmark_dda_import_path",
        "run_benchmark_dia_generalization_review_path",
        "run_benchmark_dia_review_path",
        "run_benchmark_dia_import_path",
        "run_benchmark_lfq_generalization_review_path",
        "run_benchmark_lfq_review_path",
        "run_benchmark_multiplex_generalization_review_path",
        "run_benchmark_multiplex_review_path",
        "run_benchmark_ptm_generalization_review_path",
        "run_benchmark_ptm_review_path",
        "run_benchmark_targeted_generalization_review_path",
        "run_benchmark_targeted_review_path",
        "run_benchmark_sequence_path",
    ],
    "bijux_proteomics_runtime.workflows.black_box_reproducibility": [
        "RuntimeArtifactStabilityEntry",
        "RuntimeBlackBoxRerunGate",
        "RuntimeBlackBoxRerunIssue",
        "RuntimeBlackBoxVerificationRoute",
        "RuntimeEnvironmentContract",
        "RuntimeExecutionModeComparison",
        "RuntimeReplayChallenge",
        "RuntimeRerunRefusalEntry",
        "build_runtime_artifact_stability_reports",
        "build_runtime_black_box_rerun_gate",
        "build_runtime_black_box_verification_routes",
        "build_runtime_environment_contracts",
        "build_runtime_execution_mode_comparisons",
        "build_runtime_replay_challenges",
        "build_runtime_rerun_refusals",
    ],
    "bijux_proteomics_runtime.workflows.proof_accounting": [
        "RuntimeExecutionShortcutAudit",
        "RuntimeExecutionShortcutAuditEntry",
        "RuntimeExecutionShortcutAuditIssue",
        "RuntimeFlagshipProofGate",
        "RuntimeFlagshipProofGateIssue",
        "RuntimeProofClaimRow",
        "RuntimeProofMap",
        "RuntimeProofPromotionChecklist",
        "RuntimeProofPromotionChecklistItem",
        "build_runtime_execution_shortcut_audit",
        "build_runtime_flagship_proof_gate",
        "build_runtime_proof_map",
        "build_runtime_proof_promotion_checklist",
        "validate_runtime_execution_shortcut_audit",
    ],
    "bijux_proteomics_runtime.workflows.proof_classes": [
        "RuntimeProofClass",
    ],
    "bijux_proteomics_runtime.workflows.flagship_runs": [
        "FlagshipCrossFamilyRunBundle",
        "FlagshipRunArtifact",
        "FlagshipRunBundle",
        "FlagshipRunFailureReplayArtifact",
        "FlagshipRunFailureReplayCase",
        "FlagshipRunRegistry",
        "FlagshipRunRegistryEntry",
        "FlagshipRunStageLineageArtifact",
        "FlagshipRunStageLineageEntry",
        "FlagshipRuntimeSurfaceSnapshot",
        "build_flagship_cross_family_run_bundle",
        "build_flagship_run_bundle",
        "build_flagship_run_bundle_family",
        "build_flagship_run_failure_replay",
        "build_flagship_run_registry",
        "build_flagship_run_stage_lineage",
    ],
    "bijux_proteomics_runtime.workflows.handoffs": [
        "WorkflowOwnerPackage",
        "WorkflowStageHandoffContract",
        "build_flagship_workflow_handoff_contracts",
    ],
    "bijux_proteomics_runtime.workflows.flagship_workflow_manifest": [
        "FLAGSHIP_WORKFLOW_MANIFEST_PATH",
        "FlagshipWorkflowManifest",
        "FlagshipWorkflowManifestIssue",
        "FlagshipWorkflowManifestStageEntry",
        "build_flagship_workflow_manifest",
        "validate_flagship_workflow_manifest",
    ],
    "bijux_proteomics_runtime.workflows.packets": [
        "WorkflowPacketSerializationMode",
        "WorkflowStagePacketBoundaryContract",
        "build_workflow_stage_packet_boundary_contracts",
    ],
    "bijux_proteomics_runtime.workflows.paths": [
        "RuntimeReviewableOutputPath",
        "RuntimeSmokeWorkflow",
        "RuntimeWorkflowStep",
        "build_runtime_smoke_workflows",
        "run_reviewable_import_path",
        "run_reviewable_sequence_path",
    ],
    "bijux_proteomics_runtime.workflows.plans": [
        "DeterministicExecutionContract",
        "ExternalToolCapabilityIssue",
        "ExternalToolCapabilityReport",
        "ProteomicsDagPlan",
        "ReproducibleWorkflowBlueprint",
        "WorkflowDataType",
        "WorkflowDagEdge",
        "WorkflowDagNode",
        "WorkflowDagValidationIssue",
        "WorkflowDagValidationReport",
        "WorkflowCacheReuseDecision",
        "WorkflowCacheReuseDisposition",
        "WorkflowCacheReusePlan",
        "WorkflowArtifactKind",
        "WorkflowCacheMissReason",
        "WorkflowCheckpointStatus",
        "WorkflowExecutionMode",
        "WorkflowExecutionReadinessIssue",
        "WorkflowExecutionReadinessReport",
        "WorkflowInputRole",
        "WorkflowManifestExplanationEntry",
        "WorkflowManifestExplanationReport",
        "WorkflowPathKind",
        "WorkflowResumeKind",
        "WorkflowSchedulerKind",
        "WorkflowScientificSurface",
        "WorkflowStepKind",
        "WorkflowStepProvenanceEntry",
        "WorkflowStepProvenanceReport",
        "WorkflowStepReplayDisposition",
        "WorkflowStepTypeValidationIssue",
        "WorkflowStepTypeValidationReport",
        "WorkflowStreamingMode",
        "build_proteomics_dag_plan",
        "build_proteomics_workflow_runtime_bundle",
        "build_parallel_execution_plan",
        "validate_proteomics_workflow_step_types",
        "build_workflow_cache_reuse_plan",
        "build_workflow_runtime_validation_report",
        "validate_proteomics_dag_plan",
    ],
    "bijux_proteomics_runtime.workflows.reproducibility": [
        "RuntimeWorkflowBlueprint",
        "RuntimeWorkflowBlueprintStage",
        "RuntimeWorkflowBlueprintStep",
        "WorkflowRunDiffCategory",
        "WorkflowRunDiffEntry",
        "WorkflowRunDiffReport",
        "WorkflowRunSnapshot",
        "build_runtime_workflow_blueprint",
        "build_workflow_run_diff_report",
        "build_workflow_stable_error_envelope",
        "evaluate_large_artifact_upload_guard",
        "evaluate_workflow_api_cli_parity",
        "verify_portable_run_bundle",
    ],
    "bijux_proteomics_runtime.workflows.runs": [
        "DdaImportWorkflowRunReport",
        "DdaSearchHitInput",
        "DiaImportWorkflowRunReport",
        "DiaPrecursorQuantInput",
        "KnowledgeEvidenceInput",
        "KnowledgeReviewWorkflowRunReport",
        "MultiplexRuntimeWorkflowRunReport",
        "PtmRuntimeWorkflowRunReport",
        "QuantRuntimeWorkflowRunReport",
        "RuntimeWorkflowStatus",
        "SequenceToDigestWorkflowRunReport",
        "TargetedRuntimeWorkflowRunReport",
        "run_multiplex_workflow_end_to_end",
        "run_ptm_workflow_end_to_end",
        "run_quant_workflow_end_to_end",
        "run_targeted_workflow_end_to_end",
    ],
}

_WORKFLOW_EXPORTS = {
    name: (module_name, name)
    for module_name, names in _WORKFLOW_EXPORT_GROUPS.items()
    for name in names
}

__all__ = sorted(_WORKFLOW_EXPORTS)


def __getattr__(name: str) -> Any:
    """Load workflow exports lazily to avoid package-import cycles."""

    target = _WORKFLOW_EXPORTS.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attribute_name = target
    module = import_module(module_name)
    return getattr(module, attribute_name)
