# SPDX-License-Identifier: Apache-2.0
# Copyright © 2026 Bijan Mousavi

"""Canonical FASTA owner package for sequence intake and residue policy."""

from __future__ import annotations

from bijux_proteomics.sequences.fasta.models import (
    DecoyGenerationManifest,
    DecoyGenerationMode,
    DecoyGenerationReport,
    DuplicateAccessionPolicy,
    FastaDatabaseComposition,
    FastaDeduplicationReport,
    FastaFilterReport,
    FastaParseMode,
    FastaParseReport,
    FastaProvenanceManifest,
    FastaSequenceRecord,
    FastaStatsReport,
    NormalizedProteinRecord,
    ProteinSequence,
    RejectedFastaRecord,
    ResiduePolicyEntry,
    ResiduePolicyState,
    SequenceIssueSeverity,
    SequenceResiduePolicy,
    SequenceValidationIssue,
    SequenceValidationResult,
    TargetDecoyValidationReport,
    UniProtAccession,
    sequence_length,
)
from bijux_proteomics.sequences.fasta.parsing import (
    build_decoy_generation_manifest,
    build_decoy_generation_report,
    build_fasta_provenance_manifest,
    build_fasta_stats,
    compute_decoy_generation_reproducibility_hash,
    deduplicate_fasta_records,
    filter_fasta_records,
    generate_decoy_database,
    generate_decoy_records,
    normalize_protein_record,
    parse_fasta_document,
    parse_fasta_records,
    render_fasta_records,
    render_records_fasta,
    validate_protein_sequence,
    validate_target_decoy_database,
)
from bijux_proteomics.sequences.fasta.policies import (
    build_sequence_residue_policy,
    canonicalize_protein_reference,
    parse_uniprot_accession,
    sequence_checksum,
)

__all__ = [
    "DecoyGenerationManifest",
    "DecoyGenerationMode",
    "DecoyGenerationReport",
    "DuplicateAccessionPolicy",
    "FastaDatabaseComposition",
    "FastaDeduplicationReport",
    "FastaFilterReport",
    "FastaParseMode",
    "FastaParseReport",
    "FastaProvenanceManifest",
    "FastaSequenceRecord",
    "FastaStatsReport",
    "NormalizedProteinRecord",
    "ProteinSequence",
    "RejectedFastaRecord",
    "ResiduePolicyEntry",
    "ResiduePolicyState",
    "SequenceIssueSeverity",
    "SequenceResiduePolicy",
    "SequenceValidationIssue",
    "SequenceValidationResult",
    "TargetDecoyValidationReport",
    "UniProtAccession",
    "build_decoy_generation_manifest",
    "build_decoy_generation_report",
    "build_fasta_provenance_manifest",
    "build_fasta_stats",
    "build_sequence_residue_policy",
    "canonicalize_protein_reference",
    "compute_decoy_generation_reproducibility_hash",
    "deduplicate_fasta_records",
    "filter_fasta_records",
    "generate_decoy_database",
    "generate_decoy_records",
    "normalize_protein_record",
    "parse_fasta_document",
    "parse_fasta_records",
    "parse_uniprot_accession",
    "render_fasta_records",
    "render_records_fasta",
    "sequence_checksum",
    "sequence_length",
    "validate_protein_sequence",
    "validate_target_decoy_database",
]
